### ISSUE TITLE
access to frame size functions without ZSTD_STATIC_LINKING_ONLY

### ISSUE THREAD

**Issue by shawnl** [facebook/zstd#1018]
In order to robust error handling in systemd's zstd preliminary patch I needed ZSTD_STATIC_LINKING_ONLY

for ZSTD_frameHeaderSize_prefix and ZSTD_frameHeaderSize and perhaps also ZSTD_findDecompressedSize

https://github.com/systemd/systemd/pull/8207

**Comment by shawnl** [comment]
also ZSTD_findDecompressedSize

**Comment by terrelln** [comment]
I've commented on your PR. `zstd_errors.h` is now considered stable, but only since v1.3.1. If you need to support compiling and linking against different versions, where one is earlier than v1.3.1, you can't rely on the error codes being correct.

As long as you compile against zstd >= 1.3.1, error detection with `ZSTD_isError()` will always work, even when linking against zstd < 1.3.1, though the error codes might be wrong.

**Comment by shawnl** [comment]
Thanks for your review.
