### ISSUE TITLE
Store compression level

### ISSUE THREAD

**Issue by roussec** [facebook/zstd#1066]
Is there a store compression level (where data is just written without compression)? I think this would be very helpful.

**Comment by Cyan4973** [comment]
There is no store compression level.
`zstd` has the ability to create ["uncompressed blocks"](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#blocks), but this stage cannot be "forced" externally, it is decided by the algorithm, when it believes that compressing a block is not beneficial enough.

Note that I'm not aware of any other compressor (like `gzip`, `xz` or `bzip2`) offering this capability.
This is more likely the territory of archivers (like `7zip`), which operate at a different responsibility layer.

**Comment by roussec** [comment]
Thanks Yann. Having a store compression level would make it easy to compare compression performance easily without the need for having a separate code path for no compression. zlib has Z_NO_COMPRESSION.

**Comment by Cyan4973** [comment]
As far as I know, `Z_NO_COMPRESSION` is useful to throttle zlib, in situations where it's necessary to save cpu cycles, due to a burst activity for example, at the temporary expense of bandwidth.

If that's the objective, not only do we offer a high speed mode which is much faster then `zlib -1` and should reduce the situations where it's necessary to cut off compression,
we will also propose faster settings, using negative compression levels (which are already available for users of `dev` branch). You can push the negative value as far as you want. At some point, it becomes equivalent to "no compression at all".

For example, try compression level `-200000` : 
```
./zstd -b --fast=200000 calgary.tar                                                                      
calgary.tar       :   3265536 ->   3265621 (1.000),3547.7 MB/s ,9109.7 MB/s
```

**Comment by Cyan4973** [comment]
negative compression level and `--fast=#` are now part of [release v1.3.4](https://github.com/facebook/zstd/releases/tag/v1.3.4)

**Comment by roussec** [comment]
Thanks a lot!
