### ISSUE TITLE
[linux-kernel] Update to latest zstd

### ISSUE THREAD

**Issue by peskal** [facebook/zstd#1101]
The linux kernel patches have not been updated since Aug 31 2017. Are there any plans to incorporate the latest changes from v1.3.4 into the kernel patches?

**Comment by terrelln** [comment]
Yes, I plan on updating the kernel zstd from time to time. Since it takes some work, I don't intend to track every release. I'll probably make an update in 6 months to a year, unless there is a good reason to do it earlier. I am also keeping track of security fixes to back port earlier, but there haven't been any applicable fixes yet.

**Comment by peskal** [comment]
Cool, thanks. I'm most interested in this because I want to get some of the new performance improvements into the kernel. I'd like to tackle this this and submit a pull request if that's okay, but I don't see any documentation on how the porting is normally done. Would you be able to give me some pointers on where to start? Which files map to what, etc.? Thanks!

**Comment by harkue** [comment]
I suggest zstd publish a roadmap or milestone for further features on wiki page.

**Comment by terrelln** [comment]
Closing in favor of #1638.
