### ISSUE TITLE
[Q] defining dictionary for contiguous sequences

### ISSUE THREAD

**Issue by chbrandt** [facebook/zstd#1125]
Hi
 I have many (thousands) of large (>GB) text files containing genomics (`fastq` files), which I want to compress using a common dictionary; since the genomics vocabulary is quite limited (if we consider fixed chunks: {A,C,G,T,N}), I understand that using `zstd` with a common dictionary is good approach.

 But I have a doubt about *how to declare the dictionary* to `zstd`. Sorry if such information is already out there, besides the README and wiki, I went to [zstd-manual](http://facebook.github.io/zstd/zstd_manual.html) but couldn't find.

**Rational:**
 A sample of a genomic code is given below (many of such strings may be available in a (fastq) file; each string may have different lengths):
```
GGCATTTAGTAGCGGTAAAGTTAGACCAAACCATGAAACCAACATAAACATTATTGCCCGGCGTACGGGGAAGGACGTCAATAGTCACACAGTCCTTGN
```

 As a first step, to approach the `zstd` engine, I would like to try the dictionary training as explained in the [README](https://github.com/facebook/zstd#dictionary-compression-how-to):
```
$ zstd --train FullPathToTrainingSet/* -o dictionaryName
$ zstd -D dictionaryName FILE1
$ zstd -D dictionaryName FILE2
# ...
$ zstd -D dictionaryName FILEN
```

 The dictionary I'm planning to use has *length-4 strings* containing all possible combination of `{A,C,G,T,N}` in a size-4 set:
```
AAAA
AAAC
...
ACGT
TTGN
...
```

**Question:**
* How do I declare such dictionary to `zstd`?
* Also, is such approach, using slices of bigger (but unknown/random) strings, reasonable?

Thanks.

**Comment by Cyan4973** [comment]
#### On dictionary compression

Note that dictionary compression is mostly recommended for small files.
By "small" we mean "anything < 64 KB".
It's not that it's useless for large files, but dictionary compression benefits are simply too small to be worth their dependency.

I read that you 
> have many (thousands) of large (>GB) text files containing genomics

Unless these files are cut into small independent segments, which is not described, the benefits from dictionary compression (in KB range) are going to be insensible compared to these large files (GB range).

> the genomics vocabulary is quite limited (if we consider fixed chunks: {A,C,G,T,N})

This will be taken advantage of, using the Huffman compressor embedded into Zstandard, without any extra effort.

> But I have a doubt about how to declare the dictionary to zstd

The samples command lines you mention look good to me.

> The dictionary I'm planning to use has length-4 strings containing all possible combination of {A,C,G,T,N} in a size-4 set
> How do I declare such dictionary to zstd?

In which case, produce the set, save it into a file, a provide the file directly as a dictionary, using `-D dictFilename` command. You don't need the `--train` stage, since you already know which dictionary you want.


But then again, if you want to compress big files in the GB range, dictionary is unlikely to provide tangible gains.

**Comment by chbrandt** [comment]
Hi @Cyan4973 

Thanks for such nice answer.

> But then again, if you want to compress big files in the GB range, dictionary is unlikely to provide tangible gains.

Then I got it completely wrong. I thought that in my case -- genomics --, where redundancy may be significant (I referred to 4-size strings, but repeated "words" here may be quite big (~20 chars)), dictionaries would be effectively the way to go. In particular, the possibility to have a central one shared among all the files -- in this case, even if the gain *per file* was not much different from a common algorithm (e.g, gzip), the overall (considering the entire data archive) gain would be substantial.

*I am no expert in compression, you noted that by now; Do you have any indication of direction for me to follow?*

> Unless these files are cut into small independent segments, which is not described, the benefits from dictionary compression (in KB range) are going to be insensible compared to these large files (GB range).

Indeed I *can* cut those files in (very) small segments (down to bytes actually); they are [FastQ](https://en.wikipedia.org/wiki/FASTQ_format) files with lots of sequences in.

**Comment by Cyan4973** [comment]
Generally speaking, if compression ratio is your only concern, you are better off grouping all files together and compressing them as a single large blob. This will give maximum compression ratio.

But sometimes, that strategy is not possible, because it can be valuable to extract one element without decompressing the entire blob, for improved access latency.
In this case, it's necessary to compress data into smaller independent blobs.
But in such case, compression ratio will drop. 
The smaller the blob, the better the access speed, but the worse the compression ratio.

Dictionary compression is a way to mitigate that loss.
Thanks to the "shared knowledge" present in dictionary, the drop will be much lower, while preserving the ability to random-access any little blob independently.

That's the use case for dictionary compression.
It won't improve compression ratio for already large blobs. Large blob already contain all they need. Whatever is contained in the dictionary will merely improve the first few KB, which is nothing compared to the larger blob.

**Comment by chbrandt** [comment]
OK. Cool. Thanks!
