### ISSUE TITLE
Compression ratio worse than zlib for small blobs

### ISSUE THREAD

**Issue by jmuchemb** [facebook/zstd#1134]
By "small", I mean less than ~ 4 kB

I am currently evaluating compression algorithms for an object database that is quite big. To give a picture:
- size on disk: 814 GB
- number of records: 1.26e9
- compressible records: 87.8% with zlib=9 (1.1e9)

So far, we were using zlib at default level and I hoped that switching to zstd would bring better ratio without slowing down. I was disappointed by the following results, after I recompressed the above compressible records:

alg | total size | min | max
--- | ---------- | --- | ---
none | 737254579789 | 29 | 169130485
zstd | 440032914096 | 33 | 13765186
zstd=9 | 436601295547 | 33 |13444532
zlib | 423845118650 | 27 | 13760475
zlib=9 | 423161420348 | 27 | 13759835

- 'zlib' and 'zstd' are at default level
- 'total size' sums up the raw data (excluding internal structure and transaction metadata)
- 'min'/'max' are the size of the smallest/biggest blog
- average uncompressed blob size: 668 bytes

The DB actually contains objects of any size up to 11kB, and I made more stats. The following graph shows the average compression ratio as a function of the uncompressed size (with some smoothing, otherwise it would be hard to read, and GitHub does not even want SVG):
![graph1](https://user-images.githubusercontent.com/11165223/40017079-94d0882c-57b8-11e8-9ac3-a631093dd4ca.png)
To better compare zlib vs zstd, here is another one with ratio relative to zlib=9:
![graph2](https://user-images.githubusercontent.com/11165223/40017105-acb21582-57b8-11e8-9a51-a74a150ea127.png)
That's where I see that for this dataset, zstd only gets better for blobs biggest than 4 kB.

The following examples are zlib compressed and encoded base16:

**Example 1:** the smallest compressible record (29 bytes)

    78DA4B760A294A4D2DD6F3F70733B8607421A39E9F1E008FF308E7

zlib saved 2 bytes. With zstd, our DB engine would have stored it uncompressed.

**Example 2:** 6111753 blobs are 43 bytes uncompressed

    78DA4B760A294A4D2DD6F3F70433B8607421A39E061084321A7A3396004121931E0020D30C43

zlib: 38
zstd: 47

Again, bigger than uncompressed.

**Example 3:** 122953841 blobs are 153 bytes uncompressed

    78DA35CA4B0AC3300C04509C4FD3A49F7374E5437457B2E8A6398010260D142B63F9FE543664367A8C869F9F1482FAF7AB623A2E9C7F58968152DE94229AD92D1DA90ADA2216D9D199DA750BE80B24AE38197AC9DF9030181B259CCB5C29FD3096959262AA2FC6A516ACB85644C66D76D982BBFF0330F42AFD

zlib: 121
zstd: 127
zstd=9: 127
zstd=22: 128

By curiosity, I tried max zstd compression and was surprised to see even worse results. 

**Example 4:** 62375119 blobs are 312 bytes uncompressed

    78DA458FBB0E824010457D8BE0B3B2A5A4A2F30340114D34A891C4169709E003985D6CFC7A6184EC6D6693734EB1CCBE7200617A1E3DD4E662DB34CAF933E7725AE996104994BE212DB063F84AAB5AF7BBC62E6BF27D9DD7177BC5D95F506B07E953B718CB3E65DD97F5060771656964AD8332E33894DC4185F892B80B59C4833C4E986E852107217024DD2DAAE44EC9BDC20BF2384B0135A9B838264521C5E72F9C48B8C329C1FF6F6FC783EEDD1FC00A9C49678FF3CA29CAE1C2FC01083A50A2

zlib: 193
zstd: 212
zstd=9: 211
zstd=22: 211

For those who wonder what kind of object DB it is, see [NEO](https://neo.nexedi.com/), which implements a storage backend for [ZODB](http://www.zodb.org/). We'd use the Python bindings I wrote at https://pypi.org/project/cython-zstd/ (I use the simple API).

**Comment by Cyan4973** [comment]
Thanks for this very detailed analysis @jmuchemb .

Yes, this can indeed happen.
For small data, `zstd` cannot flex its larger window advantage.
Which means, whatever gains can still be produced are now down to encoding process.
While `zstd` encoding is generally more precise, compressing a bit more, this accuracy also cost a bit more header size, so it starts with a small disadvantage. It doesn't take long to catch up, but a few kilobytes seems within this catch-up range.

There is however one more suspect to explain such outcome : minimum match size.
For both zstd and zlib, this minimum is defined as 3 bytes.
But zstd uses heuristics for speed, which basically make it not even try below 4 bytes.
This is generally a _good bet_, but for some datasets, it's not. And perhaps more importantly, the smaller `srcSize`, the more important it is to look for small matches.

`zstd` only starts considering matches of size 3 at high enough compression levels, where it's possible to spend energy in the comparison of choices, and therefore only selects matches of size 3 when they do trigger some benefit. For small data <= 4KB, this means levels 10+.

However, we have a second issue at these modes. It happens I was considering writing an article about it, because it's fairly complex and interesting. To summarize, the high compression modes rely on "statistics" to accurately measure the gains / benefits of each choice. Statistics are built automatically, while running through the file. But at the beginning, there's nothing. So statistics are poor / inaccurate, and choices are misguided. The algorithm converges reasonably well, but unfortunately not fast enough for small files.

Hopefully, this is solvable, at a CPU cost. The combination of very small data and very high compression is a use case we have not needed to support so far. But this is going to change. Therefore, expect some improvement in the not so distant future.

Also, 
some of the sizes mentioned in this analysis are definitely tiny. Anything < 1 KB offers relatively poor prospects for compression, as the algorithm has very little time to learn and adapt from input. For such a scenario, we highly recommend the usage of dictionary compression. The gains can be very significant. However, it changes the way data is compressed / decompressed, since it requires managing an additional object, the dictionary.

**Comment by KrzysFR** [comment]
I tried replicating the test with your samples, and adding a very basic dictionary to zstd offsets the difference with zlib:

Very basic dictionary used created by eyeballing the samples and taking only what was present in all of them.
> hexa: `634254726565732E4F4F42547265650A4F4F42547265650A71012E2828282855080000000000034B015503`
> text: `cBTrees.OOBTree<0A>OOBTree<0A>q<01>.((((U<08><00><00><00><00><00><03>K<01>U<03>`

_I have also added lz4 into the mix for comparison._

Sample: __29__ bytes
> hexa: `634254726565732E4F4F42547265650A4F4F42547265650A71012E4E2E`
> text: `cBTrees.OOBTree<0A>OOBTree<0A>q<01>.N.`

| algo | size | baseline | ratio |
|-|-|-|-|
| raw |  29 | - | - |
| lz4 |  23 | 0.793x | 1 : 1.261 |
| zlib -1 |  21 | 0.724x | 1 : 1.381 |
| __zlib -5__ |  __21__ | 0.724x | 1 : 1.381 |
| zlib -9 |  21 | 0.724x | 1 : 1.381 |
| __zstd -2__ |  __33__ | 1.138x | 1 : 0.879 |
| zstd -10 |  33 | 1.138x | 1 : 0.879 |
| zstd -22 |  33 | 1.138x | 1 : 0.879 |
| __zstd -2 + dict__ |  __17__ | 0.586x | 1 : 1.706 |
| zstd -10 + dict |  18 | 0.621x | 1 : 1.611 |
| zstd -22 + dict |  18 | 0.621x | 1 : 1.611 |

Sample: __43__ bytes
> hexa: `634254726565732E4F4942547265650A4F4942547265650A71012E282828285501314B017474747471022E`
> text: `cBTrees.OIBTree<0A>OIBTree<0A>q<01>.((((U<01>1K<01>ttttq<02>.`

| algo | size | baseline | ratio |
|-|-|-|-|
| raw |  43 | - | - |
| lz4 |  38 | 0.884x | 1 : 1.132 |
| zlib -1 |  32 | 0.744x | 1 : 1.344 |
| __zlib -5__ |  __32__ | 0.744x | 1 : 1.344 |
| zlib -9 |  32 | 0.744x | 1 : 1.344 |
| __zstd -2__ |  __47__ | 1.093x | 1 : 0.915 |
| zstd -10 |  46 | 1.070x | 1 : 0.935 |
| zstd -22 |  46 | 1.070x | 1 : 0.935 |
| __zstd -2 + dict__ |  __32__ | 0.744x | 1 : 1.344 |
| zstd -10 + dict |  34 | 0.791x | 1 : 1.265 |
| zstd -22 + dict |  32 | 0.744x | 1 : 1.344 |

Sample: __153__ bytes
> hexa: `634254726565732E4F4942547265650A4F4942547265650A71012E2828282855076172746973616E71024B0155046173736F71034B015504636F6F7071044B01550367696571054B0155036F6E6771064B0155056F7468657271074B015502736171084B0155047361726C71094B015503736173710A4B0155027363710B4B015503736373710C4B015503736E63710D4B0174747474710E2E`
> text: `cBTrees.OIBTree<0A>OIBTree<0A>q<01>.((((U<07>artisanq<02>K<01>U<04>assoq<03>K<01>U<04>coopq<04>K<01>U<03>gieq<05>K<01>U<03>ongq<06>K<01>U<05>otherq<07>K<01>U<02>saq<08>K<01>U<04>sarlq<09>K<01>U<03>sasq<0A>K<01>U<02>scq<0B>K<01>U<03>scsq<0C>K<01>U<03>sncq<0D>K<01>ttttq<0E>.`

| algo | size | baseline | ratio |
|-|-|-|-|
| raw |  153 | - | - |
| lz4 |  140 | 0.915x | 1 : 1.093 |
| zlib -1 |  115 | 0.752x | 1 : 1.330 |
| __zlib -5__ |  __115__ | 0.752x | 1 : 1.330 |
| zlib -9 |  115 | 0.752x | 1 : 1.330 |
| __zstd -2__ |  __127__ | 0.830x | 1 : 1.205 |
| zstd -10 |  127 | 0.830x | 1 : 1.205 |
| zstd -22 |  127 | 0.830x | 1 : 1.205 |
| __zstd -2 + dict__ |  __116__ | 0.758x | 1 : 1.319 |
| zstd -10 + dict |  116 | 0.758x | 1 : 1.319 |
| zstd -22 + dict |  115 | 0.752x | 1 : 1.330 |

Sample: __312__ bytes
> hexa: `634254726565732E4F4F42547265650A4F4F42547265650A71012E28282828550F455250352041737369676E6D656E7471022855080000000000037A437103634254726565732E4F4942547265650A4F4942547265650A710474515511455250352042616E6B204163636F756E7471052855080000000000037A44710668047451550B455250352043617265657271072855080000000000037A457108680474515517455250352047656F67726170686963204164647265737371092855080000000000037A46710A68047451550E455250352054656C6570686F6E65710B2855080000000000037A47710C680474515508455250352055726C710D2855080000000000037A48710E68047451550F4552503520584D4C204F626A656374710F2855080000000000037A497110680474517474747471112E`
> text: `cBTrees.OOBTree<0A>OOBTree<0A>q<01>.((((U<0F>ERP5 Assignmentq<02>(U<08><00><00><00><00><00><03>zCq<03>cBTrees.OIBTree<0A>OIBTree<0A>q<04>tQU<11>ERP5 Bank Accountq<05>(U<08><00><00><00><00><00><03>zDq<06>h<04>tQU<0B>ERP5 Careerq<07>(U<08><00><00><00><00><00><03>zEq<08>h<04>tQU<17>ERP5 Geographic Addressq<09>(U<08><00><00><00><00><00><03>zFq<0A>h<04>tQU<0E>ERP5 Telephoneq<0B>(U<08><00><00><00><00><00><03>zGq<0C>h<04>tQU<08>ERP5 Urlq<0D>(U<08><00><00><00><00><00><03>zHq<0E>h<04>tQU<0F>ERP5 XML Objectq<0F>(U<08><00><00><00><00><00><03>zIq<10>h<04>tQttttq<11>.`

| algo | size | baseline | ratio |
|-|-|-|-|
| raw |  312 | - | - |
| lz4 |  229 | 0.734x | 1 : 1.362 |
| zlib -1 |  188 | 0.603x | 1 : 1.660 |
| __zlib -5__ |  __187__ | 0.599x | 1 : 1.668 |
| zlib -9 |  187 | 0.599x | 1 : 1.668 |
| __zstd -2__ |  __214__ | 0.686x | 1 : 1.458 |
| zstd -10 |  210 | 0.673x | 1 : 1.486 |
| zstd -22 |  210 | 0.673x | 1 : 1.486 |
| __zstd -2 + dict__ |  __188__ | 0.603x | 1 : 1.660 |
| zstd -10 + dict |  188 | 0.603x | 1 : 1.660 |
| zstd -22 + dict |  188 | 0.603x | 1 : 1.660 |

Using a better dictionary would probably yield even better results (there is a lot of "ERP5 ..." and other field prefixes that could probably be part of the dictionary itself.

Though, I'm not seeing much gains using higher compression levels, probably because they are still too small, and the dictionary used is not very good?

**Comment by KrzysFR** [comment]
> How do you get 23 and 21 bytes for lz4 and zlib ? I get 27 for both (tried with https://pypi.org/project/lz4/ and the builtin zlib module of Python).

Nothing special, I'm probably using deflate for zlib. Both it and lz4 are called via interop using versions build some years ago. Looking at the difference (4 bytes) maybe your version is outputing some additional header that contain the original size, or some other optional extra field?

I've played with using dictionaries to compress small documents, and the best approach seem to start with a standard dictionary that is called "gen 0", and use that to compress let's say the first N documents. After N docs added/mutated, or with some periodicity, get a random sample of K existing documents, train a new dictionary with them ("gen 1"), do some test compression, and if its better than at least 5% or 10%, then use it for all new documents or mutations. You need to add an extra 1 bytes or 2 in your object header to store the dictionary id, and keep all previously used dictionaries somewhere (so that you don't need to recompress ALL the documents when you create a new gen). As long as the threshold to create a new dictionary generation is high, you should not end up with that many, and you'll be able to cache them in memory. 

That way, you always have a dictionary that stays efficient if your data start changing completely at some point. A trivial example of that is that if you stores dates in JSON, most of the recent documents will have a fragment like `...", "modifiedUtc"="2018-05-15T...` and new month, they will be come `...2018-06-...` or next year `...2019-01-...`. If you update the dictionary periodically, it will probably pick up the new timestamp fragments and become efficient again.

**Comment by jmuchemb** [comment]
> Nothing special, I'm probably using deflate for zlib. Both it and lz4 are called via interop using versions build some years ago. Looking at the difference (4 bytes) maybe your version is outputing some additional header that contain the original size, or some other optional extra field?

I see. The difference for zlib is rather 6 bytes and it's the header (2 bytes) and 4-bytes checksum around the deflate result. For lz4, there's a header of 4 bytes for the uncompressed size. In examples 1-3, zstd has a header of 6 bytes (magic number and uncompressed length).

**Comment by jmuchemb** [comment]
What's the resolution ? Fixed or wontfix ?

I waited for a new release, to test the code before commenting. According to the changelog, the improvements seem to be mostly about speed.

I tried the above test cases and saw no improvement except for the biggest blobs at high level:

- example 3: 128 -> 126 at level 22  (zlib: 121)
- example 4: 211 -> 206 & 205 at levels 9 & 22 respectively  (zlib: 193)

**Comment by sebres** [comment]
> Anything < 1 KB is considered small 

1KB - sure, but... I got similar behavior for 32KB (non-pretty formatted) JSON, compressed to:
- 5KB - 6KB by GZ or ZLIB
- 8KB - 9KB by ZSTD (single threaded, l.1 - l.22) with `ZSTD_compress` or `ZSTD_compress2`
- 5KB - 6KB by ZSTD (single threaded, l.1 - l.22) with `ZSTD_compressStream2` (using zstd-cli that obviously uses `ZSTD_compressStream2`)

Unfortunately no time at the moment to investigate deeper what happens there exactly.

Should not this be revisited, at least for `ZSTD_compress` or `ZSTD_compress2` cases (perhaps a handbrake is applied somewhere there).

**Comment by Cyan4973** [comment]
32 KB should be enough for `zstd` to perform reasonably well compared to zlib.
I could imagine the lower "fast" levels to be at a disadvantage here, due to their tendency to aim for matches of length >= 4,
but the higher compression levels should not have this disadvantage.

Therefore, if you observe persistent compression ratio issues in these scenarios, we would be glad to know more, and try to find a mitigation.

On the proposed scenario, `ZSTD_compress2` should always be at least as good as `ZSTD_compressStream2`, so the reported difference is unexpected. That's also something we would like to observe directly in order to fix it.

**Comment by sebres** [comment]
> On the proposed scenario, ZSTD_compress2 should always be at least as good as ZSTD_compressStream2

Indeed, trying to write PoC for that (tested with almost 100 different JSON5 streams), I don't see previous behavior anymore.
Either it was something extremely special (cannot find this particular data anymore), or it was some mistake of me (compared bananas with cucumbers, like comparison of string lengths resp. size in bytes in utf-8 with single-byte encoding or something similar).
I'll try it later with more data and provide the PoC if I get this reproducible. If not, please apologize for noise.
