### ISSUE TITLE
Default compression level undocumented/unexposed

### ISSUE THREAD

**Issue by ajkr** [facebook/zstd#1148]
Is it possible to either (1) document in the public API that compression level zero will always be sanitized to ZSTD_CLEVEL_DEFAULT, or (2) expose ZSTD_CLEVEL_DEFAULT in the public API? Please correct me if I'm wrong, but I couldn't find either of these, in which case it doesn't seem there's a way to use ZSTD default compression level that's guaranteed not to change in the future.

**Comment by Cyan4973** [comment]
That's a very good point @ajkr .

The situation regarding level `0` wasn't completely clear recently.
For sure, it always meant "default", 
but "default" used to mean "level 1" in the early days of `zstd`, and now it's "level 3".
It was changed to "level 3" because the cli default level is `3`,
so the expectation was that both api and cli should feature the same default.

With the introduction of negative levels though,
it feels somewhat strange to feature a level `0`, now inserted between `1` and `-1`,
which is actually a lot slower than both, 
rather than respecting a kind of continuity between `1` and `-1`.

So, as you can see, the situation is not so stable for the meaning of "level 0" and "default".

Default (and level 0) was nonetheless left to `3`, out to fear of breaking a behavior some users might rely upon. It might remain like this, but I wouldn't advise to rely on this.

If your application relies on using "level 3", it should preferably call the api using "level 3".
This is, by definition, a lot more stable than depending on the current definition of level 0.

This does not dispense us from better documenting this behavior.
And both your suggestions look good to me.

**Comment by ajkr** [comment]
Thanks Yann. We ended up hardcoding 3 in our application for now. Feel free to close this issue if you don't need it.
