### ISSUE TITLE
Serialising and deserialising ZSTD_CCtx and Dictionary

### ISSUE THREAD

**Issue by atris** [facebook/zstd#1176]
I am looking to store ZSTD_CCtx and ZSTD Dict for faster compression and decompression. Are their existing serialising and deserialising method that I can use?

**Comment by Cyan4973** [comment]
I guess you mean serialising and deserialising operations in order to save, and then later read, this data structure from some storage device ?

I'm afraid there exist no such thing.

For CCtx, it seems not worth it.
If you need one CCtx, just create a new one.
The new CCtx will quickly achieve some light initialization and reserve just enough memory for next operation to succeed. 
I can't imagine a reason why reading a serialized version would prove any faster or more efficient.

For dictionary, I guess the raw dictionary itself could be considered a sort of raw serialized format.
Though, to be complete, its transformation into `CDict` or `DDict` costs some initialization time.
This is more sensible on the `CDict` side, which needs to populate larger tables,
so it's recommended to keep `CDict` in memory during its usage period.
Since it's used as read-only object, it can be shared without restriction by any number of threads.

Now, if you need to keep a large amount of `CDict` in memory, this could end up requiring a large amount of RAM, which could be a problem.
In which case, the recommended method is to create a "CDict cache", keeping in memory only the hottest dictionaries, within a pre-defined memory budget, and loading new ones on demand.
But that's an area of responsibility beyond `zstd` library's scope.

**Comment by atris** [comment]
Thanks a lot!
