### ISSUE TITLE
Patent lawsuit status?

### ISSUE THREAD

**Issue by lazerhawk** [facebook/zstd#1180]
So apparently Realtime Data LLC (which other people sometimes have the opinion of characterizing as a non-practicing entity, with offices in the eastern district of texas conveniently near the lawyer preferred patent court) is suing Facebook over Zstandard.

[https://news.bloomberglaw.com/ip-law/facebook-hit-with-patent-suit-over-data-compression-tech](url)

Are we going to witness the power of the fully armed and operational battlestation that is Facebook's legal department, or are they going to settle out of court (and if they settle, what's the fallout on developers and users)?

Naturally Yan and Facebook probably can't comment due to pending litigation, but a question for other contributors, should we be worried?

**Comment by JarekDuda** [comment]
[Very general patents from 1998-1999](https://www.law360.com/cases/5b16ca8c656b3a1d99000001), single [patent mass-producer](https://patents.justia.com/inventor/james-j-fallon), [LLC](https://en.wikipedia.org/wiki/Limited_liability_company), materials and discussion:
https://encode.ru/threads/2119-Zstandard?p=56966&viewfull=1#post56966

**Comment by xemasiv** [comment]
Oh boy, hopefully Facebook will stand their ground on this middle-out algorithm.

Google results for `Realtime Data LLC` already shows that they kinda make a living out of this :sob:

**Comment by lazerhawk** [comment]
I suppose since there's been some press about it this week as well, Google has been trying to patent Mr. Duda's ANS stuff, though he has been somewhat successful in fighting them off in europe. 

There is the interesting situation that Zstandard now has ANS in it. Would that also mean a heavyweight patent fight between Google and Facebook as well, if Google succeeds in patenting ANS extensions?

**Comment by scottcarey** [comment]
Maybe FB can take up the nuclear option defense:

Software patents are NOT VALID, because of the following:

1. It is not legal to patent mathematics
2. By the curry-howard correspondence, https://en.wikipedia.org/wiki/Curry%E2%80%93Howard_correspondence all software programs are equivalent to descriptions of mathematical proofs.

Therefore by this correspondence, software patents are intellectual property about how to go about solving mathematical proofs (2).  It is invalid to assert the right to own how to go about solving mathematical proofs due to (1).

**Comment by Cyan4973** [comment]
Case dismissed
