### ISSUE TITLE
Minor behavior changes between 1.1.x and 1.3.x for ZSTD_TARGETLENGTH_MIN and ZBUFF_decompressInit

### ISSUE THREAD

**Issue by KrzysFR** [facebook/zstd#1219]
While upgrading from 1.1.x to 1.3.x I found a few minor changes in my unit tests, that may or may not be of importance:

- I saw Target Length values for low compression levels lower than `ZSTD_TARGETLENGTH_MIN` that is (or was?) defined as 4. It is now only defined in the linux-kernel contrib folder and is not defined in the main library? Since the compression parameters tables does define in the 'TL' column values as low as 0 or 1 for this parameter, maybe this constant is obsolete and values lower than 4 are perfectly normal? There is also `ZSTD_TARGETLENGTH_MAX` defined as 999 but again only referenced in the linux-kernel patches.

- `ZBUFF_decompressInit()` previously could only return `0` (or an error code), but since its deprecation it now returns the result of ZSTD_initStream` which will return `5` (length of some header). This does not seem to have any impact on anything but it was triggering some asserts in my debug builds.

_Also, for people that cannot use `zstd.h` directly and have to redefine all the constants in a different language, the values of enum `ZSTD_strategy` have all been shifted by 1, and the values for error codes have all been changed as well_.

**Comment by terrelln** [comment]
Thanks for the notes!
* The target length can now be any value, so there is no need for min/max.
* The strategies aren't part of the stable API, and may change again in the future.
* The error codes are now stable, and won't change in the future (though we may add more).

**Comment by Cyan4973** [comment]
Thanks for feedback @KrzysFR .
Indeed, your notes are spot on. All these changes are happening, and @terrelln's answers are correct.

Some complementary information : 
- we need `targetLength == 0` to specify "normal mode" when using strategy `ZSTD_fast`. Any value `> 0` now means "switch to ultra-fast mode". This behavior is specific to `ZSTD_fast` strategy. Since `targetLength` is an `unsigned` type, it's necessarily `>= 0`, so there is no more need for `ZSTD_TARGETLENGTH_MIN`, since it would create a tautological test. A related question is that `ZSTD_TARGETLENGTH_MIN` might actually be useful, if only for documentation purpose ?

- we need `targetLength == SOME_HUGE_NUMBER` to make `ZSTD_fast` produce guaranteed uncompressed blocks (but still using `zstd` format encapsulation). There is currently no upper bound defined, but that may be necessary to avoid strange corner cases, so `ZSTD_TARGETLENGTH_MAX` _may_ re-appear.

- `ZBUFF_*`  API is deprecated. It's highly recommended to switch to the official streaming API (`ZSTD_compressStream()`). We are considering removing the deprecated API from default build in the future.

- As mentioned by @terrelln , all error codes had to be changed, in order to become stable. They are now pinned to specific values. There is a small probability that some new error codes may appear in the future (though not many of them), but existing ones have their values guaranteed. `zstd_errors.h` is expected to be labelled "stable" in the future.

- The values of `enum ZSTD_strategy` had to be changed to make room for value `0`, which now [means "keep default value" (relative to selected compression level)](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L1002). `enum ZSTD_strategy` is still part of experimental API. It is expected to become stable in the future. When that happens, all `enum` members will be pinned down to specific integer values.

**Comment by Cyan4973** [comment]
For information : `ZSTD_TARGETLENGTH_MIN` and `ZSTD_TARGETLENGTH_MAX` macro constants have been restored, they will be part of next release.
