### ISSUE TITLE
decompressDCtx and decompress_usingDict ignore dctx->format

### ISSUE THREAD

**Issue by benrg** [facebook/zstd#1224]
(v1.3.5)

`ZSTD_decompressDCtx` and `ZSTD_decompress_usingDict` behave as though the format is `ZSTD_f_zstd1` even if you set it to `ZSTD_f_zstd1_magicless` before the call. I think they should either support both formats or error out if the format is wrong. (The same may be true on the compression side – I didn't check.)

**Comment by Cyan4973** [comment]
Unfortunately, only `ZSTD_decompress_generic()` is able to decompress `ZSTD_f_zstd1_magicless` format, since setting the format is a capability only available from the advanced interface (it's effectively "invisible" when using a different entry point).

`ZSTD_decompress_generic()` is a strict superset of existing interfaces. It is designed to be able to achieve same performance and functionality as `ZSTD_decompressDCtx` and `ZSTD_decompress_usingDict`, and more.
