### ISSUE TITLE
Make zstd record decompressedSize when output is to file, even if input is not

### ISSUE THREAD

**Issue by waterhouse** [facebook/zstd#1251]
Consider this use case:
```
zcat giantfile.gz | some-processing-pipe | zstd -13 -o out.zst
```
(by the way, I know zstdcat is faster than zcat at decompressing .gz files, which is an amazing feature)

When doing this, out.zst will be missing the correct decompressedSize value, and "zstd --list out.zst" will have blank spaces in the "Uncompressed" and "Ratio" columns.  I think this is suboptimal behavior.

At the start of the stream, obviously you won't know the size of the entire input.  But when you've reached the end of the stream, you do have that information.  Then, if the output is to a pipe, then it's too late to change the header—you've probably written it out long ago.  But if the output is to a file, it should be easy to find where you wrote the header and insert the correct decompressedSize value.

**Comment by Cyan4973** [comment]
Hi @waterhouse 

This feature is unplanned for the time being.

You are correct the method you propose is in theory "possible",
however, it would violate the current software design,
making it not only difficult to achieve, 
but more importantly, if badly designed, even harder to maintain.

Right now, the module in charge of file writing / reading is an overlay on top of `libzstd`.
It's not supposed to modify the compressed content provided by `libzstd`.
It's not even supposed to just understand its format !

On the other hand `libzstd`, which can create and understand frame headers,
has no sense of "files", it only understands "buffers".
Once some output is flushed out onto some destination buffer, it's considered "irrecoverably lost",  it cannot be accessed anymore.

Also, `libzstd` supervises content size, it ensures that what it creates corresponds to the contract. Creating a "fake" header with a wrong content size (to be modified later on), would currently trigger an error during compression, when it detects that real and declared sizes do not correspond.

So, while the library could "in theory" be modified to allow updating the frame header after its creation, in practice though, it violates a few assumptions in current software design, and just carelessly creating an exception for it would be dangerous for library's stability.
Therefore, a first step would be to find a correct way to "blend" such a new capability into current software architecture. On first look though, it feels uneasy, likely a (too?) large work and risk for the value of intended feature.

**Comment by waterhouse** [comment]
Ah, darn.  I see, that makes sense.

I'm considering a separate program that took a completed .zst file and filled out the header.  That would cover the functionality of this use case, as well as where someone had lots of existing files.  However, it looks like the file is variable length based on whether the size is recorded, so that would entail rewriting the entire file, which would either require a bunch of extra space or risk corrupting the file if the process died partway through.  Leaving space up front would either make the common case worse or require forethought.

The sanest solution seems to be having a bit in the header that says "look at the end of the file for a structure that describes the decompressed size".  You probably couldn't encode the offset of that structure in the header; could potentially be many bits.  You might be able to encode the size of the structure, or just make it constant.  Then there's the zstd feature where you can concatenate files and have them work.  If you appended a "naive" .zst onto a .zst that had "yes, tail structure exists" set, then it'd try to parse whatever bytes happened to be at the end, which would be bad; and having an efficient, guaranteed way to distinguish the tail structure from the regular end-of-file would probably mean a format change and sacrificing more bits.

Yeah, there's probably no very good way to do this.  Ah well.  Thanks for looking at it.

**Comment by Cyan4973** [comment]
The only method I can think of is to reserve space at the beginning, to be modified later on.

This is theoretically possible : one could typically define the "frame content field size" to be an unconditional 8-bytes, so that it can represent any value. This is obviously wasteful for small files, which may need only 1, 2 or 4 bytes. But it could also be negligible for many use cases, making it an acceptable trade off.

The issue currently is that there is no way to "reserve" such space, because the value in the header must be correct, and the library control this fact when creating the frame. Hence it would error out during compression.

To make this possible, a new capability should be created.

But then, the resulting frame would still be "invalid" [according to the format specification](https://datatracker.ietf.org/doc/draft-kucherawy-dispatch-zstd/?include_text=1). So the header would need to be fixed to be decodable. Indeed, another application could do it, but still, it feels uneasy to create something "invalid" and depend on some later application to fix it.

It's a pity we did not think such possibility when creating the format, as we could have defined a kind of "placeholder" value, that would have no effect (equivalent to "no frame content size defined") but keep the resulting frame valid. `0` used to have this role, but it was later changed to actually mean "empty frame", as it was a real-world use case.
