### ISSUE TITLE
Question about frames and dictionary

### ISSUE THREAD

**Issue by LastImmort** [facebook/zstd#1288]
Hello, I trying to use https://github.com/skbkontur/ZstdNet port for .net, so only way to compress\decompress here it is byte arrays and it work good, but i need to write compress chunk to file(no problems here) and then read from file little chunk.

 At this step i meet some trouble, when decompressing i have 10 mb buffer for example, but 1 fully compressed chuck is ~6mb, so another 4 mb it is another compressed chunk and for success decode i need to path src with size ~ 6mb or read and decompress full file at once or getting error 'src size not correct'.

 Is there way to get first chunk size(~6mb) to provide correct range of src bytes if i have only encoded file or it is not possible to do with byte array api?

And one more question when i need to use dictionary and how i need to prepare it(what amount of samples best, best sample length and etc)? Do i need to use dict for files <2-5 kb max or it can help to compress files more then 5 kb? Cause sometimes it is just make archivation slower.

**Comment by felixhandte** [comment]
Hey @LastImmort, happy to help out.

The core C Zstd library here has support for figuring out when a frame has ended in the streaming API. However, it looks like the binding you are using doesn't support the streaming API. So that would be an issue with that library and you should take it up with them.

As for dictionary best practices: Dictionaries can be used for inputs of any size (though they get less useful as your input gets larger). I find that ~10MB of samples is about the right size to provide to the trainer. I'm surprised you find dictionaries produce worse results in some situations. Can you describe  in more detail the situation where you find that to be the case?

**Comment by LastImmort** [comment]
Hi @felixhandte, thank you for answer i will try to check this samples size in few days.

 I attached [link to minimal c# core project with samples](https://drive.google.com/open?id=1J6nMlbAJ27ul8LxaylsyQaskVjtyCSns) of mesh files and two files of different size, with small mesh, output practically same, but with larger mesh ~40 mb, output with nearly 100 kb more.With meshes compress time in both cases seems like same. It is data which i can safely share.
 
 But more interesting things going on when i compressing 169 mb .fbx file which i can not share :(
In few words it seems like if i use dictionary from another fbx files from 2-40 mb, compress time increased from ~500-650 ms on my pc to ~1k ms, and output generated ~104mb but without dictionary ~99mb. Maybe be with 3d data more difficult to get right samples.

So it feels like dictionary can reduce performance on big files and some loss of ratio which increased when file size increased and buffer used ~100mb

Another one case which little surprise me(not about training dictionary) is compression level and buffer size,  on 22 level if we path buffer which equals to file size of fbx (169mb) output become ~47 mb, but with bufffer of 10mb output  changes to ~94mb

**Comment by Cyan4973** [comment]
Hi @LastImmort 

It's true that, when compressing large files with a dictionary, it can result in worse compression ratio.
The causes are unrelated to the format, rather, it's a weakness of current library, which "bets" that, by default, future files to compress with a dictionary will be small. When the bet is incorrect, it results in sub-optimal compression ratios.

You could override this, and explicitly define compression parameters (rather than letting the system trying to guess them automatically), by using the [advanced compression parameters](https://github.com/facebook/zstd/blob/dev/programs/zstd.1.md#advanced-compression-options). But that's a fairly complex process.

Rather, I would recommend that you opt out from using dictionaries whenever the file to compress seems "large enough", which I would loosely define as > 100 KB, though your mileage will vary depend on file type, and you might prefer some different threshold.
