### ISSUE TITLE
[QUESTION] ZSTD_compressStream() returns dstSize_tooSmall

### ISSUE THREAD

**Issue by xndai** [facebook/zstd#1320]
Hi all, 

When will ZSTD_compressStream() returns dstSize_tooSmall? Is there any requirement on the minimum length of output buffer? There is a function ZSTD_CStreamOutSize() to get recommended output size, is that the minimum length required?

I am having an intermittent dstSize_tooSmall error in our setup. The output buffer size varies each time we call  ZSTD_compressStream() due to our implementation. I am trying to understand what could be the issue.

Thanks!

**Comment by Cyan4973** [comment]
Hi @xndai ,

if I understand your question correctly, this should not happen.
`ZSTD_compressStream()` is supposed to size its internal buffers correctly, and will use its internal buffer instead of provided `dst` output buffer whenever it believes there is not enough room in `dst` to complete operation safely.

Which version of `libzstd` are you using ?

If you have a reproducible error case, I would like to analyze it.

**Comment by xndai** [comment]
Thanks @Cyan4973 . We use 1.1.0. Is it a legitimate error under low memory condition? I do see the system was under memory pressure when we got this. I will try to get a repro and will also test on 1.3.

**Comment by Cyan4973** [comment]
In theory, a low memory condition should trigger a different error `ZSTD_error_memory_allocation`.
However, v1.1.0 is fairly old by now, and it could be that it mixes up things when it comes to exact error code. We changed/fixed a lot of little details since.

Best course of action is to find a way to generate the issue in a reproducible way. If it's related to memory pressure, this can be more difficult. You might have to insert a cooked `malloc()` derivative to make it (mis)behave in order to trigger the issue in a reliable manner.

`ZSTD_customMem` might be useful for that. See https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L621.

**Comment by Cyan4973** [comment]
Any update on generating this error code ?

**Comment by xndai** [comment]
Hi @Cyan4973 , sorry for getting back to you late. We still see this repros in our production environment, but we still have a hard time getting consistent repro in our test setup. Good news is we don't see it with 1.3.1 so far, so the hope is that with the new release, the issue will go away.

Given that there are very limited things we can do in the production (ZST_customMem is too risky), I am thinking if there are simpler approaches we can try. For example, the first thing is to get a complete calls stack for this exception so we know where the error originated. Is there any compiling flag or macro that's able to get such information?

**Comment by Cyan4973** [comment]
I'm afraid there is no simple flag to trigger a backtrace.
Especially as it's not a segfault or anything equivalent considered an "error" by the host system : it's just a valid error code, so from the host perspective, everything works correctly.

If you can't catch a reproducible bug condition, then I'm afraid next stages are too complex : one would need to modify the source code, to generate traces, and be able to filter them when error happens. That's a lot of effort, for a version long deprecated.

I would rather put this effort into bringing a more up to date version into your infrastructure.
