### ISSUE TITLE
Rename to zs

### ISSUE THREAD

**Issue by hdante** [facebook/zstd#1333]
Here is a stylistic suggestion to rename the executable and/or at least the extension to zs. No real rationale behind it, just a suggestion.

 $ zs file1
 $ zs -d file1.zs

**Comment by terrelln** [comment]
At this point it is too late to rename the executable, and we aren't going to change the extension without a good reason.

If you want to use this on your system, you can always add this to your bash config.

```bash
alias zs=zstd
```

Currently, if you want to use `.zs` as your extension, you can use `zstd file -o file.zs`, and `zstd -d file.zs -o file`. We might add a `--suffix` flag that allows zstd to recognize/write arbitrary suffixes, and then you could do:

```bash
alias zs=zstd --suffix zs
```

However, I don't recommend this, since it makes your files non-standard.
