### ISSUE TITLE
Extending the option -o to directories?

### ISSUE THREAD

**Issue by svenha** [facebook/zstd#1334]
I have some use cases that require many zstd-decompress invocations: the directory compressed/ contains 20m files. In regular intervals, I have to decompress around 2m files to the directory uncompressed/.
I do this with 2 million invocations of `zstd-decompress -d -o uncompressed/f f.zst`
How about something like:
`xargs -a my-2m-files | zstd-decompress -d -o uncompressed`
Thanks for your time.

**Comment by Cyan4973** [comment]
It's an interesting feature request.
Clearly, we don't have it yet.

It's not trivial to implement either, especially as this proposal conflicts with current definition of `-o`, which defines a destination __file__ name.
Now, to re-use the same command, we would need the behavior to differ, depending on the existence of `-o` target and whether it is a directory or not. This could introduce some confusion. Typically : 

- `zstd -d someFiles*.zst -o someNonexistingName` => decompress everything and append into single destination file `someNonexistingName`
- `zstd -d someFiles*.zst -o someExistingFile` => prompt for overwrite, if yes, decompress everything and append into single destination file `someExistingFile`
- `zstd -d someFiles*.zst -o someExistingDirectory` => Now : error out. Current proposal : decompress each file separately into directory `someExistingDirectory` using their original name

We can already guess some confusion scenario : 
- If a user wants to decompress all files into some target directory, but does provide a non-existing destination name instead, the result will be a single file, featuring all decompressed contents appended.
- Conversely, if a user wants to decompress a single file at some explicit destination, and it happens that this destination exists and is a directory, the order will be silently converted into "decompress into target directory using existing filename", instead of an error as it behaves today.

An opened question is therefore if creating such confusion scenarios is an acceptable cost for the feature.

An alternative would be to use a different command.
Unfortunately, `-d` and `-D`, which could have been handy to mean "directory", are already in use.
But a relative to `-o`, `-O`, is still available, and could be suitable.

**Comment by svenha** [comment]
The danger of confusion is real as you pointed out. Hence, a new option -O is a good idea.

**Comment by Cyan4973** [comment]
This feature request is in our backlog for next release, either `v1.3.9` or `v1.4.0` depending on user feedback.

**Comment by svenha** [comment]
Thanks for including my feature request. I am really curious how it will speed up my use cases sketched above.

**Comment by senhuang42** [comment]
Hey @svenha ! I'm currently working on this - I was wondering if you had any thoughts for how this should behave?

Basically, there are two options: 
1) For each file in args, compress it and store it into the output directory so for the example:
`zstd dir1/file1 dir2/file2 file3 -O targetDir`
we end up with 
`targetDir/file1, targetDir/file2, targetDir/file3`
In this case, if two files have the same name (but are in different folders) then we simply complain that we can't do it.

2) For each file in args, preserve the file tree structure with the current working directory as the starting point, and store it in the output directory, so for the example:
`zstd dir1/file1 dir2/file2 file3 -O targetDir`
we end up with 
`targetDir/dir1/file1, targetDir/dir2/file2, targetDir/file3`
In this case, if any file is a parent/ancestor of the current working directory, then we refuse to include it (since then it complicates the issue of reproducing the file structure).

In both cases, using '-r' would expand any argument that is a directory and treat it as a list of regular files. Both cases seem like reasonable implementations to me, curious if you had any thoughts.

**Comment by svenha** [comment]
Thanks for your work, @senhuang42! I have not thought about 2. before. I think that 1. would follow the principle of least surprise (but I am not sure). For 2., the option name should hence be different, if it is implemented.

**Comment by Cyan4973** [comment]
If we start to consider multiple behaviors, even in the future, we would be better off using `--long` commands, which are more descriptive.

**Comment by senhuang42** [comment]
Makes sense. I think using (--odir, --odirstructured) for the simple and filetree-preserving options, respectively, would be best. Stay tuned :)

**Comment by felixhandte** [comment]
(TW: Bikeshedding)

`mirrored` seems like the right word to describe the behavior of matching the input directory structure. I like `--output-dir-flat` and `--output-dir-mirrored`.

**Comment by Cyan4973** [comment]
`--output-dir-flat` is now available, via @senhuang42's #1812

**Comment by camdenorrb** [comment]
Any updates on the mirrored output?

**Comment by Cyan4973** [comment]
`--output-dir-mirror` is available in `dev` branch
