### ISSUE TITLE
Spec. versioning

### ISSUE THREAD

**Issue by MarkCallow** [facebook/zstd#1349]
I'm planning to reference https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md from another specification. How best to make a bibliographic reference to a specific version? Are appropriate git tags created whenever a new spec. version is created?

There does not appear to be a version number in the frame header. Are you planning that a decompressor of today will be able to decompress any future version of Zstandard, i.e. no breaking changes?

**Comment by Cyan4973** [comment]
> Are you planning that a decompressor of today will be able to decompress any future version of Zstandard, i.e. no breaking changes?

Yes, that's the idea. The initial magic number is the important identifier.

We actually have 2 bits of variance built-in : 
- One for non-breaking change : signaling a feature which can be useful to know by the decoder, but does not prevent the decoder from decompressing data normally.
- One for breaking change : signaling a yet-to-be-defined feature that *must* be interpreted to decode data correctly. We could use it for a `v2` in the future. For the time being, and the foreseeable future, it will remain at value `0`.

All changes since v1.0 are mostly cosmetic changes, or errata. We had a lot of reviews since, so several words have been refined to reduce potential confusion or inaccuracy. But the format has remained the same.

In the near future, the specification will be published as RFC8478. 
You might prefer this reference, since it's more "formal".

**Comment by MarkCallow** [comment]
Thanks for the helpful information.

> All changes since v1.0

The latest document in the dev branch says version 0.3.0. Where is it labelled v1.0?

> In the near future, the specification will be published as RFC8478.
> You might prefer this reference, since it's more "formal".

Yes. I'll reference the RFC. Will it be published before the end of the year?

**Comment by Cyan4973** [comment]
> All changes since v1.0

I meant since [`zstd v1.0`](https://github.com/facebook/zstd/releases/tag/v1.0.0). The versioning of the format document is different, since it doesn't update at same pace.

From a `zstd_compression_format.md` perspective, the "baseline" version can be considered v0.2.0.
All changes since this version are either cosmetic, or erratum, but describe the same format.

> I'll reference the RFC. Will it be published before the end of the year?

Yes

**Comment by Cyan4973** [comment]
Zstandard is now published as [__RFC8478__]( https://tools.ietf.org/search/rfc8478 ) .
