### ISSUE TITLE
Accessing Context Dictionary

### ISSUE THREAD

**Issue by SteveBooth-1** [facebook/zstd#1377]
I have an application that needs to compress large blocks of memory-resident data (~1GB) in chunks of 1-10MB and save them to an output file. I'm new to Zstandard (fantastic tool, btw), and it looks like the right way to proceed is to use Compression Contexts (the app is multi-threaded) because there is, by definition, no pre-train phase for the blocks and no way to pre-create a dictionary.  It would be fairly useless as well because there is little consistency block-to-block.  However, once I process all the chunks, I'm thinking it would be super useful and efficient to write out the encoded dictionaries from the Contexts so they can then be read and used when decompressing.  My question is, there doesn't seem to be any way in the standard zstd.h header to do this.  How can I access and write out the dictionary from a Compression Context?  Or am I approaching this problem all wrong?

**Comment by Cyan4973** [comment]
Your application probably does not need a "dictionary" (at least, not what _we_ call a dictionary, which is essentially useful when compressing _small_ data).

The main question that seems to matter is : 
do you want each chunk to be independent ? so that it can be extracted independently ?
or do you value more final compression ratio ?

For the first case, `ZSTD_compress()` is enough. You may prefer `ZSTD_compressCCtx()` as a small optimization, because it will be easier on `malloc()` operations, but at the cost of maintaining one context per thread.

For the second case, you need streaming capability, provided by `ZSTD_compressStream()`. This one takes advantage of block contiguity to compress even further, which is more important at higher compression levels.

Does it answer your question ?

**Comment by SteveBooth-1** [comment]
First, thanks so much for getting back so quickly.  It's appreciated.

To answer your first question, each chunk is by definition, independent because each is created by (n) parallel threads.  Although obviously, I'd like to maximize the compression ratio.  I was hoping to use the dictionaries as a way to maximize that, but more importantly to improve the decompression speed on the back-end by saving it/them, and then loading it before decompression.  

Will it not be true, if I use the same contexts for data coming from the same thread, that there will be chunk-to-chunk efficiencies?

Unfortunately, due to the parallel-thread nature of the source data, I'm thinking that streaming probably isn't an option here...?

**Comment by Cyan4973** [comment]
Yep, to keep processing in parallel, better compress each chunk independently.

While a dictionary could in theory help compression ratio, it's unlikely to provide tangible benefits in this case, because chunks are relatively large. It's too much difficulties for too little gains.
Better keep it simple.
