### ISSUE TITLE
zstd v1.3.6: decodecorpus generates excess byte for zero-sequence compressed block

### ISSUE THREAD

**Issue by ulikunitz** [facebook/zstd#1379]
I have implemented a zstd decoder in the Go language. I have used the decodecorpus tool to generate test files for the decoder. The test files have been very useful because I could find two bugs in my implementation.

However I had to implement also one workaround for an excess byte generated by decodecorpus  for compressed blocks with a zero sequence count. IMHO the excess byte doesn't conform to the Zstandard format specification.

Here is the actual example of such a block in hex:
```
25 00 00 b1 7a 00 95
```

The block header `25 00 00` translates into a last block, that is compressed and has a block size of 4 bytes.

It is followed by the literals section `b1 7a`, which translates into the RLE-encoded sequence of 22 bytes `7a`. There is no issue here.

But the sequence header `00` translates into no sequences. The Zstandard Compression Format specification states for the case, that the sequence section stops here. But actually it doesn't because the block size is 4 bytes. It appears that zstd v1.3.6 ignores the excess byte and decompresses the file correctly. My implementation does now the same. In all cases that I found, there was only one excess byte.

My suggestion is to extend the Zstandard Compression Format Specification to allow for the excess byte, since the decodecorpus tool generates such files and the zstd program can decompress them without any error. From my understanding of the zstd code, zero-sequence blocks without the excess byte are also supported by the program.

**Comment by Cyan4973** [comment]
Thanks for pointing that corner case to our attention @ulikunitz .
This is a nice investigation.

I believe it's now preferable to consider the official format documentation as the "source of truth".

Regarding the sequence section header, the RFC states : 
https://tools.ietf.org/html/rfc8478#section-3.1.1.3.2.1
> if (byte0 == 0): there are no sequences.  The sequence section stops here.

So I think it's pretty clear : sequence section ends immediately after the `0`.

Now, one could consider that excess bytes are not part of the section, but may still be part of the block.

Of course, a first issue is, nowhere in the spec is described anything between the end of the sequence section and the end of the block.
But there is more : the size of the sequence section is directly derived from the size of the block (described in [this paragraph](https://tools.ietf.org/html/rfc8478#section-3.1.1.3.2)), hence end of block and end of sequence section are one and the same thing.

Hence the block itself should stop right after the `0`.
As a consequence, `decodecorpus` output is incorrect. \
The tool should be updated to better respect the specification.

Regarding the reference decoder, this is a case of "undetected format error". Excess bytes in the block are just skipped. It's not a big issue, since it doesn't impact normal operation (valid blocks) and doesn't degenerate into something exploitable. But better be more strict on this spec detail. It also explains why this `decodecorpus` bug has not been detected until now.

**Comment by ulikunitz** [comment]
Happy to see that we are agreeing on the interpretation of the specification.

My source for the implementation was the specification. From that perspective I can support following the specification for this case. What I don't know is, whether there are any zst files with real data out there that contain such blocks. If that would be the case, the format specification would need to be extended and these blocks still to be accepted.

On the other hand I have raised all issues that I found in the specification while implementing the decoder. I appreciate how fast those issues have been resolved. So it is possible to write a decoder based on the specification, but there is one place, where I would wish the specification would be more explicit, but it isn't wrong in that case. Would it be of interest?

**Comment by Cyan4973** [comment]
I believe there is no valid frame out there generated with extraneous byte.
The reference encoder [stops right after the `0` byte](https://github.com/facebook/zstd/blob/dev/lib/compress/zstd_compress.c#L2240).

By all means, if you have any other questions or clarification requests regarding the specification, let's review them. I'm happy to improve the specification document for 3rd party implementers.
