### ISSUE TITLE
Compiling with -fPIC in Linux (Centos 6)

### ISSUE THREAD

**Issue by SteveBooth-1** [facebook/zstd#1387]
I need to use Zstd in a Linux .so file I'm developing, but it would appear that the base cmake file doesn't provide a way to add '-fPIC' to the compile-time options.  Before I go hack the deployed cmake files, I thought I would ask if there is an official way to make zstd using -fPIC?

**Comment by Cyan4973** [comment]
I'm not too familiar with the `cmake` script, since I prefer using the `Makefile` one directly,
but I note that it has the following option for shared libraries : 

https://github.com/facebook/zstd/blob/dev/build/cmake/lib/CMakeLists.txt#L14

As far as I can tell, a shared library should always be compiled with `-fPIC`.
If that's not the case, maybe there's something to fix in the `cmake` build script.

**Comment by SteveBooth-1** [comment]
It's actually the static library build that I'm using, not the shared, since I'm statically linking to the '.a' file, which it does seem to create properly.  It does not appear to compile with -fPIC, since that is the error I'm getting when I compile.  I will look further at the cmake file, although I confess I haven't done a lot of that in the past.

**Comment by Cyan4973** [comment]
ah ok, then it's different.
A static library should not be compiled with `-fPIC` _by default_, since some builds will actually require this capability to be disabled,
but it should certainly be possible to build the static library with this flag on demand.

While I can't comment on how to do that with `cmake`, I can propose a solution using `Makefile`.
```bash
CFLAGS="-O3 -fPIC" make -C lib libzstd.a
```

This will create `libzstd.a` within `/lib` with `-fPIC` enabled.

**Comment by SteveBooth-1** [comment]
It's actually the static library build that I'm using, not the shared, since I'm statically linking to the '.a' file, which it does seem to create properly.  It does not appear to compile with -fPIC, since that is the error I'm getting when I compile.  I will look further at the cmake file, although I confess I haven't done a lot of that in the past.

**Comment by SteveBooth-1** [comment]
Okay, I'm still trying to get this to work.  Not sure exactly how to use your solution.  It's not a valid shell command, but if I stick a semi-colon in there, i.e.: 'CFLAGS="-O3 -fPIC" ; make -C lib libzstd.a', I get 'No rule to make target 'libzstd.a'.  Did you mean 'CFLAGS="-O3 -fPIC" make -C lib libzstd_static''?

And, doing a 'CFLAGS="-O3 -fPIC" ; make VERBOSE=1 -C lib libzstd_static' clearly shows that the '-fPIC' is not being inserted into the cc commands.  I also tried inserting a 'MOREFLAGS="-fPIC' into the /lib/Makefile, but this didn't work either.  Trying to figure out which Makefile and which variable needs to be updated to stick PIC at the end of the compile commands...

**Comment by Cyan4973** [comment]
The example command should be run from the root directory of the repository.

Alternatively, if you prefer, you can also change directory into `/lib` and run : 
`CFLAGS="-O3 -fPIC" make libzstd.a`

If your shell doesn't accept setting environment variables on command line, which is pretty strange (Windows maybe ?), you may take full ownership of the variable from the `Makefile`, by setting the variable _after_ `make`. In order to keep all internal variables as designed by the `Makefile`, you may use the non-standard build macro `MOREFLAGS`, which limits the impact of this strategy to just adding a few flags (instead of replacing them all).

With the assumption of running from `/lib`, it works this way : 
`make libzstd.a MOREFLAGS=-fPIC`

**Comment by SteveBooth-1** [comment]
Okay, I figured it out.  The normal, 'official' way of making zstd on a Linux platoform, according to the docs, is to go to /build/cmake, execute a 'cmake .', then just do a 'make'.  That creates a Makefile in /build/cmake, and then creates the 'libstd.a' library archive file in /build/cmake/lb.  If you use the following, slightly modified version of Yann's suggested command, with the semi-colon inserted:

      `CFLAGS="-O3 -fPIC" ; make libzstd.a`

AND it is executed in the /lib directory, with the Makefile there, it will properly create a version of libstd.a _in the /lib directory'_, with 'fPIC set.

**Comment by Cyan4973** [comment]
I would really recommend against inserting a `;` semi-colon between the `CFLAGS` variable setting and the `make` command.

In a _normal_ shell environment, this wouldn't work : 
The `CFLAGS` variable is set, but its lifetime ends at `;`, so the command `make` is run with the default `CFLAGS` environment variable (if it exists), not the one previously set.

@SteveBooth-1's shell seems pretty strange, and doesn't react according to expectation based on his feedback, so maybe _for him_ this trick works. But be aware that I've never seen that working anywhere, and cannot reproduce it on any system, not even on a CentOS6 VM one.

**Comment by SteveBooth-1** [comment]
Confirmed.  My initial experience regarding the semi-colon was caused by being in the wrong directory.  The original command is correct when executed from the root directory, which is critical.
