### ISSUE TITLE
Out-of-bounds access in HUF_compress_internal()

### ISSUE THREAD

**Issue by vnair81** [facebook/zstd#1393]
In `HUF_compress_internal()`, variable `table` is a pointer to `HUF_compress_tables_t` in which member `count` is a member defined as:
`U32 count[HUF_SYMBOLVALUE_MAX + 1];`
having storage of 1 KB.

`HUF_compress_internal()` calls `HIST_count_wksp()` passing `table->count` as the workspace argument.

`HIST_count_wksp()` calls `HIST_count_parallel_wksp()` which `memset()` 4KB of memory starting at `workspace`  causing out of bounds access:
`memset(workSpace, 0, 4*256*sizeof(unsigned));`

![See this graphically.](https://user-images.githubusercontent.com/44025701/47549109-ab3acc80-d918-11e8-89c1-c7744ffd5740.png)

**Comment by Cyan4973** [comment]
This is a false positive. We would have serious problems since a long time ago if we were providing a 1 KB buffer to a function initializing 4 KB.

The trick is, `table` is just a pointer into `workSpace`.
So when `table`  is passed as `workSpace` in `HIST_count_wksp()`, it actually refers to the original `workSpace`, which is large enough for the 4 KB initialization.

This is bad programming style though : the last argument of `HIST_count_wksp()` should have been `workspace` (since it's available), instead of `table`, even if they actually point at exactly the same address. This would properly express the intention. It might even help the static analyzer in this case (which one are you using ?).

So, even if it's not a "bug", this function might be worth some code refactoring, to improve clarity.

**Comment by vnair81** [comment]
Thanks Yann.

We're using Coverity Static Analysis.

**Comment by Cyan4973** [comment]
New version merged in `dev` branch.
While it's not exactly a "fix", since there was no error, the new version might nonetheless make it simpler for the static analyzer to understand what's going on.
