### ISSUE TITLE
Out-of-bounds read in ZSTD_insertBtAndGetAllMatches()

### ISSUE THREAD

**Issue by vnair81** [facebook/zstd#1397]
See below:
![outofboundsreadinzstd_insertbtandgetallmatches](https://user-images.githubusercontent.com/44025701/47631592-a706ed00-db6c-11e8-8af2-dffa78076826.png)

**Comment by terrelln** [comment]
I don't believe that this is possible. `ll0` must be either `0` or `1`, since it is a boolean parameter. Then before we access `rep`, we check `repCode == ZSTD_REP_CODE`, which can only happen when `ll0 == 1`, and is also the maximum possible value for `repCode`.

We could assert that `ll0 <= 1` at the top of the function.

**Comment by Cyan4973** [comment]
I agree with @terrelln , `ll0` is necessarily `<= 1`, 
but that's a guarantee that the static analyzer seems unable to determine.

We could add an `assert()`, 
which seems like a good idea because it can act as an "active comment" 
hence is better for code clarity.
However, I'm unsure if this will be a good enough signal for the static analyzer.
It might simply elude it since `assert()` are disabled in release mode.

I would like to be able to reproduce this warning to see if the `assert()` can solve it.

**Comment by vnair81** [comment]
If` ll0` is meant to be `<=1`, we can convert its type to `bool`. In this case we won't need an assert.

Or perhaps we can add the assert and convert `repCode == ZSTD_REP_CODE` to `repCode >= ZSTD_REP_CODE`.

**Comment by vnair81** [comment]
If we don't want to change `ll0`'s type, we can also change:
`U32 const lastR = ZSTD_REP_NUM + ll0;`
to
`U32 const lastR = ZSTD_REP_NUM + (ll0 ? 1 : 0);`
making the intent (of an integer being treated as a binary) very clear.

**Comment by Cyan4973** [comment]
> U32 const lastR = ZSTD_REP_NUM + (ll0 ? 1 : 0);

I tried this suggested variant. Unfortunately, the generated code is not binary identical, so it impacts the assembler generated.

I then measured a very small speed hit (~1%). Note that this is within error margin, so it might have been noise.

Anyway, if the intention is to ensure that `ll0` is understood as a `0`/`1` value, I believe that an `assert()` and a comment are enough.

**Comment by Cyan4973** [comment]
One issue is that we try to keep the code mostly compatible with C90 (+ a few reasonable extensions, such as variadic macros, or `long long` type) for broader compatibility.

**Comment by cemeyer** [comment]
One possible C90 compromise might be something like:

```
#if __STDC_VERSION__ < 199901L && !defined(bool)
#define bool U32
#endif
```

**Comment by Cyan4973** [comment]
Right, we could define our own `bool` type,
I suspect I would rather lean towards using `enum` in this case,

but it feels overblown if the objective is just to solve this issue #1397.
Introducing a new type must be considered at code base level.

I feel no urge to push for the introduction of `bool` type within `zstd` currently,
though I note the suggestion, as it could happen in the future.

**Comment by cemeyer** [comment]
That is very reasonable, and I agree with the conclusion — this issue does not justify a change of that magnitude.  I just happen to like C99+ and `bool` personally, so I try to advocate for it a little bit ;-).  No worries.
