### ISSUE TITLE
Is there some plan to support ZSTD_compressBlock_destSize as LZ4?

### ISSUE THREAD

**Issue by hsiangkao** [facebook/zstd#1399]
Hi,
Sorry to bother in the ZSTD community again, I am considering to add another high CR algorithm but with reasonable decompression speed for the future Linux EROFS file system --- Not very soon (because we are currently focusing on LZ4 for our products :) ), but I am curious about the question I request in the title...

Almost the current file system is small block-based due to their physical media constrain, which means it could be better to compress data as much as possible until a centain aligned output size (like into 4kb in the current EROFS, or other constrains later for larger cluster size...),  A compressBlock_destSize interface is very helpful to such cases to fill to the block-aligned boundary...

It is a really low-priority feature...I just want to raise in order to get some future plan hints, thanks :)

Thanks,
Gao Xiang

**Comment by Cyan4973** [comment]
Hi @hsiangkao 

This feature is hard to implement.
LZ4 has a fixed encoding scheme, which makes it possible to calculate, at all time, what's the current output position, and what will it be after next encoding decision.

In contrast, Zstandard has a second pass, called entropy, which optimizes the encoding scheme itself. Because of that, it's not possible (by default) to control the "current" position, since it's not yet known as long as all statistic are not gathered.

Now, this could be "approximated", by taking some bets on probable size, and then adjust accordingly.
A multi-pass solution could be created with current API, based on this simple concept (adjust - retry).
This would be wasteful on the encoding side though.

A more efficient method would require working on intermediate data, after match find and statistics gathering, but before encoding. There, it would be possible to essentially proceed the same way (adjust -retry) but by working directly on the statistics, and evaluating the output size, which is a lot more cpu friendly than re-encoding everything at each attempt.

Still, it is inherently more complex and less accurate than LZ4.
Hence, save a high value target use case, this feature is currently not in our short term roadmap.

**Comment by hsiangkao** [comment]
Hi Yann,
  Thanks for your quickly reply. :)
  Yes, LZ4 is simple enough and it is also enough to use Dynamic Programming to get the optimal output data for LZ4_compress_destsize.
  But I know little about the current ZSTD... If it is hard to implement, I think by using binary search (to get the result, could be a work-around.... But I am not sure it is roughly monotonous...). I will look into ZSTD later.
  At last, thanks for your reply again. I need to go into your reply to learn more :) 

Thanks,
Gao Xiang

**Comment by Cyan4973** [comment]
Merging this topic with #204, which seems roughly similar
