### ISSUE TITLE
Uninitialized variable being used in ZSTD_compressBlock_opt_generic().

### ISSUE THREAD

**Issue by vnair81** [facebook/zstd#1400]
Line 799. Declaring variable `lastSequence` without initializing its members (in particular `price`)
![1](https://user-images.githubusercontent.com/44025701/47711184-9b91ef80-dc5a-11e8-855f-a30e4bb006cd.png)
Line 837. Jumping to label `_shortestPath`
![2](https://user-images.githubusercontent.com/44025701/47711277-ddbb3100-dc5a-11e8-8964-4a2b203e7821.png)
Line 983. Assigning `lastSequence` to `opt[storeEnd]`, with `price` member still uninitialized.
![3](https://user-images.githubusercontent.com/44025701/47711361-11965680-dc5b-11e8-99c0-f655e5c7d573.png)

**Comment by terrelln** [comment]
Once we reach the label `_shortestPath`, the price is no longer needed, since it is only used during the computation of the shortest path. After we loop, the contents of `opt` are forgotten and overwritten.

We could zero out `price` to satisfy the static analyzer.

@Cyan4973 we should decide if we want to support this static analyzer in the long term. We can fix all the issues, but we will inevitably introduce more over time. If we want to silence all the warnings, we should also add it to our CI.

Looking at the [Coverity FAQ](https://scan.coverity.com/faq#frequency), we'd have to run it in a nightly build, not on every commit.

**Comment by Cyan4973** [comment]
Unfortunately, we are not allowed to use `coverity`, so it's not part of our CI.

I agree that we cannot pledge to support false positives for every static analyzer out there. They lean towards false positive due to their very nature, and 2 different versions of the same analyzer can even flag different false positives.

I rather take such input as "hints" that maybe the code could be made clearer, for the benefit of reviewers and future contributors. 
If yes, I follow up with a change that helps both code clarity and the static analyzer.
But if not, we won't change the code _only_ to satisfy a tool, especially one we don't use.

Regarding the diagnosis of this warning, I concur with @terrelln statement : `lastSequence.price` is not needed, hence it doesn't matter that it's not initialized. 

We _could_ initialize it just to please the static analyzer, but that'd not a good reason enough. It doesn't help code readability, and even impair other tools capability, namely memory sanitizer and `valgrind`, that we use to find problems related to un-initialized variables (and a "blind zero" just push the problem to a higher level, where we don't have automatic detection tools, so it's actually worse).

**Comment by vnair81** [comment]
> Unfortunately, we are not allowed to use `coverity`, so it's not part of our CI.
Is is because of some license limitation or because of the limits on the numbers of builds they allow to be scanned? We've found this tool rather useful in our development.
I agree we should make changes only to either fix actual bugs or to make the code more readable/maintainable.
Thanks for taking the time out to review the reports. I have a few other simple changes to propose via pull requests but am waiting for my CCLA approval.
