### ISSUE TITLE
internal header name collision

### ISSUE THREAD

**Issue by gvollant** [facebook/zstd#1406]
Hello,
I made a library which uses zstd, and included in a cocoapods package (for using on iOS application).

Unfortunatelly, another cocoapods component have a cpu.h and a mem.h

My solution is just manualy rename cpu.h and mem.h as zstd_cpu.h and zstd_mem.h (and modify include).

If you do this renaming in source, this will be more easy for me, but of course, I understand if you don't

**Comment by Cyan4973** [comment]
These files do not have currently a `zstd_` prefix because they don't depend on it.
`mem.h`, especially, is created to be generic enough for any usage outside of Zstandard.
`cpu.h` is marginally tied to `zstd` in the sense that some symbol names use `ZSTD_` prefix, but apart from that, it's a completely independent piece of code, that could be made totally generic.

Both these files are supposed to remain internal, and are not exposed on public interfaces.
I understand filename collision can nonetheless be a pain for larger projects.

A potential solution to this problem could be to generate a static zstd library (like `libzstd.a` on linux) independently, and then link the main program to it. This way, no internal `.h` get merged into the main source tree.

**Comment by bimbashrestha** [comment]
@Cyan4973 has provided a workaround for the core issue here and explained why the mentioned files don't have a zstd_ prefix. I'm closing this issue.
