### ISSUE TITLE
travis: Improve build time

### ISSUE THREAD

**Issue by lzutao** [facebook/zstd#1453]
I don't know any advantage to run ASan and UBSan on both gcc-6 and gcc-7.
A disadvantage I think is that the total build time is longer, but our 
target on CI is to reduce that.
If we just want to test build success on one gcc version, I think we do 
not need ASan on it.

Btw, why clang-3.8? If we need a higher version of clang, Travis Xenial 
ships with [Clang 7][travis_clang].

According to [Travis docs][travis_deprecated], it is recommended to 
switch to Travis current Xenial Linux infrastructure.

[travis_clang]: https://docs.travis-ci.com/user/languages/c/#clang
[travis_deprecated]: https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments

**Comment by lzutao** [comment]
Should we keep those `apt-install` target in Makefile? 
That target is just usable on Debian-based distro.
And I think we only use it on Travis. So can we move 
these dependency installation part to `.travis.yml`?

**Comment by Cyan4973** [comment]
I'm fine with moving dependency installation into `.travis.yml`, 
I think it will prove better in term of readability and maintenance.

However, the `apt-install` targets in `Makefile` can be useful beyond Travis, on any Debian-based distro, since they take care of the list of dependencies required to run certain tests (cross-compiling typically). This can be handy for local tests.

**Comment by terrelln** [comment]
* We have CircleCI which gives faster signal on compilation with different flags
* We've improved travis build time over the last year to ~30 minutes
