### ISSUE TITLE
 Out-of-bounds access in ZSTD_encodeSequences_body()

### ISSUE THREAD

**Issue by vnair81** [facebook/zstd#1468]
In function `ZSTD_encodeSequences_body()`, two calls to `BIT_addBits()` which have `ofBits - extraBits` as the last argument, are being flagged as out-of-bounds access.

First call site:
![image](https://user-images.githubusercontent.com/44025701/50329994-83827200-051f-11e9-818e-3f2c4e43a0fd.png)

Second call site:
![image](https://user-images.githubusercontent.com/44025701/50330131-22a76980-0520-11e9-8b83-8a3772f3bcfc.png)

 Out-of-bounds access:
![image](https://user-images.githubusercontent.com/44025701/50330145-2e932b80-0520-11e9-9807-fd323eb1075c.png)

**Comment by Cyan4973** [comment]
In the `BIT_addBits()` function, we have an `assert()`, which guarantees that `nbBits < 32`.
The `assert()` is enabled in all our tests, and is never triggered, which implies that it holds true.

I'll have to look again at `ZSTD_encodeSequences_body()` to understand why the analyzer does not understand this condition holds true. I suspect it mixes up constants of 32 vs 64 bit modes. I'll see if it's possible to make the association more obvious (though, as we don't use coverity and none of our static analyzers flag this scenario, this will be a blind fix).

**Comment by Cyan4973** [comment]
Confirmed,
since `nbBits == ofBits - extraBits`, and `ofBits = ofCode`,
it cannot be "any value", it's necessarily `<= windowLog`,
which is itself bounded by `WINDOWLOG_MAX`, which is `<= 31`.

Hence `ofBits - extraBits <= ofBits <= 31`.

So it cannot be `== 55` as stated by the analyzer.

Not sure how to make that condition clear to the analyzer.
I could add an `assert()`, but it seems the analyzer does not consider them, otherwise it should have detected the `assert(nbBits < 32)` condition right before the place where it flags that `nbBits==55`, which is obviously not possible if the `assert()` is enabled.
