### ISSUE TITLE
CLR support

### ISSUE THREAD

**Issue by Alex1992rus** [facebook/zstd#1513]
Is it possible to compile VS project with /clr option?

**Comment by terrelln** [comment]
I don't know the Microsoft ecosystem. I googled it, but I don't clearly understand what `/clr` does. Could you explain to me what it is, and why you need the VS project to be compiled with it?

**Comment by terrelln** [comment]
I see, Managed C++ is compiled to something sort of like bytecode that can be a bit more portable. We won't add this to our project, since the VS project is used for our CI.

However, you can clone/fork the repo, or just copy `lib/` into your own project, and compile with that option. I would offer to help more, but I know next to nothing about this topic.
