### ISSUE TITLE
How to use streaming compression with multi-thread?

### ISSUE THREAD

**Issue by bennyyip** [facebook/zstd#1584]
I am trying to add multi-thread to [examples/streaming_compression.c](https://github.com/facebook/zstd/blob/470344d33e1d52a2ada75d278466da8d4ee2faf6/examples/streaming_compression.c). I added a few lines in  `compressFile_orDie()`(full code [here](https://gist.github.com/bennyyip/cc45ab593afa848c00fb312384fee525)):
```C
#ifdef ZSTD_MULTITHREAD
    assert(!ZSTD_isError(ZSTD_CCtx_setParameter(cstream, ZSTD_c_nbWorkers, 2)));
#endif

    // size_t const initResult = ZSTD_initCStream(cstream, cLevel);
    // if (ZSTD_isError(initResult)) {
    //     fprintf(stderr, "ZSTD_initCStream() error : %s \n",
    //                 ZSTD_getErrorName(initResult));
    //     exit(11);
    // }
```

It seems that https://github.com/facebook/zstd/blob/470344d33e1d52a2ada75d278466da8d4ee2faf6/lib/compress/zstd_compress.c#L4021 would create `mtctx` only if `cctx` is not initialized(i.e. `cctx->streamStage == zcss_init`). So I comment `ZSTD_initCStream` and set `ZSTD_c_nbWorkers` to 2.

But this modified version of `streaming_compression` dies after calling `ZSTD_endStream` and exit with message "not fully flushed". This can be reproduced on large enough input, for example, [silesia.tar](http://sun.aei.polsl.pl/~sdeor/index.php?page=silesia).

I think maybe I misunderstand the way to use ZSTD. So how to use streaming compression with multi-thread?

**Comment by terrelln** [comment]
Hey @bennyyip, there are two things that should help you here:

1. I updated [streaming_compression.c](https://github.com/facebook/zstd/blob/dev/examples/streaming_compression.c) to use the new API a week ago. Now you would just insert your call to `ZSTD_CCtx_setParameter(cctx, ZSTD_c_nbWorkers, 2))` where the other parameters are set.
2. The reason you were seeing that not flushed error, is because in multithreaded mode `ZSTD_endStream()`, or equivalently `ZSTD_compressStream2()` with `ZSTD_e_end`, so you need to call it until it returns `0`. We realized that this was a confusing behavior, so in commit 48a6427d22f290157b8acc3f7c03c0f762a768be we made `ZSTD_endStream()` block until either its output buffer is full, or the stream is complete.

We'll be releasing a new version of zstd on Monday with a focus on the advanced API. Please let me know if you find any of the new documentation confusing, so I can improve it.

**Comment by bennyyip** [comment]
@terrelln Thanks for your quick reply! I will open an issue if I found any confusion in the new documentation.

**Comment by wupengcheng6819** [comment]
It appears that the multi-thread option is not working, even in the given example `streaming_compression`. And the compression result is different.


```
$ time streaming_compression data 3 8
Starting compression of data with level 3, using 8 threads

real    0m6.646s
user    0m6.222s
sys     0m0.423s

$ time zstd -T8 < data >data2.zst

real    0m1.405s
user    0m9.425s
sys     0m0.563s

$ ls -l data*.zst
-rw-r--r-- 1 root root 398568858 Apr 26 18:11 data.zst
-rw-r--r-- 1 root root 398964840 Apr 26 18:11 data2.zst
```

Zstd version: 1.5.5
Local machine: Centos 7

**Comment by Cyan4973** [comment]
Was the library compiled with multithreading enabled ?

**Comment by wupengcheng6819** [comment]
I think so. The commandline `zstd` in foler `programs` works fine with multithreading.  I simply ran the default Makefiles to build, don't see any options...

**Comment by Cyan4973** [comment]
The examples link to the static version `libzstd.a` of the library.

This version is single-threaded by default : 
https://github.com/facebook/zstd/tree/dev/lib#multithreading-support

Consequently, requesting multithreading results in an error, but this error is not checked by the example, so it remains invisible. After that, the library reverts to single-threaded behavior.

To compile the static library in multithreading mode, one can do : 
```
CPPFLAGS=-DZSTD_MULTITHREAD make
```

Note that linking a program to the multi-threaded version of the static library can lead to further compilation shenanigans depending on system, such as declaring an explicit link to the `pthread` library (on `macos`, there is nothing to add, it's transparent). That's why it's not default.

After that, I get the expected multi-threading performance : 

```
> time ./streaming_compression silesia.tar 9 1
Starting compression of silesia.tar with level 9, using 1 threads
./streaming_compression silesia.tar 9 1  2.52s user 0.07s system 101% cpu 2.540 total

> time ./streaming_compression silesia.tar 9 3
Starting compression of silesia.tar with level 9, using 3 threads
./streaming_compression silesia.tar 9 3  2.88s user 0.06s system 281% cpu 1.045 total
```
