### ISSUE TITLE
zstd Decoding error (36) : Destination buffer is too small

### ISSUE THREAD

**Issue by klauspost** [facebook/zstd#1606]
It seems like the zstd commandline can fail rather arbitrary:

```
zstd.exe -d d93f6a3b678f3ae4f31c32b3ebcfcaf75c8f515f.zst
ebcfcaf75c8f515f.zst : Decoding error (36) : Destination buffer is too small
```

Input: [d93f6a3b678f3ae4f31c32b3ebcfcaf75c8f515f.zst.gz](https://github.com/facebook/zstd/files/3125394/d93f6a3b678f3ae4f31c32b3ebcfcaf75c8f515f.zst.gz) (gzipped to make github happy)

There shouldn't be a reason that zstd cannot decode this. It should decompress to a file that is 394754 bytes of `48`. I guess it should switch to a stream decoder if it fails to allocate a big enough buffer rather than throw an error.

v1.4.0 used in Win64.

**Comment by terrelln** [comment]
The frame header says it is a single-segment frame with size 48. That means the decoder must allocate >= 48 contiguous bytes to decode the data, and the data will be exactly that size.

However, the block says it is a RLE block of byte `0x30` of size  394754. This is now an invalid frame, since the frame header size is wrong, and the decoder could emit `srcSize_wrong`. If the destination buffer was large enough, the decoder checks this at the end of the stream and would error anyways.

Since the decoder ran out of output room before it validated the regenerated size, it returned destination buffer too small.

**Comment by klauspost** [comment]
Make sense. So I guess this falls into "allowed to" portion:

>In order to preserve the decoder from unreasonable memory requirements, a decoder is allowed to reject a compressed frame which requests a memory size beyond decoder's authorized range.

>For broader compatibility, decoders are recommended to support memory sizes of at least 8 MB. This is only a recommendation, each decoder is free to support higher or lower limits, depending on local limitations.

I guess it is better to have the reference decoder be more strict about this.

**Comment by terrelln** [comment]
> Make sense. So I guess this falls into "allowed to" portion:

This example is corrupted data, since the size written into the frame header (48 bytes) is not the same as the regenerated size (394754 bytes). A decoder should report an error in this case.

A example that would fall into the "allowed to" portion would be that by default the zstd decoder allows window sizes up to 128 MB. A frame whose header says it requires a window log > 2^27, or who is single segment with a size > 2^27 would be rejected by the zstd decoder. We allow a flag `-M` to control the maximum memory allocation.

**Comment by klauspost** [comment]
Sounds reasonable. I will add a hard reject on this case.

**Comment by unoexperto** [comment]
I don't know if it's related but I managed to get this exception inside of AWS Redshift :)

```
[2021-11-14 20:20:24] -----------------------------------------------
[2021-11-14 20:20:24] error:  S3CurlException: Failed writing body (0 != 6149) Cause: zstd - stream decompress failed. Destination buffer is too small (error code: 70), CurlError 23, multiCurlError 0, CanRetry 0, UserError 0
[2021-11-14 20:20:24] code:      9001
[2021-11-14 20:20:24] context:   S3 key being read : s3://xxx-xxx/redshift_chunk_11415238115203909871.csv.zstd
[2021-11-14 20:20:24] query:     5321146
[2021-11-14 20:20:24] location:  copy_s3_scanner.cpp:304
[2021-11-14 20:20:24] process:   query0_127_5321146 [pid=4389]
```

I used following file
[redshift_chunk_11415238115203909871.csv.zstd.tar.gz](https://github.com/facebook/zstd/files/7534606/redshift_chunk_11415238115203909871.csv.zstd.tar.gz)

**Comment by jeffparsons** [comment]
@unoexperto I also have run into this with Redshift recently. Unfortunately I can't share the relevant file.

I'm currently trying to figure out whether there's actually anything weird about the file. It seems valid (downloaded it, decompressed it, validated that the decompressed content at least parses) but Redshift continually chokes on it with the error above.

I haven't been able to figure out what version of zstd Redshift is running; I'd like to try decompressing it with that exact version in case it's just an old bug or something.

**Comment by fullcrypt** [comment]
@jeffparsons have you figured out the root cause? it seems I have the same issue from time to time (either Destination buffer is too small or Data is corrupted) from zstd...

**Comment by jeffparsons** [comment]
@fullcrypt AWS support confirmed that I was running into a bug in their implementation, but were unwilling to share any detail beyond that. (I wonder if that means it's exploitable? 😈)

They have a fix for the bug now, but said it will be deployed some time in the next few months (I assume that's their normal release cadence or something) so I have no idea what to expect. 

In my case the affected functionality is actually not all that important, so we've elected to wait. The advice from AWS was to use a different compression scheme.

**Comment by fullcrypt** [comment]
@jeffparsons many thanks for the reply. 
Their reply sounds really puzzling though.. curious if the issue was inside some system library maybe. As it is not easily reproduced on other environments..
