### ISSUE TITLE
What is the minimum bytes recommended for compression?

### ISSUE THREAD

**Issue by hiqinternational** [facebook/zstd#1628]
100bytes / 256bytes / 1000bytes? for utf8, ascii etc. can't seem to find such information online.

**Comment by Cyan4973** [comment]
There is no _universal_ answer.
It all depends on which kind of data.
Some will need 1 KB before starting to show visible gains.
Some will be compressible as soon as 200 bytes.

A very generic rule of thumb is to not expect much compression below 100 bytes.
It's still not a lower bound : 100 bytes of `\0` can still compress well,
but given some "normal text" data, I would expect 100 bytes to provide limited perspective (< 10%) in most circumstances, so it's relatively safe to skip compression under this threshold.

But even 200 bytes of text can get decent compression. I'm observing ~30% gains testing some casual unstructured english text.

**Comment by felixhandte** [comment]
Hi @hiqinternational,

It's hard to offer broad guidance on this topic. It all depends on the nature of your data (the presence of redundancies and repetitions), and your goals for compression. As you increase the size of the data being compressed, the ratio will improve from no benefit at all (where the header cost exceeds any savings) and asymptotically approach some upper limit. That limit in compression ratio, and the speed at which it approaches that upper bound, depends entirely on the data.

It then becomes a decision in balancing the benefits of compressing larger chunks of data (and therefore achieving better compression) against the benefits of compressing smaller chunks (presumably, finer-grained access into your data).

Can you share some more context around your use case?

**Comment by hiqinternational** [comment]
Thanks for the answer.
I was wondering if someday it's an nginx config option, what will the recommended min_length be.

I understand what you mean.

I'm looking for a generic, advisable, standard recommendation to set min_length.

I'm mostly thinking of compressing flatbuffers of exactly 384bytes, 512bytes and 1024bytes. so i'm wondering if it's worth the compression at all.

will be in flatbuffers format which includes strings in utf8.

**Comment by felixhandte** [comment]
@hiqinternational, I see.

Yeah, for HTTP compression, you'll want to bias higher for a cut-off point, since you also need to account for the penalty of including a `Content-Encoding: zstd\r\n` header in the response (although [HPACK](https://tools.ietf.org/html/rfc7541) and [QPACK](https://tools.ietf.org/html/draft-ietf-quic-qpack-08) can lower that cost from the literal 24 bytes it would be in an HTTP/1 response).

On the other hand, flatbuffers are definitely not optimized for compactness, and Zstd can frequently achieve pretty good compression on them.

The long term answer for problems in this domain is [dictionary compression](https://github.com/facebook/zstd#the-case-for-small-data-compression), which I am working to bring to HTTP.

**Comment by hiqinternational** [comment]
back to the question:
384bytes min is good if it's flatbuffer?

**Comment by felixhandte** [comment]
That seems reasonable to me. Certainly it's within an order of magnitude of the correct answer. :)
