### ISSUE TITLE
[linux-kernel] Update to latest zstd

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#1638]
* [x] https://github.com/facebook/zstd/issues/1636
* [x] https://github.com/facebook/zstd/issues/1637

**Comment by polarathene** [comment]
@terrelln both linked issues have been resolved by PRs, will the update be for future kernels or also LTS like 5.4? Is it likely to see the update by kernel 5.9?

**Comment by nariox** [comment]
For whoever is following this, terrelln has been hard at work.

You can look at the major commit: https://github.com/terrelln/linux/commit/e12184696a1ae080ffe6378f9d538b3d80a65faa
And test his branch at https://github.com/terrelln/linux/tree/zstd-1.4.6

**Comment by nariox** [comment]
For those subscribed here, the update v11 (zstd v 1.4.10) has been proposed: [LINK](https://lwn.net/ml/linux-kernel/20210430013157.747152-1-nickrterrell@gmail.com/)

As a BTRFS user with zstd'd kernel, ramdisk, and initramfs, I am really eager to test out all the improvements to zstd since 1.3.1. Thank you @terrelln!

EDIT: update link to v11 (from v10).

**Comment by romulasry** [comment]
Zstd 1.4.9 Released With ~2x Faster Performance For Long Mode
https://github.com/facebook/zstd/releases/tag/v1.4.9

**Comment by nariox** [comment]
Hi @terrelln,
I have been trying to figure out what is happening. Seems like with the addition of the MAINTAINERS file, there shouldn't be major objections to the ZSTD update. Other than David Sterba's endorsement, what else would be needed for the update to be pushed to 5.14?

**Comment by polarathene** [comment]
Is it unlikely that this will make it into the next LTS kernel release?

I have tried to look for any progress since the last referenced mailing list but searching LWN didn't seem to show anything. Looking at @terrelln linux fork branches, last activity seems to be from end of April 2021. The linked LWN thread was last active in May 2021.

Is this still being pursued? If any assistance is required, please let the community know where we can help :)

**Comment by nariox** [comment]
This was merged into linux-next, so, most likely will be included on Linux 5.16.

Thank you @terrelln!
