### ISSUE TITLE
Multi-threaded Build Makefile CPPFLAGS Args Missing

### ISSUE THREAD

**Issue by ghostop14** [facebook/zstd#1657]
I was trying to build libzstd with multi-thread support, and the only way I was successful was in editing the lib/Makefile and changing 

lib: libzstd.a libzstd

to:

lib: CPPFLAGS += -DZSTD_MULTITHREAD
lib: libzstd.a libzstd

Without it, calls to ZSTD_CCtx_setParameter() for ZSTD_c_nbWorkers generates a parameter not supported error.  Building with multi-thread support should be the default.

**Comment by Cyan4973** [comment]
Modify the `Makefile` to get multithreading support is neither required nor recommended.
Alternative methods include : 

- Pass compilation directive on command line :
  `CPPFLAGS=-DZSTD_MULTITHREAD make lib`
- Invoke the prepared multi-thread target `lib-mt` : 
  `make lib-mt`

This is explained in the `lib` documentation, at : 
https://github.com/facebook/zstd/tree/v1.4.0/lib#multithreading-support

> Building with multi-thread support should be the default.

This was considered, and I like this idea.
However, there are counter-arguments to this choice.

The most important one is that it's not enough to compile with the multithread build macro : the real issue comes at link stage, where it's necessary to invoke `-pthread` (typically). This can be more or less possible, or even just not desirable, depending on use cases.

We have identified a few scenarios where updating to a new version of the library with multithread support enabled by default would break the project's build chain, and it was considered unacceptable up to `<v1.4.0`, because the multi-thread support used to be labelled "experimental".

Now that multithreading is officially part of the stable API, it gives more weight to supporting it by default in the generated library. Hence, we'll revisit this choice. But for that to happen, we'll have to investigate again the problematic scenarios, and find mitigation techniques. Even then, we might end up with some scenarios that can't be solved transparently, with the user project being required to adapt its build chain in order to link or run its program properly.

**Comment by ghostop14** [comment]
Problem is, I get errors (latest clone, just refreshed this morning).  The Makefile in the root directory doesn't have a lib-mt option.  There is a zstdmt but that just seems to build the zstdmt command-line tool?

from zstd's git cloned directory:

make lib-mt
make: *** No rule to make target 'lib-mt'.  Stop.

from lib:
make lib-mt
make: *** No rule to make target 'lib-mt'.  Stop.

Any suggestions?

Editing the Makefile has been the only way I've successfully gotten the multi-threaded build.  If there's arguements against the default being multi-threading support, maybe it gets flipped and have a build switch for single-threading and default to multi-threaded?

**Comment by Cyan4973** [comment]
`lib-mt` is a target defined into `lib`'s `Makefile`,
so not at root level.

I'm surprised it did not worked for you.
I just made a test, and `make lib-mt` does generate the expected binaries,
using both current `dev` branch and the release `v1.4.0`.

I'm not sure to understand what' happening on your system,
Which version of the library are you compiling ?

> maybe it gets flipped and have a build switch for single-threading and default to multi-threaded?

That's exactly what "default" is about.

**Comment by ghostop14** [comment]
I'm on the latest (I just did a fresh git pull this morning just to be safe.

git branch
* dev

git show
commit b26818fe731f5636905dba1b751d05c92285dea4
Merge: aeb86b1 bc400ed

**Comment by Cyan4973** [comment]
This is indeed, current latest commit on `dev` branch.

The `lib-mt` target is defined then. It should work. I tried it again, from multiple platforms, they all work correctly.

Don't forget that `lib-mt` is only defined in `lib` directory.
So either `cd lib; make lib-mt`,
or, if you want to run from and stay in root directory : `make -C lib lib-mt`.

**Comment by ghostop14** [comment]
Just to verify something wasn't corrupt locally I completely deleted my zstd directory thread and recloned it.  That seemed to fix the make lib-mt issue.  No errors reported previously not sure what happened there.

Is there a way to make both the multi-threaded library and the command-line zstd utility in one shot?

**Comment by Cyan4973** [comment]
> Is there a way to make both the multi-threaded library and the command-line zstd utility in one shot?

`CPPFLAGS=-DZSTD_MULTITHREAD make`

**Comment by ghostop14** [comment]
That did the trick.  Thanks for the help!
