### ISSUE TITLE
 improvement of the detection of BMI2 support in the compilation toolchain needed

### ISSUE THREAD

**Issue by astratsx** [facebook/zstd#1704]
I recently encountered a compile time problem with DYNAMIC_BMI2 when compiling zstd on our RHEL 6.7 box using gcc 7.4 that I built for this box. I got an error that indicated that gcc 7,4 generated BMI2 instructions even though I had not specified an -march option that supports the AVX2 instruction set. Thes BMI instrcutions were not recognized by the older GNU assembler version 2.20.51.0.2-5.43.el6 20100205 that comes with RHEL 6.7. Yes, I could update the entire tools chain with a newer version of binutils to obtain a version of "as" that supports AVX2 an later, but I believe that it is an incorrect assumption to base DYNAMIC_BMI2 solely on the gcc version. Just because a particular version of gcc has the capability to generate BMI2 instructions doesn't mean that it should. The entire tool chain, including "as", must also have the ability to support BMI2. Also, I was intentionally building zstd targeting the SandyBridge architecture (yeah, we still have a lot of older HW) which does NOT support BMI2. I was not expecting the compiler to generate BMI2 instructions. The current DYNAMIC_BMI2 logic simply ignores the command line arguments setting for target machine architecture. For example: -march=sandybridge
I was able to work around this by setting DYNAMIC_BMI2=0 when building, but it was not obvious that this was the correct way to work around this issue nor was there doc that I could find stating that this behavior would occur. In any case, it would really be nice if the detection of BMI2 support were more intelligent and took into account the entire tool chain. Thanks.

**Comment by Cyan4973** [comment]
I believe that setting `DYNAMIC_BMI2=0` was the correct action to do for your use case.

The purpose of `DYNAMIC_BMI2=1` is that binaries can be created on a system with or without `BMI2`, and then be delivered to systems with or without `BMI2`, and the same binary will make the most appropriate choice locally, at runtime. There's nothing exceptional in this behavior, equivalent mechanisms can be found in many performance-oriented softwares.

We understand that there are situations where this behavior is not desirable, and that's why there is a direct control accessible through `DYNAMIC_BMI2` build macro.

It's unfortunate that the documentation wasn't clear enough. That's a point that can certainly be improved.

**Comment by astratsx** [comment]
@Cyan4973 I understand; however, I believe that it is inherently incorrect to automatically enable BMI2 just based upon what version of gcc that you are using. It may make more sense to remove this detection and make setting DYNAMIC_BMI2 a user defined requirement prior to build time? That way the builder of the software can decide whether they want BMI2 instructions to be generated of not. Thanks for you consideration.

**Comment by astratsx** [comment]
@terrelln Making Nick aware of this entry since he offered to take on a PR to work on making detection better.

**Comment by Cyan4973** [comment]
Added documentation on `DYNAMIC_BMI2`, to make this feature easier to find and understand.
