### ISSUE TITLE
Remove mixing of function result and error codes

### ISSUE THREAD

**Issue by andrew-aladev** [facebook/zstd#1825]
Hello, I am new to `zstd`.

```
size_t ZSTD_CCtx_setParameter(...); // regular function
ZSTD_ErrorCode ZSTD_getErrorCode(size_t functionResult);
ZSTD_error_maxCode = 120;
```

I was wondering why `size_t` and opened `lib/common/error_private.h`:

```
#define ZSTD_ERROR(name) ((size_t)-PREFIX(name)); // => (size_t)-120
```

We can see that you are actually **mixing** function result and error code in `size_t`, max possible value for function result is `sizeof(size_t) - 121`. It is not safe.

```
 * @return : the compressed size of the first frame starting at `src`,
 *           suitable to pass as `srcSize` to `ZSTD_decompress` or similar,
 *        or an error code if input is invalid */
size_t ZSTD_findFrameCompressedSize(const void* src, size_t srcSize);
```

Any function like this one returning both size and error can easily overflow. It is not possible in terms of fair use, but it will be used to attack applications. Approach of mixing size and error is defective by design, please remove it.

This function can look as follows:
```
ZSTD_ErrorCode ZSTD_findFrameCompressedSize(
  const void* src, size_t srcSize,
  size_t * frameCompressedSize);
```

Thank you.

**Comment by Cyan4973** [comment]
These functions return a __sum type__,
aka a value which either means a success, providing a size,
or an error, providing a specific code, for accurate debugging.
It cannot mean both at the same time, which is actually a good thing, as it removes the possibility of return inconsistency.

I acknowledge that `size_t` is not inherently a sum type,
and it's the way it's employed in `libzstd` API that makes it a sum type.
Especially, the return value must always be tested with `ZSTD_isError()`,
in order to determine if it's a success, or an error.
Only then can the value be interpreted correctly.
This pattern is documented pretty heavily  in `zstd.h`, and it's also fairly easy to understand. As a consequence, so far we never met significant problem with this it.

I also acknowledge that it's pretty easy for a user application to _forget_ testing the return value with `ZSTD_isError()`, and instead read it as a size directly, leading to potential undefined behavior. When that happens, a quick reminder from the documentation is all it takes to fix the issue.

This situation is not uncommon, as many existing `C` functions do offer identical experiences : `malloc()` can return `NULL`, which is a failure, `fwrite()` can return `0`, which may be an error, etc. A "good" user program must not assume success, it must check return values for the possibility of failure.

The Zstandard's API was established almost 5 years ago, and an important property of an API is its stability. We can't just wreak havoc into an established ecosystem by breaking its stable interfaces, just on the ground that a new incompatible one might be better. Stability is worth a lot more than that.

Besides, it ignores that this API has been in widespread use already, and the presumed issue has never been a big problem : using a return value as a sum type is actually common in C, and as long as it is well documented, it's generally accepted, and deployed correctly. At least, it's our experience.

This doesn't mean that no progress can ever be achieved. In recent times, I've been proposing some different APIs, in an attempt to make this construction more reliable. For example, the return type can be a `struct`, using scary member names, such as `do_not_access_me`, and requiring to pass through helper functions to retrieve the result, such as `getResult(value)`, which would automatically trigger an `abort()` in case `value` is actually an error (somewhat similar to some Rust's runtime constructions).

While this proposal seems safer in theory, since it forces the pattern of verifying the return type before interpreting the value, and backup to `abort()` in case this check wasn't performed by the user, it has been considered "heavy" in our limited experiments. It does not sound like much, but it adds work on the library implementer (helper functions, custom type), it adds new symbols and names, and adds an unusual pattern for most C developpers.
So much that some users regularly decided to actually read `do_not_access_me` directly, on the ground that it's easier (it's not that easier, really, but it's more familiar).

That is to say, we live in a time with some already established experience and practices, and can't just ignore that. A good approach blends into existing microcosm while providing additional benefits (safety in this instance).

Speaking of which, your proposed API suggestion is well known, and it is applicable.
But it doesn't solve the core issue of "API safety" which is hinted in your post.
A user can still ignore the return code and go straight to reading `*frameCompressedSize`, which is likely UB if the function has errored. Also, the library implementer must define and pay attention to the return value provided in `*frameCompressedSize` when the function fails, making the contract slightly more complex (hence more complex to test, easier to get wrong, etc.). This interface is incompatible with a simpler `const` initialization, which is a great pattern contributing to code resiliency. It also forces the compiler to use 2 registers instead of 1 (in the best case), which is not important for one function in isolation, but when this process is repeated over the whole code base (as is the `size_t` sum type within `zstd` code base, since it's present basically everywhere), all this adds up, and things get more complex when optimizing some hot functions in some critical loops. 

Anyway, both approaches are possible, and there is certainly ground for debate,
but the real issue is : this API is now stable, and must __not__ change.
The debate can happen, but for some future API, in some future library.

**Comment by andrew-aladev** [comment]
> It cannot mean both at the same time, which is actually a good thing, as it removes the possibility of return inconsistency.

It can return inconsistency, because it is **size**, size is the the main thing in any application that can be large. `(size_t) -10`, `(size_t) -12` is still a valid size, but it overlaps with `ZSTD_error_prefix_unknown`, `ZSTD_error_version_unsupported`. Any hacker will try to attack size in application linked with `zstd`.

> I acknowledge that size_t is not inherently a sum type,
> and it's the way it's employed in libzstd API that makes it a sum type.

I've already mentioned a place where it is implemented as `(size_t)-size`. You have just **hidden** errors from user point of view by using biggest possible values.

> This situation is not uncommon, as many existing C functions do offer identical experiences : malloc() can return NULL, which is a failure, fwrite() can return 0, which may be an error, etc. A "good" user program must not assume success, it must check return values for the possibility of failure.

Sorry, but this situation is the most uncommon I've ever seen. There following common approaches to mix errors and values today in C:

1. Unsigned type: `size_t`, `uint`, etc. Error value is 0, regular value > 0.
2. Unsigned type: `size_t`, `uint`, etc. Error signal is 0, regular value > 0. Error values - `errno`.
3. Signed type: `ssize_t`, `int`, etc. Error values < 0, regular values > 0.
4. Signed type: `ssize_t`, `int`, etc. Error signal is -1, regular value > 0. Error values - `errno`.

Nobody ever mixed multiple error and regular values inside unsigned types, especially inside `size_t`. It is the most dangerous type for mixing.

> The Zstandard's API was established almost 5 years ago, and an important property of an API is its stability. We can't just wreak havoc into an established ecosystem by breaking its stable interfaces, just on the ground that a new incompatible one might be better. Stability is worth a lot more than that.

Zstandard code is very good for proof of concept, but the problem is that @felixhandte wants [here](https://github.com/facebook/zstd/issues/1669) to make a worldwide integration.

> Besides, it ignores that this API has been in widespread use already, and the presumed issue has never been a big problem : using a return value as a sum type is actually common in C, and as long as it is well documented, it's generally accepted, and deployed correctly. At least, it's our experience.

Size of `size_t` on **x86** system is just 4 bytes. It will become a problem soon, when someone will make a security review or first overflow **exploit** will appear. Functions behaviour like `ZSTD_findFrameCompressedSize` and its bindings are not defined when it will try to return large size.

> Anyway, both approaches are possible, and there is certainly ground for debate,
> but the real issue is : this API is now stable, and must not change.
> The debate can happen, but for some future API, in some future library.

You can select any commonly used approach, I am not insist on separate result and size pointer. Current approach is not acceptable.

**Comment by Cyan4973** [comment]
> Functions behaviour like ZSTD_findFrameCompressedSize and its bindings are not defined when it will try to return large size.

It's simply not possible

`ZSTD_findFrameCompressedSize()` takes a buffer as argument, with a `srcSize` expressed using `size_t`. It follows that its return value is necessarily `<= srcSize`, which means it's within `size_t` range, whatever the size (4 or 8 bytes) of `size_t`.


> Signed type: ssize_t, int, etc. Error values < 0, regular values > 0.

Well, that's how `LZ4` decoder works.
The idea was to do something similar, except that `size_t` being unsigned, it can't be negative.
Hence the closest thing was to reserve the last values, at the end of the range, for error codes.

Using this method, detecting an error does no longer use a comparator like `value < 0`, or even `value == 0`, the only difference is that it's replaced by a call to `ZSTD_isError(value)`. Which is just plain equivalent. Whatever happens inside `ZSTD_isError()` (it's actually just a `>` comparator), it does exactly the same job, at exactly the same place in the code, with same consequences.

This construction may be unfamiliar to you, that does not make it an instant vulnerability. Usage of `ZSTD_isError()` is the core component in this pattern, it must not be skipped. Then it's as safe as any other listed pattern.
