### ISSUE TITLE
Use tar to compress with `--ultra -22 -T8`

### ISSUE THREAD

**Issue by txtsd** [facebook/zstd#1829]
I'm trying to compress a directory with tar using the settings I usually use to compress with zstd.
`env ZSTD_CLEVEL=19 tar -cvf --zstd archive.tzst directory/`

Apart from setting `ZSTD_CLEVEL`, which only goes up to 19, I'm unable to find any other way to communicate the ultra setting and threads to tar.

How do I go about doing it?

**Comment by Cyan4973** [comment]
Hi @txtsd ,

you are correct, there is currently no way to set the level into `--ultra` territory using `ZSTD_CLEVEL`.

Such a capability is undecided yet.

It's technically possible to offer it : whenever `ZSTD_CLEVEL > 19`, automatically enable `--ultra` in the background. That would make levels 20-22 accessible.

However, another school of thought is : 
`--ultra` levels are not recommended, due to the very high memory usage they require, at both compression and decompression time.

Why would it matter ?
Well, the issue with environment variables is that they could be set silently by some external actor, without the user being aware of it. In this case, the idea would be to make the compressor use a lot of resource to produce some side effect, such as triggering a OOM-killer, or just making the system unresponsive.

The trade-off between benefit and risk is unclear at this stage. It could be that the risk is overblown. We are simply not sure.

> I'm unable to find any other way to communicate the ultra setting and threads to tar.

Another method is to pipe the output of `tar` into `zstd`.
This way, the full range of `zstd` commands is available.

Example :
`tar -cvf - directory/ | zstd -T0 --ultra -22 > archive.tzst`

The difference in this case is that no option is "silent", in the background, so the user can be fully in charge.

Note that the above example setting (`-T0 --ultra -22`) can require a _lot_ of memory, possibly more than the host can provide (~1 GB per active thread).

**Comment by txtsd** [comment]
Thank you for the explanation! Piping works for me as an alternative solution. And I use it on my desktop, so memory is not an issue.

**Comment by marxin** [comment]
Hello.

I face the very same problem and would recommend to really support something like `ZSTD_OPTIONS` env variable that will accept any option that `zstd` binary does.
I would really like to use threads for a tar compression with zstd.

**Comment by Cyan4973** [comment]
We have already ruled out against a "generic pass-through" environment variable, that could be abused for side effect and become a security liability (which is a scenario which already happened in practice with `gzip` in the past).

But we are opened to the possibility of increasing the number of accessible options from environment variables, as long as it's controlled and feels safe.

To progress on this path, we would need one or several scenarios justifying the need for triggering specified commands or parameters through environment variables.

**Comment by marxin** [comment]
> To progress on this path, we would need one or several scenarios justifying the need for triggering specified commands or parameters through environment variables.

I'm definitely interested in the usage of threads by `zstd`. In my case, I prefer to use `-T0` to make autodetection. Is it something you can support?

**Comment by AnimMouse** [comment]
`tar -I "zstd -T0 --ultra -22"`
