### ISSUE TITLE
Training Dictionary in streaming mode

### ISSUE THREAD

**Issue by yuruiz** [facebook/zstd#1913]
Hi guys, looking into the [ZSTD dictionary building API](https://github.com/facebook/zstd/blob/master/lib/dictBuilder/zdict.h) I noticed that currently ZSTD requires that all the samples to be loaded into a single flat buffer. Is it possible to build a streaming mode dictionary building api that allow user to feed samples into the builder in multiple times? The streaming mode api would potential reduce the required memory footprint and avoid unnecessary memcpy.

**Comment by Cyan4973** [comment]
This capability does not exist right now.
And it's far off.

To make this technique worthwhile, the streaming mode would need to enrich some internal data model, which would no longer require the input for further processing. The data model should also cost a fraction of the input size, otherwise the "memory savings" do not make sense. Both conditions do not hold with current algorithms.

Bottom line : one would need to develop a completely different algorithm to support such capability. It's not in the roadmap.

**Comment by yuruiz** [comment]
Well, if streaming mode is not feasible right now. What about merging dictionary? Is it possible to merge dictionary trained from different samples?
