### ISSUE TITLE
Does zstd handle compression of changing files?

### ISSUE THREAD

**Issue by anayrat** [facebook/zstd#1926]
Hello,

I tried to use zstd to compress log files which are continuously appended. 

Execute:
```bash
#!/bin/bash
while true
do
echo "line" >> /tmp/log.txt
done
```
When I tried to compress in another session I were faced to this issue:
```
zstd --compress --stdout /tmp/log.txt > /tmp/log.txt.zst
zstd: error 27 : Read error : Incomplete read : 66205544 / 66194080 B 
zstd -t /tmp/log.txt.zst
/tmp/log.txt.zst     : 0 MB...     /tmp/log.txt.zst : Decoding error (36) : Corrupted block detected 
```

Note gzip handle this:
```
gzip  --stdout /tmp/log.txt > /tmp/log.txt.gz 
gzip: /tmp/log.txt: file size changed while zipping
gzip -v -t /tmp/log.txt.gz
/tmp/log.txt.gz:	 OK
```

Same for lz4:
```
lz4 --compress --stdout /tmp/log.txt > /tmp/log.txt.lz4
lz4 -t /tmp/log.txt.lz4                                
/tmp/log.txt.lz4     : decoded 71455396 bytes                    
```

Regards,

**Comment by Cyan4973** [comment]
Hi @anayrat , 
that's indeed unexpected.

Is it reproducible ?
And is it possible to share an example that produces this outcome ?

**Comment by anayrat** [comment]
> Is it reproducible ?

Yes

> And is it possible to share an example that produces this outcome ?

You just have to append lines to a file and compress in another session.

FYI, I tried with zstd 1.4.4 (archlinux) and 1.3.8 (debian package)

**Comment by Cyan4973** [comment]
OK, it took me a while to figure out what the problem was.

So what you mean is, if the file _is being modified (appended) at the same time that it is being compressed_, then `zstd` produces an error at the end. This is different from `gzip` which doesn't complain.

`zstd` produces an error because it detects that the size of the file is not the one that was claimed at the beginning of the session. This is classified as a file system error.

##### Why ?

When compressing a file, `zstd` queries the size of said file, and this becomes an information _embedded into the frame header_.
Once expressed in the header, the information is controlled. It must be correct, otherwise it's labelled an encoding error. The decoder will also complain if a frame with a mismatch between header and content size is decoded.

The main scenario which we want to protect against is early truncation. In some cases, file systems may be not that reliable. Granted, this is more likely a scenario for large data centers, where some file systems layers can be pretty complex and strange. If source size is not controlled, the compressed file might contain a truncated version of the source, due to some FS error, but it may still appear as a success. Administrator will be unaware that data is truncated, think all is fine, and only discover the problem much later when trying to regenerate the data.
This is a big deal.

### Work around : 

You can **_pipe_** input data into `zstd` so that it has _no idea_ of the original source size and will not complain about a difference at the end. This is almost the same command : 
```
zstd --compress --stdout < /tmp/log.txt > /tmp/log.txt.zst

echo $?
0

zstd -t /tmp/log.txt.zst
/tmp/log.txt.zst    : 22819445 bytes
```

### In the future

Right now, the check is pretty strict, and only accepts that the file has the exact same size as the one claimed at the beginning of the session. The idea was to protect from early truncation issues, but it also excludes simultaneous appending.

If continuing to append at the same time as the file is being compressed is deemed a scenario worth supporting, we could adapt the rule, although the outcome is slightly different from the work around : 
- when piping data into `zstd` through `stdin`, `zstd` has no idea of the source side, and will compress as much data as presented. If new data is appended while compressing the source, it will also be present in the compressed frame.
- when compressing a file, `zstd` will probe and then save the file size in the header. It must then be correct. As a consequence, it must stop once it has compressed as much data as expected. If new data is appended while compressing the source, it will __not__ be present in the compressed frame.

I suspect the difference doesn't matter much, but it's good to be aware of it.

**Comment by anayrat** [comment]
> OK, it took me a while to figure out what the problem was.
> 
> So what you mean is, if the file _is being modified (appended) at the same time that it is being compressed_, then `zstd` produces an error at the end. This is different from `gzip` which doesn't complain.

Exactly and lz4 do not complain too.

> 
> `zstd` produces an error because it detects that the size of the file is not the one that was claimed at the beginning of the session. This is classified as a file system error.
> ##### Why ?
> 
> When compressing a file, `zstd` queries the size of said file, and this becomes an information _embedded into the frame header_.
> Once expressed in the header, the information is controlled. It must be correct, otherwise it's labelled an encoding error. The decoder will also complain if a frame features a mismatch between header and content size.
> 
> The main scenario which we want to protect against is early truncation. In some cases, file systems may be not that reliable. Granted, this is more likely a scenario for large data centers, where some file systems layers can be pretty complex and strange. In some cases, due to some spurious FS error, source might be truncated, and seem "fully loaded". If size is not controlled, the operation will be classified as "successful", but the compressed file would only contain a truncated version of the source. Administrator will then be unaware that data is truncated, believe that all is fine, and only discover the problem much later, when trying to regenerate the data.
> This is a big deal.

Great, thank for this clear explanation :)

> ### Work around :
> 
> You can **_pipe_** input data into `zstd` so that it has _no idea_ of the original source size and will not complain about a difference at the end. This is almost the same command :
> 
> ```
> zstd --compress --stdout < /tmp/log.txt > /tmp/log.txt.zst
> 
> echo $?
> 0
> 
> zstd -t /tmp/log.txt.zst
> /tmp/log.txt.zst    : 22819445 bytes
> ```
> 

Thanks for providing this workaround!

> ### In the future
> 
> Right now, the check is pretty strict, and only accepts that the file has the exact same size as the one claimed at the beginning of the session. This is incompatible with simultaneous appending.
> 
> Since the original issue we want to be protected from is early truncation, we could consider a different method, which would still flag early truncation, but allow parallel appending. Note that such scenario is already possible using above work-around. The question is more : do we also want to support it when source is passed as a file.
> 
> If this scenario is deemed worth supporting, we could change the rule, although to be complete, the outcome would be slightly different from the work around :
> 
>     * when piping data into `zstd` through `stdin`, `zstd` has no idea of the source side, and will compress as much data as presented. If new data is appended while compressing the source, it will also be present in the compressed frame.
> 
>     * when compressing a file, `zstd` will probe the file size at the beginning, and then save it into the header. It must then be correct. As a consequence, it must stop once it has compressed as much data as expected. If new data is appended while compressing the source, it will **not** be present in the compressed frame.
> 
> 
> I suspect the difference doesn't matter much, but it's good to be aware of it.

It seems fine. Maybe you should look how other tools handle this case (gzip, lz4...)?
lz4 has an option `--[no-]content-size` to includes (or not) original size in headers.

**Comment by bimbashrestha** [comment]
@anayrat zstd now has a --no-content-size option like lz4
