### ISSUE TITLE
Decoding error (36) : Corrupted block detected on valid block that meets spec

### ISSUE THREAD

**Issue by pgraniello76** [facebook/zstd#2005]
Hi, 

I have a valid compressed block that meets the spec requirements but cannot be decompressed by the zstd software. It can be decompressed by the educational decoder.

Characteristics of the compressed block:
File Attributes:
##### BLOCK ##### 
LAST_BLOCK: 1
BLOCK_TYPE: 2
BLOCK_SIZE: 0x17

##### LITERALS ##### 
LIT_TYPE: 2
SIZE_FORMAT: 1

NUM_streams: 4, Regenerated_size: 4, Compressed_SIZE: 13 

Number of sequences = 2
Symbol compression modes =  ll(0) mo(0) ml(0)

Could you please explain why this file cannot be decompressed by zstd software?

I have attached the .zst file
[test.zip](https://github.com/facebook/zstd/files/4232332/test.zip)

**Comment by Cyan4973** [comment]
I suspect that the issue is that the compressed block is larger than its uncompressed size.

This, in itself, is not a problem (inflated blocks are allowed), but because this is a single-block frame, it also means that this block is larger than the filesize, which I presume is also the window size.
This is not allowed : no block, compressed or uncompressed, can be larger than the window size.

**Comment by pgraniello76** [comment]
Thank you for the quick response! I agree with the feedback and will make sure future files are following this requirement. I was able to create a new file with a larger window size for my testing purposes.
