### ISSUE TITLE
Dictionary compression negatively impacts ratio on a 4KB file

### ISSUE THREAD

**Issue by SmitaKumar** [facebook/zstd#2008]
A 16KB dictionary was built using 4KB segments of the 1MB kennedy.xls file of the Canterbury corpus.

Following table shows the compression ratio with and without the dictionary for the 1st 4 4k segments of kennedy.xls  (using the default compression level)
--------------------------------------------------
| 4k segments | CR w/o dict | CR with 16k dict|
--------------------------------------------------
|aa                  | 34.74%        | 36.11%               |
|ab                  | 21.22%        | 20.92%              |
|ac                  | 18.33%        | 12.30%               |
|ad                 | 16.28%        | 13.01%               |  
--------------------------------------------------

As shown in the table above, the compression ratio for the 1st 4k segment is better without the dictionary. If the dictionary isn't effective, I would expect that the compression ratio would remain the same. Why does it get worse?

Further investigation into the sequences produced with and without the dictionary shows that some matches are missed when the dictionary is enabled. 
1st sequence <LL, ML, MO> with dictionary <66, 6, 11>
1st sequence <LL, ML, MO> without dictionary <15, 4, 9>

**Comment by Cyan4973** [comment]
Could you try the same test with higher compression ratios ?
Like level 19 ?

**Comment by SmitaKumar** [comment]
Don't see the ratio degradation at level 19
| 4k segments | CR w/o dict | CR with 16k dict|
|aa                   | 33.06%       | 32.13%               |
|ab                   | 20.80%       | 18.65%               |
|ac                   | 16.92%       | 7.57%                 |
|ad                  | 16.06%        | 9.38%                 |

**Comment by Cyan4973** [comment]
OK, in which case, that's an expected.

At higher compression levels, there is more time available, so the algorithm can properly measure each choice and select the better one.

But with faster modes, less time is available to make "best" choices.
So the algorithm will rely on faster heuristics which "generally" work.
But not always.

For example, it will "blind trust" that the statistics tables are correct, and if they end up being suboptimal, it will not even realize it.

**Comment by SmitaKumar** [comment]
When dictionary is enabled, does it miss the 4 byte match at byte 16 because of a sub-optimal entropy table in the dictionary ? 

> Further investigation into the sequences produced with and without the dictionary shows that some matches are missed when the dictionary is enabled.
> 1st sequence <LL, ML, MO> with dictionary <66, 6, 11>
> 1st sequence <LL, ML, MO> without dictionary <15, 4, 9>

**Comment by Cyan4973** [comment]
There are multiple heuristics at play. Entropy table is only one example.

I presume "default compression level" means "level 3".

In which case, it has basically 2 chances per position to find matches. 
And when it finds a match, it basically "trusts" it, and move on to the next one.
This process may greedily select early matches, and "mask" later "more efficient" ones.
This is a case where having "more choices" can be detrimental.
Statistically, "more choices" is generally profitable, but in some cases, locally, it can be detrimental.

For the exact example provided, I understand that without dictionary, the match finder finds a match of length 4 after 15 literals, while with dictionary, it will skip it, and only find a match of length 6 after 66 literals.

This is an example of parameter adaptation. When compressing the isolated block, the compressor realizes it has only 4KB of data to search into, and will use parameters from the most appropriate table, in this case, the table dealing with input <= 16 KB.
While, when compressing a 4 KB block with a 16 KB dictionary, it will realize there is more data to search into, up to 20 KB, and will select its parameters from a different table, the one dealing with sizes from 16 KB to 128 KB.

Among the differences in these tables, there is the minimum match length.
A look at [these tables](https://github.com/facebook/zstd/blob/dev/lib/compress/zstd_compress.c#L4073) show that, for small inputs <= 16 KB, level 3 is happy with matches of length 4, while for larger inputs > 16 KB, it will rather aim at matches of length 5.

Why the difference ? Well, this is purely heuristic. In general, for larger inputs, discarded small matches for larger ones is supposed to be a better bet. But occasionally, it's not.

You can force the match finder to accept match lengths of 4 with an [advanced command](https://github.com/facebook/zstd/blob/dev/programs/zstd.1.md#advanced-compression-options) : 
`--zstd=mml=4`. This will likely fix the reported difference regarding the 1st sequence. But it may prove suboptimal in other cases. It depends...

Another idea is to reduce the dictionary to 12 KB in order to ensure that the sum of both input + dictionary remains <= 16 KB. With less dictionary content, it will hurt ratio in other ways, but for testing, it will allow you to witness the impact on parameters, and therefore on match selection.

**Comment by SmitaKumar** [comment]
Makes complete sense. Didn't realize that it was using parameters from the table dealing with sizes 16KB to 128KB when a 16KB dictionary is enabled.

Thanks a lot for your response
