### ISSUE TITLE
help in debugging 'Decompression error: Corrupted block detected'

### ISSUE THREAD

**Issue by smanikim** [facebook/zstd#2014]
We do create millions of zstd compressed files. But recently, I started to get into  occasional 'Decompression error: Corrupted block detected' like once in 10-12 days for 1 file. I tried to read stuff around like open issues and tried debugging where I checked system issues around that time but I don't find anything. 
File were not very small of single frame like I see in issues earlier. Example in one of case, It was of 40 MB uncompressed which became 22 MB compressed later.

Can someone points me how can I debug what could be causing it

**Comment by Cyan4973** [comment]
That's a pretty difficult topic.

From our experience, detectable corruption errors typically come from 3 sources. In decreasing frequency order :
- Software issue : one _user_ software, somewhere in the pipeline, has a bug, with the most typical one being truncating data. Buffer corruption is also in this list, with multi-threading increasing the odds of such thing happening. The most common bugs tend to happen more than once every 10 days. But some rare subtle ones may require many concurrent triggering conditions, and manifest only once in many millions cases.
- Hardware issue : so this is much rarer, but at the scale of gigantic datacenter, it is bound to happen from time to time. What's very helpful in this case is to know which system generated the data. When the corruption errors consistently come from the same hardware unit, then it's a pretty good sign.
- Library issue : we have not had to face such issue in recent time, but yes, it's always a possibility. If the library has a bug, then it will generally show up in a wide range of systems and applications (since it's integrated basically everywhere). This is a pretty good sign that something is wrong in the library itself.

Presuming you have no instrumentation and rely purely on the content of the frame to determine a potential cause, this is a very hard case scenario, with low prospects of identifying a root cause.

Something possible is to enable and store decompression logs, in order to determine where exactly the decompression process fails. To do that, one needs to compile `zstd` from source, adding `DEBUGLOG=5` to the list of parameters. Higher levels will increase the verbosity of logs, but level 5 should be enough to determine which block exactly fails.

Knowing where the decompression process fails can be helpful, especially when it's close to the beginning or the end of the frame. But sometimes, it's simply not enough to determine a cause.

An important tool to debug corruption is an ability to track provenance and (sometimes) transfer of files. Without a dedicated tool for this goal, it's still possible to add watermarks to compressed frames, by appending [skippable frames](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#skippable-frames), which are allowed to contain any custom content, so adding an "origin" field there can prove valuable at debug time.

The issue being : it must be already there to be useful. This won't help for your _current_ corrupted frames.

**Comment by smanikim** [comment]
I looked from hardware and software issue.  Given the nature of issue and its occurence, I can not confirm as well as deny possibility.  Just to add: We did not change anything in terms of hardware/zstd version etc. This issue was not happening 6-7 weeks ago but started occurring lately.

My build ran with below params but it did not change anything in decompression logs.

> cc -I../lib -I../lib/common -I../lib/compress -I../lib/dictBuilder -DXXH_NAMESPACE=ZSTD_ -I../lib/legacy -DZSTD_MULTITHREAD    -DDEBUGLOG=5 -DZSTD_LEGACY_SUPPORT=5 -O3 -DBACKTRACE_ENABLE=0  -pthread     ../lib/common/debug.c ../lib/common/entropy_common.c ../lib/common/error_private.c ../lib/common/fse_decompress.c ../lib/common/pool.c ../lib/common/threading.c ../lib/common/xxhash.c ../lib/common/zstd_common.c ../lib/compress/fse_compress.c ../lib/compress/hist.c ../lib/compress/huf_compress.c ../lib/compress/zstd_compress.c ../lib/compress/zstd_compress_literals.c ../lib/compress/zstd_compress_sequences.c ../lib/compress/zstd_double_fast.c ../lib/compress/zstd_fast.c ../lib/compress/zstd_lazy.c ../lib/compress/zstd_ldm.c ../lib/compress/zstd_opt.c ../lib/compress/zstdmt_compress.c ../lib/decompress/huf_decompress.c ../lib/decompress/zstd_ddict.c ../lib/decompress/zstd_decompress.c ../lib/decompress/zstd_decompress_block.c ../lib/dictBuilder/cover.c ../lib/dictBuilder/divsufsort.c ../lib/dictBuilder/fastcover.c ../lib/dictBuilder/zdict.c ../lib/legacy/zstd_v05.c ../lib/legacy/zstd_v06.c ../lib/legacy/zstd_v07.c zstdcli.o util.o timefn.o fileio.o benchfn.o benchzstd.o datagen.o dibio.o  -o zstd -pthread


logs are something like 

$zstd -vvv -d in.tar.zst
*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
in.tar.zst           : 5 MB...     in.tar.zst : Decoding error (36) : Corrupted block detected


$ zstd -vvv -l in.tar.zst
*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
in.tar.zst
# Zstandard Frames: 1
Window Size: 2.00 MB (2097152 B)
Compressed Size: 22.57 MB (23668400 B)
Check: XXH64

it actually enabled build debug logs. Do you think I compiled it right way

**Comment by smanikim** [comment]
Also, I do see `--test` argument in CLI which checks integrity of file. Can I enable integrity check without adding performance overhead in compression step itself

**Comment by smanikim** [comment]
I used zstd-jni to debug it too. I am getting "-20" size from decompressStream

**Comment by smanikim** [comment]
@Cyan4973 could you please suggest

**Comment by Cyan4973** [comment]
These symptoms seem consistent with hardware failure scenario.
That being said, I'm much too far away from the action to give any kind of definitive statement.

> it actually enabled build debug logs. Do you think I compiled it right way

I haven't seen any debug output in your traces. I guess it's not enabled.
The option is actually called `DEBUGLEVEL`, so ` -DDEBUGLEVEL=5` should be present on the compilation line.

> I do see --test argument in CLI which checks integrity of file.

It only checks if a compressed file can be decompressed correctly.

**Comment by smanikim** [comment]
"-DZSTD_MULTITHREAD -DDEBUGLOG=5 -DZSTD_LEGACY_SUPPORT=5" seems present in above command.   How do you usually enable debug in zstd build

**Comment by Cyan4973** [comment]
`-DDEBUGLEVEL=5`
