### ISSUE TITLE
Compressing Generated Wordlists [2GB to 134KB via nanozip]

### ISSUE THREAD

**Issue by deepseek** [facebook/zstd#2034]
A simple method to test the robustness of zstd dictionary-based compression is to test compressing on a generated wordlist.
- The main issue is that zstd which is a more advanced and complex compressor can't detect a simple pattern like repetitive letters of a generated wordlist, even after training a zstd dictionary.

- It seems that Nanozip have better heuristics and flexible enough filters to apply delta filter on such generated wordlist.
```
crunch 6 6 abcdefghijklmnopqrstuvwxyz > wordlist.txt
```

- Zstd takes 8 seconds and compressed into 178mb using default settings 
- [Nanozip](https://archive.org/compress/nanozip.net/formats=ZIP&file=/nanozip.net.zip) takes 18 seconds and compressed into 135**kb** using nz_optimum2

**Comment by terrelln** [comment]
> A simple method to test the robustness of zstd dictionary-based compression is to test compressing on a generated wordlist.

I wouldn't expect zstd dictionaries to help here. Dictionary compression is useful for compression of small data. This wordlist is a large file of sorted words, so I wouldn't expect dictionaries to help.

This is a very particular file. It can be compressed to `6 6 abcdefghijklmnopqrstuvwxyz` plus the size of a minimal worlist generator, which could be very small.

Unfortunately, the zstd format does not support delta transforms, or taking the delta of the literal after a match. Since the format is fixed, we can't add it.
