### ISSUE TITLE
optimize  ZSTD_getMatchPrice()

### ISSUE THREAD

**Issue by jinfeihan57** [facebook/zstd#2060]
In file zstd_opt.c 
U32 const matchPrice = ZSTD_getMatchPrice(offset, pos, optStatePtr, optLevel);
if we set U32 const matchPrice = 100; 
Compression speed will increase almost 40% in some cases.
use  matchPrice = ZSTD_getMatchPrice(offset, pos, optStatePtr, optLevel):
"size"	 		11752960
"compress_size" 	3521696
"compress_time" 	7523961700
"decompress_time"	95490700
use matchPrice = 100:
"size"	 		11752960
"compress_size" 	4319703
"compress_time" 	5472228200
"decompress_time"	116110400
But the compression rate drops a lot, so we think that optimizing the ZSTD_getMatchPrice function will increase the compression speed without affecting the compression ratio.

**Comment by Cyan4973** [comment]
The experiment establishes that `ZSTD_getMatchPrice()` uses a sizable portion of cpu time during compression. This function is only present in `zstd_opt.c`, and therefore is used for `btopt` and stronger strategies.

One thing that's missing though is what is the exact compression level or strategy used. That's because this function is different, and therefore has a different computation cost, depending on being run at `btopt` or `btultra` strategy. This can make a large difference.

Obviously, `zstd_opt` needs this function to achieve its target compression ratio, so disabling it is not a solution. There might be ways to make `ZSTD_getMatchPrice()` faster, and maybe some simplification can be done, just be aware that any change to the output of this function will impact the compression ratio, so it's a tricky balance.
