### ISSUE TITLE
[QUESTION] Effects of writing ZSTD_e_end on a buffer.

### ISSUE THREAD

**Issue by senior7515** [facebook/zstd#2061]
Hello, 

I have a fragmented buffer input and output buffers both of different fragment sizes. Think 1GB file split up in chunks. Imagine that the input is 4K chunks, and the output is composed of 128KB chunks.

I want to understand the impact of calling 

```ZSTD_compressStream2(ctx, &out, &in, Zstd_e_end)``` 

Would have on the output chunk. Let me give details. 

The algorithm for streaming is roughly 

```python

for each chunk in input_chunks: # list of say 10 chunks, each chunk is 4KB
    do:
         allocate output chunk
         mode = zstd_e_continue
         if final chunk in input stream:
                 mode = zstd_e_end
         zstd_compressStream2(ctx, out, in, mode)
```

The question is, will there be a circumstance in which calling `ZSTD_compressStream2` with `ZSTD_e_end` require extra bytes to perhaps write a footer of sorts? 

Note that I am not using the checksumming option with the streaming compressor.

**Comment by senior7515** [comment]
I tested, and it doesn't add anything to the payload. 

please feel free to close. but will leave open just to confirm w/ a simple `yes` or `no` thank you!

**Comment by Cyan4973** [comment]
I'm not too sure what is the comparison with.

Calling repetitively `ZSTD_compressStream2(ctx, &out, &in, Zstd_e_end)` digesting small inputs is basically equivalent to calling `ZSTD_compressCCtx()` with the same series of inputs. Each invocation generates a fully formed and independent frame in the output buffer.

Compared to `ZSTD_compressStream2(ctx, &out, &in, Zstd_e_continue)`, I would expect the final compression ratio to be much worse. But of course, the use case is different, since `Zstd_e_continue` would create a single continuous frame, hence forbidding random access of a single block in the middle of the frame.

Now, if the comparison is with `ZSTD_compressCCtx()`, it should end up being equivalent, if not identical.

**Comment by senior7515** [comment]
This makes sense. Thank you. 

Last question is, can a compressed buffer, that was compressed using the `SSTD_comrpessStream2` be decompressed with `ZSTD_decompress`?

**Comment by Cyan4973** [comment]
Yes
