### ISSUE TITLE
Custom dictionary: "error 11 : Allocation error : not enough memory"

### ISSUE THREAD

**Issue by klauspost** [facebook/zstd#2174]
When creating a custom dictionary I ran into something weird where I get the error above when trying to use it.

It is sort of clobbered together from a 'header' from another file and a custom payload, though I can't see why that would be an issue.

**To Reproduce**

* Ungz this dictionary: [dict-custom.gz](https://github.com/facebook/zstd/files/4677057/dict-custom.gz)
* Use command: `zstd -D dict-custom file.txt`
* zstd returns: `zstd: error 11 : Allocation error : not enough memory`. A 0 byte file is left behind.

**Expected behavior**

zstd should compress with the dictionary.

**Desktop (please complete the following information):**
 - OS: Windows 10, 64 bit.
 - Version: `zstd command line interface 64-bits v1.4.5, by Yann Collet`
 - Compiler: Released binary

**Additional context**

As I said this is a hacked together dictionary, but AFAICT it should work. If I truncate the dictionary it works.

I tried creating a bigger dictionary with `zstd`, but that works.

**Comment by Cyan4973** [comment]
Tested : `zstd -D dict-custom file.txt`

```
../lib/compress/zstd_compress.c: ZSTD_compress_insertDictionary (dictSize=131252)
../lib/compress/zstd_compress.c:2895: ERROR!: check dictMaxSymbolValue < maxSymbolValue failed, returning ERROR(dictionary_corrupted): dict fse tables don't have all symbols
../lib/compress/zstd_compress.c:3019: ERROR!: forwarding error in ZSTD_checkDictNCount(offcodeNCount, offcodeMaxValue, ((offcodeMax)<(31) ? (offcodeMax) : (31))): Dictionary is corrupted:
../lib/compress/zstd_compress.c:3395: ERROR!: forwarding error in dictID: Dictionary is corrupted: ZSTD_compress_insertDictionary failed
```

The clobbered dictionary does not seem valid.

We could probably improve the error message.

**Comment by klauspost** [comment]
@Cyan4973 Compare it to this dictionary:
[dict-custom-shorter.gz](https://github.com/facebook/zstd/files/4677837/dict-custom-shorter.gz)

The only difference is after the repeat codes and a shorter dictionary.

Unless there is an un-documented restriction that offset codes must be able to reference all parts of the dictionary this should be perfectly valid.  Is there such a check?

**Comment by klauspost** [comment]
I am generating my own dictionaries. Since I am only interested in the content of the dictionary for now, I am just slapping the same 'header' in front from a dictionary generated by zstd.

If I read the docs correctly I should be able to replace the dictionary content with anything I want. But I get this error if the content is longer than the dict I grabbed the header from.

**Comment by Cyan4973** [comment]
> Unless there is an un-documented restriction that offset codes must be able to reference all parts of the dictionary this should be perfectly valid. Is there such a check?

It's not a format restriction, 
but there is indeed such a check in the reference encoder.

What probably happens is this scenario : 
- you define your own custom dictionary, it's > 128 KB
- the reference encoder notices that the first block (128 KB) + dictionary can lead to offsets > 256 KB.
- It checks offset codes in the dictionary, to ensure that, if such a situation ever happens, it can blind-trust the dictionary's tables to represent the offset. It cannot, because the offsets were created for a different dictionary size (110 KB + 128 KB < 256 KB).
- Consequently, it fails to load the dictionary

I don't think it's a spec problem. The spec doesn't forbid that.

It's more an implementation limitation. This situation would not happen when using `ZDICT_finalizeDictionary()`, because it would notice the size of the dictionary, and increase the range of offset codes accordingly. Consequently, this limitation has never been a problem up to now.

We could probably fix it, in a number of ways, from early discarding to later optimization, depending on how much runtime cpu resources we want to spend on the topic.

**Comment by klauspost** [comment]
From a *decoder* side the dictionary should be perfectly valid (it is according to the spec) and there is no reason it shouldn't be able to decode a frame with this dictionary. 

From decoding perspective there are plenty of options, either the first block having an offset table or it could use a predefined table, or the inaccessible parts are simply never being used.

The fact that some values are out of range should only really concern the encoder, if at all. There shouldn't really be any reason it needs to be able to access everything in the dictionary, but I guess the encoder is free to reject whatever dictionary it wants.

**Comment by klauspost** [comment]
OK, it seems this is only an issue on the encoding side - the decoder doesn't complain.

**Comment by terrelln** [comment]
It should be easy for us to allow dictionaries with histograms with 0 weighted values on the encoder size. We have the ability to validate tables now, so we can use that while loading dictionaries.

However, I'd generally recommend making all literal lengths + match lengths + offsets <= 128 KB + dictionary content size representable.
