### ISSUE TITLE
Out-of-bounds access reported by Coverity in ZSTD_estimateSubBlockSize_sequences

### ISSUE THREAD

**Issue by vnair81** [facebook/zstd#2213]
**Describe the bug**
Out-of-bounds access reported by Coverity in ZSTD_estimateSubBlockSize_sequences

**To Reproduce**
Please refer flow flagged by Coverity in the following video:
[Out_of_Bounds_Access_in_ZSTD_estimateSubBlockSize_sequences.mov.zip](https://github.com/facebook/zstd/files/4814143/Out_of_Bounds_Access_in_ZSTD_estimateSubBlockSize_sequences.mov.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Win 10 64-bit
 - Compiler: Visual Studio 2017

**Comment by terrelln** [comment]
Thanks for the report @vnair81!

This bug should be impossible to trigger in practice, because the condition is checked quite a ways previous in the code when selecting the encoding type. We shouldn't select `set_basic` as the encoding type when that condition fails.

However, I'd still consider this a bug, and we will fix it.
