### ISSUE TITLE
Question: Choice of Hash Function

### ISSUE THREAD

**Issue by AKJ7** [facebook/zstd#2224]
Hello,

i was reading the source code and noticed that you use the xxhash as hash function, and couldn't help but wonder why. My question comes from the fact that a simple multiplicative hash function like

`size_t my_hash_function(const char* value, size_t size) {
    size_t hash = SOME_SEED;
    for (size_t counter = 0; counter < size; ++counter) {
        hash = SOME_PRIME * value[counter] + hash;
    }
    return hash;
}`

will be faster than the xxhash function (i haven't benchmarked as i do not have an available computer near me. The xxhash does something similar but 4 times, then rotates and xor and and ...).

What could be wrong with the hash function from above? (PHP uses the same hash function internally too, with PRIME _NUMBER=33).

Thanks

**Comment by terrelln** [comment]
I'll let @Cyan4973, author of xxhash, answer this one.

**Comment by Cyan4973** [comment]
There are 2 parts to this question, hash quality, and hash speed.

For hash quality, the goal is to prevent correlations between input and output, so that any change in the input has exactly 1 in 2^32 chances (for a 32-bit hash) to generate a collision, aka an undetected corruption event. This is more complex to achieve than it sounds, and the formula proposed in first post doesn't reach this objective (one can trivially note that only lower input bits contribute to lower output bits, so changing 2 lowest bits will trigger a collision. Also, upper bits of input bytes do not contribute to lower bits of the output, which mechanically increases probability of collisions when upper bits are modified. etc.)

But I guess the more important question is about the speed. And in below sentence : 

> My question comes from the fact that a simple multiplicative hash function like (...) 
> will be faster than the xxhash function (i haven't benchmarked 

I can only suggest you to benchmark the proposed hash function, and compare it with `XXH64`.
You will likely be surprised.

**Comment by AKJ7** [comment]
@Cyan4973 Thanks for your answer.
