### ISSUE TITLE
Zstd multithreaded output can depend on number of threads

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#2327]
**Describe the bug**
As reported by @animalize in Issue #2238:

When using ZSTD_e_end end directive and output buffer size >= ZSTD_compressBound() the job number is calculated by ZSTDMT_computeNbJobs() function. This function produces a different number of jobs depending on `nbWorkers`:

https://github.com/facebook/zstd/blob/b706286adbba780006a47ef92df0ad7a785666b6/lib/compress/zstdmt_compress.c#L1243-L1255

**Expected behavior**
The output of zstd multithreaded compression must be independent of the number of threads.

**Fix**
* [ ] Make `ZSTDMT_computeNbJobs()` independent of `nbWorkers`.
* [ ] Add a fuzz test that checks that the output of multithreaded zstd is always independent of the number of threads.

**Workaround**
If you need to work around this bug, don't start your streaming job with ZSTD_e_end. Pass at least one byte of input with ZSTD_e_continue before calling ZSTD_e_end, or ensure your output buffer is `< ZSTD_compressBound(inputSize)`.

**Comment by Cyan4973** [comment]
It's a shortcut to say that multithreaded `zstd` does not depend on nb of threads.

Actually, the feature supported is that _streaming_ multithreaded `zstd` does not depend on nb of threads
(and that's what is used by the `zstd` CLI).

This definition makes it possible to consider another potential fix : 
do not employ the one-pass shortcut for `ZSTD_e_end ` when `nbWorkers >= 1`,
since it's the delegation to the one-pass mode which triggers this issue.

This could be less disruptive than trying to adapt the single-pass MT compressor,
which was never designed to offer this guarantee.

Another (potentially positive) side effect is that it would guarantee that streaming multithreaded compression is _always_ non-blocking, since it would no longer delegate to the blocking mode.

**Comment by animalize** [comment]
> Another (potentially positive) side effect is that it would guarantee that streaming multithreaded compression is always non-blocking, since it would no longer delegate to the blocking mode.

I once wanted to propose adding a `ZSTD_compressStream3()` function, that is always blocking in multithreaded compression.

If the caller keeps checking the non-blocking progress, it's very inconvenient.

**Comment by terrelln** [comment]
> This could be less disruptive than trying to adapt the single-pass MT compressor,
> which was never designed to offer this guarantee.

Yeah, that is probably easier. I had forgotten that all the jobs in the single pass MT compressor needed to be launched at once.

> I once wanted to propose adding a ZSTD_compressStream3() function, that is always blocking in multithreaded compression.

Generally, the way people write streaming compression loops, it shouldn't be terribly inconvenient to not make maximal forward progress. If we were to add something like this, it wouldn't require a new API. We'd probably just need to add a compression parameter to control it. But, I don't currently see a great need for it.
