### ISSUE TITLE
skippable blocks for streaming compression

### ISSUE THREAD

**Issue by AbdulrahmanAltabba** [facebook/zstd#2336]
I have a scenario where I continuously receive streamed data and I want to compress this data in multiple frames with a pre-given FrameSize. I am using the C-API function ZSTD_CCtx_setPledgedSrcSize() for this purpose. The problem arise when the data stream stops or requests closing the file and starting a new file in a time point when the the current frame size is not yet reached. I can't close the frame in this case. I thought I could do padding with meaningless data till the end of the frame. However, this would not be clean when decompressing the file. If one could use something like skippable blocks, then I could fill the rest of the frame with these and the decompressor would skip them automatically. This could solve my problem. Otherwise I would appreciate any help to overcome this issue.

Thank you

**Comment by terrelln** [comment]
> I am using the C-API function ZSTD_CCtx_setPledgedSrcSize() for this purpose

Why are you setting a pledged source size when it might not be accurate? Wouldn't a better solution be to not set the pledged source size, then you can have a frame of whatever size you please?

If you need to know the source size on the decompression side, you could communicate it out-of-bad. That would allow you to over/under-estimate because you can have a protocol that adjusts it.

**Comment by pizzard** [comment]
Hello, I'm a colleague of Abdulraman. 
I need to explain a bit more context of what we want to do to see why we made the choices we made, because we have a big XY problem here.

Our problem is that a embedded device will just continuously receive data, stream compresses it and writes it to the device. At any point in this transmission it will be turned off, or it rotates the file periodically.
We use stream compression in order to manage the load, as our previous version stored the block into a buffer and compressed it at once. 

When reading the file, the offending file is bigger than we can load at once and we to start loading at a given position in the file. So we split the file into frames of manageable size and with the non.stream compression api we have the size and then quickly index all frames, and can then jump into the file at the desired point and only decompress the frame we need. 

When we now switch this to stream compression + pledged sizes the same thing almost works. The problem is that in case of a power cut or for the last frame within the file, the pledged size does not work out. This will of course corrupt the state of the decompressor, but as the file is over anyway, I don't mind anyway. 

The annoying thing here is: although all data up to the premature end are complete fine an technically readable, my colleague was not able to convince zstd to decompress them and give them out. If we don't pledge a size and and just truncate the file, one gets a error "unexpected end of input" but all bytes up to this point are decompressed and given back to us, which is fine. One can the destroy the broken decompressor, create a new one and all is fine. When we pledge a size, the contents of the last frame are lost and not given back before the error occurs (although they can be decompressed). As we did not want to loose a whole frame, we came up with some creative ideas. If we could add skippable blocks, we could basically detect an wrong pledged size and add skippable blocks with zeros to fill them up to the pledged size to make the decompressor happy enough to give us the content up to that point (ideally when writing the file).

So the our current understanding is: 
* If i just truncate a zstd file, I can get the contents up the truncation point (or at least very close to this point, at least all blocks before the truncated block) followed by an error.
* if I pledge a size for the frame, I can't get the contents of the last frame which is truncated at all, despite all information being present to decode these contents.

Is that correct? And which workaround or other measures can be done to make it possible to extract data from truncated frames with pledged size? 

If it was possible to make the behaviour for pledged size equal to the normal behaviour, just giving all bytes to the truncation point (as far as possible) followed by an premature end of file error, all our problems would be solved.

**Comment by pizzard** [comment]
fter further investigation we found our analysis to be incorrect. we will look at pledged size further to see if they can work.

**Comment by pizzard** [comment]
A I forgot to report. Setting the pledged size actually works as expected, if you use it correctly. Having blocks with larger pledged  size than actual content decompress correctly to the end and then throw an unexpected end of input error (which can be caught and handled). So this can be closed.
