### ISSUE TITLE
[dev] Build configurations don't appear to be totally respected

### ISSUE THREAD

**Issue by senhuang42** [facebook/zstd#2382]
**Describe the bug**
Build configurations don't appear to be totally respected

**To Reproduce**
Bugged revision:
```
git checkout dev
make clean && make -j MOREFLAGS="-DDEBUGLEVEL=9"
./zstd LICENSE -f
```
Working revision:
```
git checkout 8a453a34c57d2097bf499fb81446e90636851f86 # commit before PR #2373 
make clean && make -j MOREFLAGS="-DDEBUGLEVEL=9"
./zstd LICENSE -f
```

**Expected behavior**
I expect a lot of debug info to be printed in both cases, but in the `dev` checkout, nothing is printed other than 1 line of compression summary. I'm not sure if I'm supposed to be using `make` differently after #2373 to get the configuration changes propagated correctly.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by Cyan4973** [comment]
Try : 
`make -j DEBUGLEVEL=9`

This is now the preferred way to set `DEBUGLEVEL`.

The problem with previous construction is that the build macro `DEBUGLEVEL` is being redefined, since there are 2 different sources trying to set its value, one through regular `Makefile` predefined flags, and the other through `MOREFLAGS`. And unfortunately, the predefined `-DDEBUGLEVEL=0` is present on the command line _after_ the one set through `MOREFLAGS`, so it gets the last word.

This effect is visible by adding `V=1` to display the exact command used.

```
make -j MOREFLAGS="-DDEBUGLEVEL=9" V=1
(...)
cc -O3 -DBACKTRACE_ENABLE=0 -DDEBUGLEVEL=9 -DXXH_NAMESPACE=ZSTD_ -DDEBUGLEVEL=0 -DZSTD_MULTITHREAD -DZSTD_GZCOMPRESS -DZSTD_GZDECOMPRESS -DZSTD_LZMACOMPRESS -DZSTD_LZMADECOMPRESS -DZSTD_LZ4COMPRESS -DZSTD_LZ4DECOMPRESS -DZSTD_LEGACY_SUPPORT=5  -c -MT obj/conf_5867fc23cc5b51e6a5152152f9bc2124/timefn.o -MMD -MP -MF obj/conf_5867fc23cc5b51e6a5152152f9bc2124/timefn.d -o obj/conf_5867fc23cc5b51e6a5152152f9bc2124/timefn.o timefn.c                                              CC obj/conf_5867fc23cc5b51e6a5152152f9bc2124/util.o
(...)
```

**Comment by senhuang42** [comment]
Oh great - thanks for the pointer!
