### ISSUE TITLE
Clarifications for the format specification

### ISSUE THREAD

**Issue by fleon-psi** [facebook/zstd#2402]
Hi, 

I have questions about the Zstandard format, which I'm not sure about after reading format documentation:
https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md

1. Is block size limit 128 KB or 128 KiB, so 128000 bytes or 128 * 1024 bytes?
2. Similarly, is max frame size 8 MB or 8 MiB and is standard implementation enforcing this limit?
3. What is maximum number of character repeats (Block_size value) for RLE_Block, is it max for the 21 bit field (2^21-1) or Block_maximum_size?

Thank you in advance for any clarifications!

**Comment by Cyan4973** [comment]
> Is block size limit 128 KB or 128 KiB, so 128000 bytes or 128 * 1024 bytes?

128 * 1024 bytes

> What is maximum number of character repeats (Block_size value) for RLE_Block, is it max for the 21 bit field (2^21-1) or Block_maximum_size?

`Block_maximum_size`

> Similarly, is max frame size 8 MB or 8 MiB and is standard implementation enforcing this limit?

There is no max frame size.

You might be referring to the maximum `Window_Size` ?
In which case, there is no _practical_ maximum (it's in the hexabyte range), but there is a _recommendation_ to refrain using more than 8 MB (as in 8 * 1024 * 1024) for `Window_Size` as it (generally) translates into a direct memory tax for the decoding side.

There is nothing enforcing this limit, since it's merely a recommendation, not a maximum.
However, note that in the current reference CLI, the decompression routing will, by default, refuse to decode frames specifying a `Window_Size` larger than 128 MB. This is meant to protect the host from unreasonable memory requirements. This limit can be overriden with a manual parameter, like `--long=30` for example to accept `Window_Size` up to 1 GB.

**Comment by fleon-psi** [comment]
Thank you!, Yes I was asking about Window_Size, everything is now clear.
