### ISSUE TITLE
Parallel build of v1.4.8 can fail

### ISSUE THREAD

**Issue by xkszltl** [facebook/zstd#2436]
**Describe the bug**

Could be race condition:
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/5203025/102713623-9396dd00-4304-11eb-9773-71f83b7d525d.png">

**To Reproduce**

`make almost -j36`

**Desktop (please complete the following information):**
 - OS: CentOS 7 / Ubuntu 18.04
 - Compiler: gcc-9/gcc-8
 - Other relevant hardware specs: 36-thread Xeon
 - Build system: Makefile

**Comment by Cyan4973** [comment]
> Could be race condition:

most likely

**Comment by Cyan4973** [comment]
The reported issue seems to happen while compiling `minigzip` from the `zlibWrapper` sub-directory.
`libzstd.a` is probably being overwritten at the exact moment where it's needed to link `minigzip`.
But the faulty overwrite operation itself happens elsewhere.

I presume it happens while compiling `/tests` in parallel,
as tests require a specific version of `libzstd.a` which is specially built with debug and `assert()` symbols.
While compilation and build of `libzstd.a` itself safely happens in a separate directory,
the final stage, linking the resulting `libzstd.a`, overwrites the existing link in `lib/`.
I presume that's where an issue could happen.

These are all educated guesses, as I'm unable to reproduce the scenario, presumably due to a lack of parallel cores on my local system.

**Comment by Cyan4973** [comment]
In #2438, there is an attempt to mitigate this situation by giving less reasons for a "parallel `libzstd.a` update" scenario to happen.
While this seems a step in the right direction, I have to underline that I can't test its effectiveness directly, since parallel build never fails on any on my build systems, even those with a large nb of cores.
Hopefully, it will help for your build setup.

**Comment by xkszltl** [comment]
I tried to use cmake instead and that works much better (and I can use ninja!).
There're also several failures in 1.4.8 related to emcc and docker without sudo, which probably comes from contrib.
CMake script hasn't build those contrib so that happen to skip those issues for me as well.

**Comment by xkszltl** [comment]
I would suggest to consider cmake (with as less custom script as possible) as a makefile replacement.
Personally I used to love makefile because it requires less dependency, but it is now available in more and more places, probably not less than make.
That would significantly reduce race condition since the command is auto-generated.
