### ISSUE TITLE
non-deterministic test failures zstd 1.4.9 on i686-linux

### ISSUE THREAD

**Issue by llebout** [facebook/zstd#2528]
Hello!

Over at GNU Guix we are getting non-deterministic test failures for zstd 1.4.9 on i686-linux.

log:
```
roundTripTest: datagen -g8M  | zstd -v19 -T0 --long | zstd -d19 -T0 --long

*** zstd command line interface 32-bits v1.4.9, by Yann Collet ***
Note: 32 physical core(s) detected 
zstd: error 11 : Allocation error : not enough memory 
zstd: /*stdin*\: unexpected end of file 
Files tmp1 and tmp2 differ
make[1]: *** [Makefile:329: test-zstd] Error 1
```

Full log: https://ci.guix.gnu.org/build/378399/log/raw

To reproduce:
- Install GNU Guix (https://guix.gnu.org/manual/en/html_node/Binary-Installation.html#Binary-Installation)
- Run: `guix pull --commit=6f873731a030dd7ecbd8a5e756b38b26306f6966`
- Run: `guix build --system=i686-linux -K zstd@1.4.9` (few times, until the non-deterministic error is met)

Thanks

**Comment by Cyan4973** [comment]
It's a test issue.

32-bit operating systems have a limited amount of addressable memory available.

This test will attempt to compress 8 MB in streaming + multithreading mode.
And since it detects 32-cores, it will attempt to allocate 32 threads.
Then it will start compression, 
and since it has no idea how much data it's going to attempt to compress (streaming mode)
it will bet that it's "probably large", and reserve resources accordingly.
At level 19, we are looking at a ~100 MB+ budget for each compressing thread.

Thankfully, it should only instantiate one compressing thread, since 8 MB is not large enough to need more.
But that's still a sizable memory budget, that must be allocated in one block,
and the previous allocation for 32 threads, each one requiring a stack, might have fragmented address space more than necessary,
to the point that there may be no longer any free block large enough for the workspace of this one working thread.

So now that we have plausible explanation, what can be done about it ?
1) Ignore this test. It's a just test error. Disable it.
2) Change the test, so that it passes. For example, use a fixed nb of threads, like `-T4`.
3) Update the rule regulating `-T0`, determining automatically a nb of threads based on present nb of cores. Make it conditional for 32-bit systems, select a limit for this case (slightly more complex, will take time).
4) Update the thread-pool policy to allocate new threads only when needed, instead of up front (definitely more complex, will take even more time).

**Comment by zimoun** [comment]
@Cyan4973 Investigating the bug to fix it for the next Guix release, I note that on 32bits (`i686`), it happens only for the level 19.  I mean, the test suite passes for any other values, say 16 or 22.  I have not investigated to establish a range.

**Comment by vcunat** [comment]
We ran into a _real-life_ problem that i686 zstd tool (1.4.9) was bailing reliably when building the kernel.  (linked above)  I believe we have no special settings around this.
```
  ZSTD22  arch/x86/boot/compressed/vmlinux.bin.zst
zstd: error 11 : Allocation error : not enough memory 
```
Our build machines often have many cores; my manual testing was done on 16 and 32 logical cores.  The build machines always run a 64-bit kernel in practice, but for consistency the i686 builds are done in a way that can be performed on a 32-bit-only machine, by default.  (We worked around it by switching default back to xz on 32-bit platforms, at least for now.)

_Greetings to our Guix relatives :-)_

**Comment by terrelln** [comment]
@vcunat try this patch to the kernel

```
diff --git a/arch/x86/boot/compressed/Makefile b/arch/x86/boot/compressed/Makefile
index e0bc3988c3fa..c150fac9dde9 100644
--- a/arch/x86/boot/compressed/Makefile
+++ b/arch/x86/boot/compressed/Makefile
@@ -131,7 +131,7 @@ $(obj)/vmlinux.bin.lzo: $(vmlinux.bin.all-y) FORCE
 $(obj)/vmlinux.bin.lz4: $(vmlinux.bin.all-y) FORCE
        $(call if_changed,lz4)
 $(obj)/vmlinux.bin.zst: $(vmlinux.bin.all-y) FORCE
-       $(call if_changed,zstd22)
+       $(call if_changed,zstd)

 suffix-$(CONFIG_KERNEL_GZIP)   := gz
 suffix-$(CONFIG_KERNEL_BZIP2)  := bz2
```

This changes the kernel compression level from 22 to level 19, which uses much less memory. Please let me know if it works.

**Comment by vcunat** [comment]
Success, on both of the same builder machines.  So perhaps we'll use this approach instead.

**Comment by terrelln** [comment]
Glad to hear it! I think I will put up a patch to the LKML that either switches to zstd level 19, or falls back to level 19 if compression fails.

**Comment by vcunat** [comment]
Falling back if compression fails might be a bit too non-deterministic for the default approach (from my point of view at least).

**Comment by ghost** [comment]
If memory is not enough, can it flexibly reduce the number of active threads.

**Comment by vcunat** [comment]
To be clear, in our case there was always enough RAM, so it was just the 32-bit binary limitations (2G or how much is it for Linux in practice).

**Comment by Millak** [comment]
As another data point I did not run into this issue on Guix when building on my single-core powerpc iBook G4, but when the test is modified to use compression level 22 I actually went OOM. For the record I'm running with 1.5GB of RAM and 2.5GB of swap, 1GB of which is zram.

roundTripTest: datagen -g8M  | zstd -v22 -T0 --long | zstd -d22 -T0 --long

*** zstd command line interface 32-bits v1.4.9, by Yann Collet ***
Warning : compression level higher than max, reduced to 19
Note: 1 physical core(s) detected
zstd: error 11 : Allocation error : not enough memory
zstd: /*stdin*\: unexpected end of file
Files tmp1 and tmp2 differ
make[1]: *** [Makefile:329: test-zstd] Error 1

**Comment by vcunat** [comment]
For reference, I'm still getting the issue with zstd 1.5.0, i.e. this^^ PR did not solve it for me.
