### ISSUE TITLE
No progress counter when decompressing into a pipe

### ISSUE THREAD

**Issue by fleaz** [facebook/zstd#2556]
**Describe the bug**
Hi,
we use zstd for the database dumps in our development environment at work and normaly one would get this Megabyte counter which shows how much data has already been decompressed which is quite handy for large dumps because one can estimate the remaining time. Recently this progress counter disappeared. Everything is still working fine but the progress bar was a nice addition.

I tried to bisect when this problem occurred and with 1.4.4 (official Ubuntu Focal repo) I still see the progress counter, but with 1.4.8 (ondrej ppa) or directly building the dev branch myself, the counter is gone.

Best,
Felix

**To Reproduce**
1. Decrompress a SQL dump with a pipe directly into the `mysql` cli tool
```
zstd -d -c dump.sql.zst | mysql my-awesome-database
```

**Expected behavior**
I want to see the counter showing me how much data has already been decompressed.

**Screenshots and charts**
![Screenshot_2021-03-25_12:00:35](https://user-images.githubusercontent.com/2489598/112462784-bef4f200-8d61-11eb-875d-c6dd96e6469e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Focal in a Container

**Comment by Cyan4973** [comment]
I presume that's because the output is pushed into `stdout`.
If it was pushed into a file instead, the activity notification counter would still be present

This is likely the consequence of a refactoring of `zstd` CLI output
which fixed a nb of edge cases regarding its display output.
And this resulted in the notification being disabled by default when `zstd` is used in combination with `stdout`.
I believe it's the correct default, as otherwise, the display can get messed up, with both `stdout` and `stderr` being printed interleaved,
or when multiple programs want to output something to display.

What's missing though is an ability to re-enable it on demand.
I would expect `-v` to achieve that, but it doesn't (it only prints the final result).
So either fix that, or support a new command flags, such as `--progress` (since we already have `--no-progress`).

**Comment by senhuang42** [comment]
Addressed in #2595.
