### ISSUE TITLE
Better decompression buffer size for small content and high compression level.

### ISSUE THREAD

**Issue by mgautierfr** [facebook/zstd#2688]
**Is your feature request related to a problem? Please describe.**

At [kiwix](https://github.com/kiwix)/[openzim](https://github.com/openzim) we've started creating archives using zstd.
However, a bit naively, we've used the highest compression level and we end using a 128Mb windowsize.
But in the same time, the content we are compressing is keep around 1Mb data.

So, at decompression, we (zstd) always need to allocate a 128Mb buffer.
As we keep decompression stream in cache, we rapidly run out of memory. (https://github.com/kiwix/libkiwix/issues/515#issuecomment-850448854)

But, from what I understand (and this may be wrong), as the content is 1Mb, the "real" used window size in 1Mb, so we could avoid this huge allocation.

**Describe the solution you'd like**
Could zstd allocate only around MIN(windowSize, Frame_Content_Size) at decompression ?

**Comment by Cyan4973** [comment]
> Could zstd allocate only around MIN(windowSize, Frame_Content_Size) at decompression ?

That's what `zstd` does by default.
If it doesn't, that means it doesn't know the content size.

Presuming you are using the `libzstd` API,
simple one-shot functions like `ZSTD_compress()` will, by default, adopt above policy.

However, more complex functions such as `ZSTD_compressStream()` cannot do that,
because by default, they don't know the source size when starting compression.
So they have to "bet", and they bet that the size might be large, so they prepare for it.

When possible, it's preferable to use one-shot functions, because they dynamically adjust parameters based on source size.
But when one-shot functions are not possible, there are additional solutions.

The streaming API can be combined with [advanced parameters](https://github.com/facebook/zstd/blob/v1.5.0/lib/zstd.h#L238).
One of them allows [setting the content size to a pre-determined value](https://github.com/facebook/zstd/blob/v1.5.0/lib/zstd.h#L471).
Note that in this case, the value must be exact, and will be controlled at library level, notably when closing the frame (finishing compression).

If source size is really not known, and you want nonetheless to limit memory usage, it's possible to [set the window size directly](https://github.com/facebook/zstd/blob/v1.5.0/lib/zstd.h#L288). In which case, it won't adjust if source size is large, thus potentially impacting compression ratio. For all cases smaller than 1 MB though, compression ratio will be unaffected, and with window size now unconditionally set to 1 MB, decompression will no longer need to allocate 128 MB.

Note though that even 1 MB can be a lot, and if you believe your average size is substantially smaller, it's better to give a chance to the compression codec to dynamically adjust parameters depending on source size. But that would require using previous solution, thus knowing the source size immediately, at the beginning.

Finally, even if the decompressor allocates 128 MB, and presuming we are talking about the buffer inside the decoder state, it should not initialize this memory. Thus, it will not _really_ use 128 MB. It should only use the amount it needs, in slices of 4 KB (page size). For 32-bit, it's still a problem, due to scarcity of address space. But for 64-bit system, such waste of address space tend to be insignificant. Only actually used memory matters.

**Comment by mgautierfr** [comment]
> For 32-bit, it's still a problem, due to scarcity of address space

That's was our problem. Thanks for your useful comment.

I'm closing this as I've got all my answers (and even more)

**Comment by dentiny** [comment]
Hi @Cyan4973 can I ask a question on stream-based decompression?

For my case, on compression side, I use zstd `ZSTD_compressCCtx`.
On decompression side, I read content from cloud in chunks with zero-copy (we could get the pointer for content). We allocate memory in several chunks instead of a large piece of memory.

I want to know if zstd currently supports stream-based decompression, which could better utilize the zero-copy feature? We want to avoid copying the content of these chunks into a big block then decompress.
I tried to use buffer-less decompression API (https://github.com/facebook/zstd/blob/a488ba114ec17ea1054b9057c26a046fc122b3b6/lib/zstd.h#L2379) but it doesn't show difference with copy content + decompress, so I'm suspecting I used it in the wrong way.

I would be really grateful if zstd experts like you could give me some instructions on this issue. Thank you!

**Comment by Cyan4973** [comment]
This sounds like a very complex topic, that I would rather recommend to stay clear of.

It's correct that the buffer-less decompression API seems to offer capabilities in the direction you are looking for,
but it comes with many strings attached, so I would rather not invite you to try this direction.

The "regular" streaming API will collect data from these chunks, and whenever necessary, copy them internally before decompressing them. It is even able to skip this copy operation when an entire block is available in a single memory segment.
And I believe this is a reasonable approach. The cost of this `memcpy` operation is insignificant, and the memory cost for this input buffer, a block size, is just a fraction of total memory cost needed for streaming decompression. 
The largest memory cost of streaming decompression is expected to be the output buffer.
