### ISSUE TITLE
Question about multi-threading support

### ISSUE THREAD

**Issue by hwogit** [facebook/zstd#2721]
What exactly does multi-threading support mean in the case of libzstd?
Does it mean that libzstd uses multiple threads in a single call to compress?
Or does it mean that multiple calls to libzsdt for compression may occur in parallel?

If libzsdt was created for single threaded mode, are multiple parallel calls to compress files/streams possible?

The background to my question is that I am creating an app that will itself ensure that multiple files are compressed in parallel. The libzstd is only needed to compress a substream. These calls to libzstd are made multiple times in parallel for independent streams. Can I use libzstd in single thread mode for this?

**Comment by Cyan4973** [comment]
Yes, your scenario corresponds to the "normal" way to use `libzstd`.
Most applications expect `libzstd` to compress in single-thread mode, because they already handle multi-threading themselves. They just want multiple instances of compression / decompression to happen seamlessly in parallel. This is what `libzstd` offers.

`libzstd` can also, optionally, deploy multiple threads to compress a single (big) payload. That being said, this is an advanced use case, suitable for some niche scenarios, but not enabled by default. It's likely not a useful feature for your application.

**Comment by hwogit** [comment]
Thank you for the information. In my app, large files are split into 8 MB fragments, each compressed independently in separate threads. This is much faster than compressing the entire file in one thread.
