### ISSUE TITLE
ZSTD_insertBtAndGetAllMatches: Assertion `memcmp(match, ip, matchLength) == 0' failed

### ISSUE THREAD

**Issue by tommythorn** [facebook/zstd#2728]
**Describe the bug**
Hit an assertion (zstd: ../lib/compress/zstd_opt.c:651: ZSTD_insertBtAndGetAllMatches: Assertion `memcmp(match, ip, matchLength) == 0' failed.) while compressing a file.

This will probably be closed as "can't reproduce" as the file is 2363663601800 B (~ 2.1 TiB) and confidential.

**To Reproduce**
1. zfs send my private checkpoint, producing a 2363663601800 byte Zstream.
2. pipe it into `zstd -T24 -19`
3. Wait ~ 4 hours.

**Expected behavior**
No assertion.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04/AMD64 (fully up-to-date as of today)
 -   `*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***`
 -  (MD5 sum of zstd: 0ebc538aa70c5dfd46ac06edc24f0287)
 - Host: Ryzen 3900XT w/16 GiB

**Additional context**
My bandwidth for testing this is limited (and it's a multi-hour process), but if you point me to a specific version to try (I can give it a shot).

**Comment by tommythorn** [comment]
doesn’t reproduce with self-compiled 1.5.0

**Comment by terrelln** [comment]
As far as I can tell there haven't been any relevant changes to `zstd_opt.c` since v1.4.8 so this is likely still a problem, but it is possible it is fixed in the latest release. Although it seems this bug is very rare, and hard to trigger, it is a serious problem because it could potentially cause corruption.

I agree that it will be hard to debug since we can't reproduce it. But, I will leave this issue open for now. Hopefully our fuzzers will find a much smaller reproducer, if the bug is still present, and we can close this issue.

**Comment by ghost** [comment]
Just curious, why are you using a debug build? (allow `assert()` )
Have you tried self-compiled 1.4.8?

**Comment by tommythorn** [comment]
I’m was the binaries Ubuntu shipped with (for 1.4.8).  I haven’t tried building 1.4.8 myself as my host crashed while testing 1.5.0 that I built myself (after very many hours) and my bandwidth for testing this is already exceeded.

Tommy

**Comment by ghost** [comment]
I suggest to test the memory.
When I plugged 4 x 4G RAM, and ran a compression test repeatedly, different hash values of compressed data occasionally appear.
Then I used Windows 10's memory test, it found a hardware memory error.
If only plug 2 x 4G RAM, no more memory errors, and no wrong hash values.
(CPU i5 4570)

**Comment by tommythorn** [comment]
I'm very sorry.  It does indeed appear to have been a previously not-seen instability with my machine.
Couldn't reproduce when I improved the cooling.

**Comment by reivilibre** [comment]
I was running into this error message (though from using the library, not a CLI invocation on a stream). I memtested my machine (several passes) and it was fine.

Then it dawned on me (and empirically this fault seems to trigger frequently on database files for open applications):

I was memory-mapping files, splitting them up and compressing the slices.

The memory-mapping was one of those misguided things I did because it felt clever (the code to do it in my program was pretty elegant, more elegant than opening a file normally) and seemed like it would be more performant because that's what all the cool kids are doing :sunglasses:.

'Obviously' there's a big risk here: the data can change underneath the reader, in this case part-way through the compression(?), which is probably causing all sorts of craziness for Zstd here.

So if someone runs into this issue and thinks their memory is fine ... well, check if you're being too clever for your own good like me and memory-mapping the file, essentially letting other applications 'corrupt' the memory whilst Zstd is doing its work ;-).
