### ISSUE TITLE
Maximum possible compression settings

### ISSUE THREAD

**Issue by Merculous** [facebook/zstd#2730]
I'd like to know, obviously from the "issue" title, the absolute maximum compression zstd can do. I have "--ultra -22 --long=31 --single-thread" so far, and not exactly sure what the difference between -T1 and --single-thread are, and just assumed a bit more compression. Anything I can replace for more compression if it exists will be appreciated. I tried to do some good searching but have found nothing. The long range options help, but I could not find anything obvious other than what I have.

**Comment by Cyan4973** [comment]
I would use `--ultra -22 --long=31 --zstd=hlog=30,clog=30,slog=29,tlen=9999`.

**Comment by Merculous** [comment]
Thanks.

**Comment by lelik107** [comment]
Hello Yann! You gave this advice a long ago and sometimes users try to follow it. I can't understand about targetLength (tlen) specifically - the first part of the manual says:
"Note: for level 19, you can get increased compression ratio at the cost of speed by specifying --zstd=targetLength= to be something large (i.e. 4096)"
but the second part says:
"The minimum tlen is 0 and the maximum is 128 KiB."
And I can't understand what is right. Can you explain please what is the correct range of this switch?

**Comment by Cyan4973** [comment]
`targetLength` is a pretty advanced parameter for the optimal parser.
It's a sort of "shortcut", which means : "whenever you find a match of at least that length, just take it on the spot, and resolve the shortest path analysis right away". Smaller values makes the analysis shorter, hence the compression faster, and the compression ratio worse.
 
This parameter can technically store any positive value, but there is a limited range in which it makes sense.
Specifically, given that a block has a hard limit of 128 KiB set by the format, there's no sense specifying a larger `targetLength` value than that.
So, if a huge value is provided, it will be clamped to that maximum.

But there is more.
The current algorithm employed in `--ultra` settings also has implementation limitations.
Currently, this limitation is set to `4096`.
It means that, even if `targetLength` is set to a larger length than `4096`, it will effectively be clamped to `4096`,  because any match larger than that will be selected on the spot. 

But that's an implementation limitation, meaning it could change in the future. Nothing in the format forbids that. Maybe in the future it could be clamped to `8192` for example.

Therefore, `4096` is more of a "soft current limit".

**Comment by lelik107** [comment]
Some ZSTD's fine tuning parameters are very interesting but pretty sophisticated for the beginners. Thank you for the explanation Yann.

**Comment by Cyan4973** [comment]
Well, advanced parameters are clearly not for beginners.

The whole logic (of selecting the "right" set of parameters) is abstracted behind the concept of "compression level".
That's the more accessible abstraction casual users are expected to interact with.

**Comment by lelik107** [comment]
You are very right. What I found out using ZSTD is that the:
`-level --long and all the options with the threads` are crucial to understand
but the others are not so because they're tuned to be in the safe zone.
And this means you don't want to redefine them unless you know exactly why in case you want the program to work right.

**Comment by lelik107** [comment]
@Cyan4973 Hello Yann. I noticed that for ZSTD v1.5.7 with --max switch tlen=131072 is set. Or at least -vv shows exactly this.
Did you increase the value as you previously said here: https://github.com/facebook/zstd/issues/2730#issuecomment-1954838665?

> Maybe in the future it could be clamped to 8192 for example.

**Comment by Cyan4973** [comment]
Even though it's set to 131072, in effect, it's clamped to 4096 afterwards.
Going above that limit requires an enlarged memory budget for the sequence track.
Which is another thing we could do in the future.

**Comment by lelik107** [comment]
@Cyan4973 Thank you, I understood.
Yann, have you ever thought of increasing LZ77/78 sliding window (wlog in ZSTD as I understand) to 32 (4Gb) or even 33 (8Gb)?
In general practice to find more matches a sliding window should cover the data size, and nowadays 4-8 Gb of the data is not the biggest size.

**Comment by Cyan4973** [comment]
We have a hard limit at 2 GB currently.
Not a format limit, an implementation one.
Passing that limit will require a significant refactor.
We don't have the bandwidth for this effort now.

**Comment by lelik107** [comment]
@Cyan4973 Thank you for the explanations, Yann. It's a pleasure to know more about the software from the developers themselves.

**Comment by tansy** [comment]
Can \`tlen' be used for other strategies, like lazy, or only for opt and ultra (that's what is in manual anyway)?

**Comment by Cyan4973** [comment]
> Can `tlen' be used for other strategies, like lazy, or only for opt and ultra (that's what is in manual anyway)?

only for `opt` and `ultra`
