### ISSUE TITLE
Question : Multithread use of ZSTD_compressCCtx seems to be less performant than single thread?

### ISSUE THREAD

**Issue by bvpvamsikrishna** [facebook/zstd#2741]
We are trying to use zstd (using ZSTD_compressCCtx method) to compress 64KB blocks parallelly using multiple threads. It seems a single thread is performing better than with 4 threads on a 16 CPU machine.
Test program logic:
1. Read the input file into an array of input buffers of 64KB size each.
2. Create 4 threads and divide the array into four work areas and assign them to each thread.
3. Each thread will compress all the blocks assigned to it.

When we use a sample input file of 2.7 GB, with a single thread compression processing time is 0.82 seconds whereas with 4 threads time taken is 1.037.

Is this expected? 
If we are using zstd in the wrong way, could you suggest the right way?

For your reference, I am attaching our test program below,
[zstd_context_threads.txt](https://github.com/facebook/zstd/files/6930995/zstd_context_threads.txt)

**Comment by MarkMielke** [comment]
Threads don't automatically make things faster. There is a lot of
complexity added in your code, but it might not be the right complexity.
For example, I don't know why you would wait to start the threads, but if
you are going to wait, I don't believe this is a proper way to do it :

    while (startThread == 0) {
        sched_yield();
    }


There is no memory barriers or other hints around this. The variable isn't
declared volatile so the memory model seems to make this loop behaviour
undefined. In theory, I suppose your threads could all consume CPU and loop
forever here without ever making progress beyond this point.

If the code isn't optimized and it is reading real memory making it sort of
volatile, you still have a period of time where all your threads are
consuming CPU looping waiting for the go ahead. But I'm suspicious here,
since you don't notify the threads when they can start with a kernel call.
You are relying solely on them noticing a change in memory, without memory
synchronization primitives in use. They could wake up right away or they
could wake up some time in the future.

This is just one piece of the code and a hint for things you should
investigate.

**Comment by Cyan4973** [comment]
`clock()` provides the cpu time.
It will ramp up with the nb of cores effectively used.

You should use a time function for measurements.

**Comment by bvpvamsikrishna** [comment]
Thank you, once I change to proper thread sync methods using pthread_cond_wait, I can see the difference in the multithreaded performance.
