### ISSUE TITLE
Missing uncompressed size/ ratio when compress standard input 

### ISSUE THREAD

**Issue by beci** [facebook/zstd#2744]
**Describe the bug**
Missing uncompressed size/ ratio when compress standard input.

**To Reproduce**
```bash
# create sample data
> yes "i contribute to open source every week" | head -n 5 > bla.txt

# 1. create tarfile and compress it
> tar -cf bla1.tar bla.txt
> zstd bla1.tar 

# 2. tar filter through zstd
> tar -I "zstd -12" -cf bla2.tar.zst bla.txt

# 3. same with pipe
> tar cvf - bla.txt | zstd -12 -f -o bla3.tar.zst

# and the results>
> zstd -l *.zst
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
     1      0     0.13 KB      10.00 KB  78.769  XXH64  bla1.tar.zst
     1      0     0.12 KB                       XXH64  bla2.tar.zst
     1      0     0.12 KB                       XXH64  bla3.tar.zst
----------------------------------------------------------------- 
     3      0     0.37 KB                       XXH64  3 files
```

**Expected behavior**
When compress standard input, it should write back the metadata.

**Comment by terrelln** [comment]
In order to write the decompressed size in the frame, zstd needs to know the decompressed size when compression starts. When compressing from a pipe, zstd can't know that in advance.

You can provide it with `--stream-size=#`. E.g. `zstd --stream-size=10000`. However, that size must be exactly correct, and zstd compression will error out if it finds out it is wrong when the compression completes.
