### ISSUE TITLE
Problem with macro deprecated

### ISSUE THREAD

**Issue by Jamaika1** [facebook/zstd#2767]
GCC 12.0.0 20210826 X86_64 Windows  10
```
zbuff_compress.c: In function 'ZBUFF_compressInit_advanced':
zbuff_compress.c:76:5: warning: 'ZSTD_initCStream_advanced' is deprecated [-Wdeprecated-declarations]
   76 |     return ZSTD_initCStream_advanced(zbc, dict, dictSize, params, pledgedSrcSize);
      |     ^~~~~~
In file included from zbuff.h:189,
                 from zbuff_compress.c:17:
zstd.h:2216:8: note: declared here
 2216 | size_t ZSTD_initCStream_advanced(ZSTD_CStream* zcs,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
zbuff_compress.c: In function 'ZBUFF_compressInitDictionary':
zbuff_compress.c:82:5: warning: 'ZSTD_initCStream_usingDict' is deprecated [-Wdeprecated-declarations]
   82 |     return ZSTD_initCStream_usingDict(zbc, dict, dictSize, compressionLevel);
      |     ^~~~~~
In file included from zbuff.h:189,
                 from zbuff_compress.c:17:
zstd.h:2196:8: note: declared here
 2196 | size_t ZSTD_initCStream_usingDict(ZSTD_CStream* zcs,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Cyan4973** [comment]
Not sure which application you are compiling,
but we would like to invite you to no longer use `ZBUFF_`,
which is an old API that has been deprecated a long time ago.
Prefer using stable APIs, which are fully supported now and in the future, and offer all the capabilities of `ZBUFF_` and more.

**Comment by terrelln** [comment]
We no longer build zbuff as part of the library, unless deprecated APIs have been explicitly enabled. And we're planning on removing the source code from the library at some point in the future. So I strongly recommend you move away from the API.

However, if you are blocked by this in the short term, you can use `-Wno-deprecated-declarations` to silence the warning. But again, this will only work for so long, because we will be deleting this code.

**Comment by Jamaika1** [comment]
I use ZSTDLIB_VISIBILITY=ZSTDLIB_API=/"/"
Adding ZBUFF_ doesn't fix anything

**Comment by felixhandte** [comment]
The linked PR should fix this issue.
