### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by dbrami** [facebook/zstd#2804]
Hi,
I'm new to ZSTD. The documentation makes it ample clear that using a dictionary for compression increases the compression ratio and the speed. Yet, I'm getting a better compression without the use of the dictionary (but definitely speed gains).
What am I doing wrong?
I'm compressing JSON "documents". I used split to create one document per file from a large source file and have tried using both 1k and 10k training samples yet got same results.

Here are outputs - please note the compression of 7.97% without dictionary and 13.72% with dictionary.
Any thoughts?
```
zstd -T4 -19 -v -v first_100k_records.json -o first_100k_records.json.zstd
*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***
zstd: first_100k_records.json.zstd already exists; overwrite (y/n) ? y
first_100k_records.json :  7.97%   (384998461 => 30669146 bytes, first_100k_records.json.zstd) 
first_100k_records.json : Completed in 145.70 sec  (cpu load : 199%)```

mkdir dict
cd dict
split -l 1 ../first_1k_records.json 1k
cd ..

zstd --train dict/* -o 1kdict
Trying 5 different sets of parameters                                          
k=1998                                                                         
d=8
f=20
steps=4
split=75
accel=1
Save dictionary of size 112640 into file 1kdict

zstd -T4 -19 -v -v -D 1kdict first_100k_records.json -o first_100k_records_dict_2.json.zstd
*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***
Loading 1kdict as dictionary 
zstd: first_100k_records_dict_2.json.zstd already exists; overwrite (y/n) ? y
first_100k_records.json : 13.72%   (384998461 => 52820640 bytes, first_100k_records_dict_2.json.zstd) 
first_100k_records.json : Completed in 6.33 sec  (cpu load : 137%)

**Comment by Cyan4973** [comment]
It looks to me that you are compressing one large big file.

For such a scenario, dictionary compression will not bring any significant benefit.
Actually, due to other complex and changing side effects, it is likely going to decrease compression efficiencies.

Dictionary compression is useful to compress a lot of small files.
The corresponding command line would look like something like : 
`zstd -r dict -c | wc - c` , 
vs `zstd -r dict -D 1kdict -c | wc -c`.

Then, it should be possible to observe benefits from dictionary compression.

Note that in this new scenario, each small file is compressed independently. This is entirely different from the first scenario, where all the records are grouped together in one giant big file. Obviously, from a compression ratio perspective, compressing one large big file results in a denser compressed outcome, so the new scenario compressing each file independently will result in worse compression ratio. 
On the other hand, if there is a need to consult one record, the "big file" approach requires to decompress everything and search the wanted record into it, while the second approach allows fetching and decompressing just the one wanted record.

**Comment by dbrami** [comment]
Thank you for these explanations. I got comparable compression rates for both methods by using v1.50 but will keep your caveats in mind.

Thanks again.
