### ISSUE TITLE
ZSTD_countTrailingZeros() bug?

### ISSUE THREAD

**Issue by ghost** [facebook/zstd#2807]
The current `dev` branch has a `ZSTD_countTrailingZeros()` function.
Maybe `>> 3` is wrong?

https://github.com/facebook/zstd/blob/a5f2c45528032ed20c33e0f8cd2c163a800a0017/lib/common/zstd_internal.h#L381-L424

**Comment by ghost** [comment]
If it's a bug, I can fix it in #2800, so that the trouble of code conflicts can be reduced.

**Comment by Cyan4973** [comment]
I presume it was originally designed to provide the nb of trailing zero **bytes**.
However, the next 2 variants seem to return the nb of _bits_ instead.

We would have to look at invocation call sites of `ZSTD_countTrailingZeros()` to understand and check that all call sites expect one variant or the other, and fix it accordingly. A name change is likely welcome too, in order to avoid such confusion in the future.

I also note that this variant produced no test error nor bug report, meaning it's likely unused. Not sure if there is a test that could force usage of this code path.

**Comment by ghost** [comment]
The function is used when `HUF_ENABLE_ASM_X86_64_BMI2` macro is defined.
Maybe because it is being developed on the x64 Linux platform, so no problem was exposed.

**Comment by Cyan4973** [comment]
And it is also clearly looking for the nb of bits : 
`bit->bitsConsumed = ZSTD_countTrailingZeros((size_t)args->bits[stream]);`
so that clears it, `>> 3` is a bug. To be fixed.

**Comment by terrelln** [comment]
Yes, it is a bug. A fix would be welcome :)

The code is currently disabled on Windows. This is one step closer to it working. And `ZSTD_countTrailingZeros()` isn't used in 32-bit mode, currently.

**Comment by ghost** [comment]
Fixed in #2800.
I removed the slow code, since it's a hot function used by ASM implementation.

**Comment by terrelln** [comment]
> I removed the slow code, since it's a hot function used by ASM implementation.

This is actually a very cold function. It is only called 4x per block, to setup for the ASM. We should leave the backup implementation in place.

**Comment by ghost** [comment]
Fixed in #2800 .
