### ISSUE TITLE
How to create split zstd files?

### ISSUE THREAD

**Issue by ragnarov** [facebook/zstd#2812]
Suppose I want to compress a file called 'target.tar' using zstd.
But there will not be a single resultant file like 'target.tar.zst'.
It will consist of several parts.
For example : 
target.zst.001
target.zst.002
target.zst.003
⋮
target.zst.00n

When I decompress target.zst.001 , zstd should automatically
search for the other needed parts, like target.zst.002, target.zst.003,
...target.zst.00n.

This can be done with rar and 7z archives.
Can zstd do this? How?

Can zstd automatically extract files splitted using  `split` command?.

I need this because I can use cat to put together a file splitted using `split`
command but the other person with whom I share my file may not want to
do that. They may be on Windows which can further complicate matters.
But if zstd handles this, things get easier.

You may ask, why I need to split files?
Cause many online cloud storage services does not allow uploading of files
bigger than a certain size.

Do you have a support IRC channel?

**Comment by Cyan4973** [comment]
> When I decompress target.zst.001 , zstd should automatically
search for the other needed parts, like target.zst.002, target.zst.003,
...target.zst.00n.
> This can be done with rar and 7z archives.
> Can zstd do this? How?

Nope, it can't.

An important thing to keep in mind here is that `zstd` is not an _archiver_, which both `rar` and `7zip` are.
It's merely a streamable compression format, with no additional metadata.
It's _designed to be integrated into archivers_, and btw it's exactly what [7zip_zstd_edition](https://mcmilk.de/projects/7-Zip-zstd/) does. 
The `zstd` command line tool can also be used as a stand-alone compressor (but ***not*** _archiver_), exactly like `gzip` or `xz` already do.

> Can zstd automatically extract files splitted using split command?

Partially, yes, it depends on implementation details.

If you : 
1) `split` a file
2) compress each file-chunk independently
3) concatenate these compressed chunk into a single file (or into `stdin` stream) and in the correct order
4) decompress the resulting concatenation of compressed chunks by `zstd`
then you get the same decompressed result as if the original file was compressed as a single file, instead of being `split` first.

Of course, it results in a reduction of compression ratio, so this use case may look silly at first.
But there are situations where it's not possible to wait, and data has to be compressed in chunks, typically for buffer reasons. In which case, the concatenation of multiple compressed blocks is a correct solution.

While the scenario above corresponds to some real-world situations in datacenters, for your use case, you would be better off `split`ting the entire compressed frame into numbered frame, and then concatenating them back into `zstd` on the decompression side. This would save compression ratio, and make compressed size more predictable.

Note that, as said before, the concatenation logic is not provided by `zstd`. An external script has to do this job. Given a decided set of convention, it looks simple enough to be done in `bash` or `python`, it's just not part of any logic shipped directly within `zstd`.

> Do you have a support IRC channel?

We use the github public issue board for support.

**Comment by ragnarov** [comment]
Thank you for replying.
