### ISSUE TITLE
Question: Compressing to a sequence of size-bounded frames or blocks

### ISSUE THREAD

**Issue by gdhuse-ocient** [facebook/zstd#2823]
Hello, 

I'd like to implement seekable compression that aligns to 4K disk block boundaries, and could use some guidance.  I have a large stream of data to compress, and would like to generate a sequence of frames of no more than 4KB each.  Experimenting with both the buffered and unbuffered stream compression APIs, I haven't had any luck finding a way to bound frame size.

I'd also be happy using something similar to `ZSTD_compressBlock()` to generate blocks instead of frames.  In this case, my ideal API would take a maximum block size, a dst buffer of at least that size, a potentially too-large src buffer, and then return the number of bytes consumed from src.

Is what I'm trying to do possible?  I'm open to exposing and calling internal APIs or even adjusting hard-coded limits if needed.  

Cheers,
 Greg

**Comment by Cyan4973** [comment]
While it's theoretically possible, the public interfaces to do so do not exist.
It's also far from trivial, because there are many dynamically sized components, hence it's not as simple as cutting the input into pre-determined fixed size.

An expensive way to achieve this objective is effectively to "guess, try and adjust". After multiple passes, you will eventually end up with a compressed frame size around 4 KB, or strictly <= 4 KB if disk block is your use case, and call it "good enough", and move on to next disk block. Nothing fancy, but it can get the job done, given enough time and processing power.

**Comment by sergv** [comment]
@gdhuse-ocient Have you looked at `zstd_seekable`? Even though its aim is to make it possible to navitage to arbitrary offsets in the decompressed stream by seeking in the compressed stream, it has ability to not produce frames more that a certain size, i.e. https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstd_seekable.h#L83:

```
ZSTDLIB_API size_t ZSTD_seekable_initCStream(ZSTD_seekable_CStream* zcs, int compressionLevel, int checksumFlag, unsigned maxFrameSize);
```
If `ZSTD_seekable_initCStream` does more than you need then you can take it as an inspiration and maybe implement something similar yourself.

**Comment by gdhuse-ocient** [comment]
Thanks to both of you for your responses.  @sergv, looking at https://github.com/facebook/zstd/blob/v1.5.0/contrib/seekable_format/zstdseek_compress.c#L233 it seems like `maxFrameSize` limits the size of decompressed input data per frame, where I would like to limit the size the compressed output frames.  Unless I'm mistaken, it sounds like I need to consider different approaches.
