### ISSUE TITLE
correct --size-hint increases compressed size

### ISSUE THREAD

**Issue by Hello71** [facebook/zstd#2848]
**Describe the bug**
According to the manual (emphasis added):

> When handling input from a stream, zstd must guess how large the source size will be when optimizing compression parameters. If the stream size is relatively small, this guess may be a poor one, resulting in a higher compression ratio than expected. This feature allows for controlling the guess when needed. *Exact guesses result in better compression ratios.* Overestimates result in slightly degraded compression ratios, while underestimates may result in significant degradation.

From this description, I assumed that if I specify --size-hint with exactly the correct size, then the compressed size should either decrease or remain the same.

**To Reproduce**
1. Download [vmlinux-lts.gz](https://github.com/facebook/zstd/files/7488655/vmlinux-lts.gz) and decompress it. This file was obtained by downloading https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/linux-lts-5.15.0-r0.apk, extracting boot/vmlinuz-lts, then running scripts/extract-vmlinux.sh from the Linux kernel sources.
2. Run `cat vmlinux-lts | zstd --ultra -22 -c | wc -c`.
3. Run `cat vmlinux-lts | zstd --size-hint=$(wc -c < vmlinux-lts) --ultra -22 -c | wc -c`.
4. Run `cat vmlinux-lts | zstd --stream-size=$(wc -c < vmlinux-lts) --ultra -22 -c | wc -c`.

**Expected behavior**
step 2 <= step 3 ~= step 4.

**Screenshots and charts**
6669383, 6669897 (diff +514), 6669900 (diff +3).

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 1.5.0
 - Compiler: n/a
 - Flags: n/a
 - Other relevant hardware specs: n/a
 - Build system: n/a

**Additional context**
I expected stream-size to be possibly slightly smaller, but larger also seems reasonable; I guess it makes the same compressed data but with 3 byte longer header. However, it seems unexpected that a correct size-hint would increase the file size.

**Comment by Cyan4973** [comment]
A few words.
1) The differences presented are extremely small. This is well below <0.1%. At this level, we are essentially talking noise.
2) There are a lot of heuristics in these algorithms, and while they do generally tend to work as intended, well they are just guesses, and sometimes they guess wrong.
3) In this case though, the pb is more likely conflicting priorities between different dynamic adjustments, one meant to "improve" compression ratio, the other one meant to improve memory usage, to preserve system-level performance.

The "improvement" talked about here should not be seen as any kind of "hard guarantee".
It's more a "general attempt at".
More importantly, `--size-hint` wasn't designed to address this scenario.

The scenario `--size-hint` addresses is when input ends up being small (like < 16 KB), while being passed from `stdin`, thus not giving `zstd` a chance to guess its size before hand.
In which case, providing a `size-hint` will be very helpful, as otherwise, `zstd` will spend a massive amount of memory, initialization time and gear its search structures towards large files, and this will be wasteful. The effect on compression ratio is probably even more visible for middle-range compression levels (such as level ~12 for example) which have to arbitrate between trade-offs and can't just throw a massive amount of resources at the problem. We are talking many % of difference here, so it's not negligible.

The other aspect is "good" usage of memory. In this specific instance, the source size is a bit less than 32 MB, which means a `windowLog=25` will prove enough. Yet, `--ultra 22` expects by default something in the range of ~128 MB. When it's informed that there are only 32 MB to compress, it will reduce its memory usage to match this new target. This results in pretty massive memory savings. But indeed, it also means its search structures are partially reduced, increasing other side effects, such as collisions ratios, which are compensated by deeper search rounds, but eat into the search budget, up to a preset limit.

All in all, despite such tradeoff, this should end up being pretty much "okay", at least as long as a < 0.1% difference is considered "negligible".
 
If it's not, then users can still take matters into their own hands, and decide to manually override parameters and select the ones which give the absolute best compression ratio. Not even `--ultra -22` goes there, because the tradeoff seems honestly wasteful, but well, if anyone wants to go there _regardless_, then advanced interfaces and parameters are the way forward.

**Comment by Hello71** [comment]
hm, yes, I see your point. I'm still a little confused though: I compared `cat vmlinux-lts | zstd --ultra -22 --show-default-cparams >/dev/null` and `zstd --ultra -22 --show-default-cparams vmlinux-lts` and found that with known size, `windowLog` is set to 25 and `chainLog` is set to 26. then I tried `zstd --ultra -22 -c --zstd=wlog=27,clog=27 vmlinux-lts | wc -c` and found that it still gives the "large" 6669900. am I using `--zstd` wrong, or are there some "hidden parameters"?

**Comment by Cyan4973** [comment]
I believe there are a few adjustments which are "unavoidable".
Specifically, I think that, when the library is "certain" of the input size, it will adjust `windowLog` downward if need be, and may then also adjust a bunch of other things in the process (`chainLog` and `hashLog`) to match the new value.

One way to avoid such automatic adaptation is to "hide" the input size, i.e. send input via `stdin`.

There used to be a way to force any parameter to any value and bypass these automatic adaptations (`ZSTD_compress_advanced()` I believe), but it was deprecated years ago. Reason was, we needed to funnel multiple disparate entry points into a single processing pipeline, for improved maintenance and reliability (some sets of parameters do not make sense). That's more or less how automatic adjustments ended up being compulsory.
