### ISSUE TITLE
ZSTD_maxCLevel, x86 vs x64

### ISSUE THREAD

**Issue by aleksazr** [facebook/zstd#2919]
#2885 has limited ZSTD_maxCLevel to 21 for 32-bit binaries,
which causes x64 code to be 2x slower than x86 code with some files.

Currently, I only see this with Rich Text Format (*.rtf) files containing images.
Sample file: http://users.beotel.net/~gwh/zstd/zstd_rtf.zip

Perhaps limit it to 21 only for files bigger than some limit,
`ZSTDLIB_API int ZSTD_maxCLevelEx(size_t srcSize); // note the Ex`

```
x86
17#test.rtf          :   5142698 ->     23636 (217.58),  54.4 MB/s ,4298.8 MB/s
18#test.rtf          :   5142698 ->     23779 (216.27),  51.8 MB/s ,4613.9 MB/s
19#test.rtf          :   5142698 ->     23213 (221.54),  20.4 MB/s ,4591.3 MB/s
20#test.rtf          :   5142698 ->     23213 (221.54),  20.2 MB/s ,4573.3 MB/s
21#test.rtf          :   5142698 ->     22461 (228.96),  8.34 MB/s ,4638.1 MB/s ZSTD_maxCLevel()
22#test.rtf          :   5142698 ->     20869 (246.43),  2.90 MB/s ,4645.6 MB/s
```

```
x64
17#test.rtf          :   5142698 ->     23636 (217.58),  86.9 MB/s ,4476.6 MB/s
18#test.rtf          :   5142698 ->     23779 (216.27),  79.6 MB/s ,5888.8 MB/s
19#test.rtf          :   5142698 ->     23213 (221.54),  27.9 MB/s ,5995.2 MB/s
20#test.rtf          :   5142698 ->     23213 (221.54),  27.3 MB/s ,5654.1 MB/s
21#test.rtf          :   5142698 ->     22461 (228.96),  10.9 MB/s ,5246.0 MB/s
22#test.rtf          :   5142698 ->     20869 (246.43),  3.81 MB/s ,4918.4 MB/s ZSTD_maxCLevel()
```

**Comment by ghost** [comment]
Limiting to 21 loses some ability.

IMO write in doc that level 22 may run out of 32-bit memory space, or give a friendly error message when there is a huge memory request in 32-bit build.

**Comment by aleksazr** [comment]
My next idea was to have a flag (#define / variable) that would say (to zstd internal functions):
"you are running on a 32bit CPU. If level 22 runs out of memory, try level 21."

But that should be a normal behavior anyway. Simply disabling level 22 for 32bit code is not
a good thing for files that **could** be compressed in 32bit memory space.
A 32bit app could use level 21 and still run out of memory (because it was already taken).

**Comment by Cyan4973** [comment]
Initially, 32-bit used to be limited to level 20, due to a limitation in the 32-bit encoder.

Later on, higher levels 21 and 22 were enabled, but limited the window size to 32 MB (equivalent to level 20).
This resulted in confusion, with users complaining that level 21 and 22 do not mean the same thing depending on the platform.

Ultimately, we fixed the issue with 32-bit mode and window sizes > 32 MB, and therefore kept levels 21 and 22 on 32-bit platform. Problem is, it's now quite frequent for these high levels to run out of memory on 32-bit systems, especially since the CLI switched to multi-threading mode by default (and especially level 22, which is now almost guaranteed to run out of memory).

None of these situations are ideal.
But among them, having fixed levels leading to different outcomes depending on platform, or more dynamically depending on runtime conditions, seems a recipe for confusion to the ecosystem.

We see 2 different set of constraints, depending on user scenarios. 
Some want a strictly reproducible outcome : given an input, a version and a set of parameters, the result should be strictly bit identical, whatever the platform. In this case, failing is seen as a better outcome than producing a functioning but different result.
But other scenarios are more keen to let it "work as it can", and are more annoyed to have general parameters deployed on a large heterogeneous fleet that work in some cases, and break in other cases. They would much prefer to let the CLI adjust as needed in order to ensure that the compression process will run and finish.

These are really 2 different sets of scenarios, and if we try to serve them both at the same time, it's easier to settle for a lower denominator, aka only allow compression levels which are "not too high".

Now this doesn't address the fact that small inputs do not need the same amount of memory as large inputs, and therefore even level 22 is fine on 32-bit, as long as input is small enough.
OK, that's right, but now enters another concept, "simplicity".
It's way simpler to explain "level 22 is not available on 32-bit systems" 
than, "it may, it may not, it depends. Let's see what kind of data it is and how it is ingested".
This kind of complexity will be paid big time at ecosystem level, in confusion delays and support time.

There are work-around.
To begin with, while level 22 is not available, advanced parameters are. It's possible to set the same compression parameters as level 22, or even higher ones, and let the system try to run them. In which case, the (advanced) user is fully in charge. It may fail, due to exhaustion of memory, but this is hardly a surprise, advanced users are supposed to be aware of these limitations, and be able deal with them.

Now, when it comes to dynamic adaptation, we don't have yet a great story. We could try to create one, but it would need to be a separate mode, that users explicitly select, so that they also accept the non-reproducibility property (a bit like `--adapt`). The downside is that it's a pretty big effort, costing time and energy that could be better spent in other directions, and we would need a pretty solid use case to justify it. That it can be useful sometimes on a few isolated machines won't cut it. It needs to be for the benefit of a much larger scope.

**Comment by ghost** [comment]
For large files, level 22 is very slow, I suspect not many people do this on 32-bit systems.

If a user encounters this problem in the production environment, he will adjust his behavior.
Please consider making the adjustment easy (for the two constraints), setting parameters is relatively inconvenient, and if the parameters of level 22 are adjusted in future versions, it can't get strictly reproducible outcome.
Maybe limit the maximum level with an environment variable is a easy method.

**Comment by ghost** [comment]
> Problem is, it's now quite frequent for these high levels to run out of memory on 32-bit systems, especially since the CLI switched to multi-threading mode by default (and especially level 22, which is now almost guaranteed to run out of memory).

In multi-threaded compression, if memory allocation fails, can it not be regarded as an error, just wait for the running threads to complete the task, and then retry again.
Can set some constraints for this, such as 32-bit build + MT-compression + total memory > 1.5G.

**Comment by Cyan4973** [comment]
That would indeed be part of the project. But doing it properly is a non-trivial time investment.

Another problem is that even with a single active compression thread, the amount of RAM needed is pretty large for 32-bit systems.

**Comment by ghost** [comment]
I guess some users will complain this.
Please consider revert #2885 and 4cc5e2818a4db99ebf7b5bf1a46258927c5ffa3a at the last moment.
We can add an environment variable to CLI in v1.5.2, this should not diffcult.

**Comment by aleksazr** [comment]
I will probably never compress more than 100k, so this limit is probably pointless to me.
I would write it like this: (clevels.h)

~~~
#ifdef  ZSTD_NOMAX_32BIT_CLEVEL
  #define ZSTD_MAX_32BIT_CLEVEL     ZSTD_MAX_CLEVEL
#else
  #define ZSTD_MAX_32BIT_CLEVEL     21
#endif
~~~

**Comment by ghost** [comment]
The limit was reverted in #2940.

**Comment by Cyan4973** [comment]
There is still a need to offer users with large fleets of disparate hosts an ability to ensure that the binary will complete the compression operation, even if it's at the cost of reduced speed or lower compression ratio, due to restricted memory usage (instead of just failing with a `memory error` code, as it does know).

But we'll do that in a separate effort, tracked in #2933.
