### ISSUE TITLE
Update API manual to version 1.5.1

### ISSUE THREAD

**Issue by marxin** [facebook/zstd#2944]
If I see correctly, API documentation points to version 1.4.7:
https://facebook.github.io/zstd/zstd_manual.html

**Comment by Cyan4973** [comment]
This is a copy of the manual, which is hosted as part of the home page, as opposed to the repository.
Since it's a copy, it doesn't automatically update, so it becomes out of date from time to time.

Thanks for the notification @marxin, the copy has been updated, and now features the content of `v1.5.1`.

The API manual in the repository is always up to date. Ideally, we would prefer to link the manual in the repository. Unfortunately, github does not interpret html content, and display it as raw text file instead : https://github.com/facebook/zstd/blob/release/doc/zstd_manual.html .

**Comment by marxin** [comment]
> Thanks for the notification @marxin, the copy has been updated, and now features the content of `v1.5.1`.

I thank you!

> 
> The API manual in the repository is always up to date. Ideally, we would prefer to link the manual in the repository. Unfortunately, github does not interpret html content, and display it as raw text file instead : https://github.com/facebook/zstd/blob/release/doc/zstd_manual.html .

Well, you will have to use an external service like:
https://raw.githack.com/
https://raw.githack.com/facebook/zstd/release/doc/zstd_manual.html

**Comment by Cyan4973** [comment]
Oh, that's a good one !
Thanks @marxin, it's probably better to use that link, so that it gets updated automatically with each release.

I'll update the homepage with this new link.

**Comment by marxin** [comment]
I took the inspiration from https://stackoverflow.com/questions/6551446/can-i-run-html-files-directly-from-github-instead-of-just-viewing-their-source.

**Comment by marxin** [comment]
Hello. Again, the same problem, please fix.
