### ISSUE TITLE
[Question] Is zstd compression determinist ?

### ISSUE THREAD

**Issue by mgautierfr** [facebook/zstd#2949]
I'm working on a new archive format with some content compressed with zstd.
For this format I would like to have diff/patch feature. To have this efficiently done, I want to store the diff on the uncompressed content and recompress the content when we rebuild the archive (when applying the patch).
But to have a exact diff, I need to be sure that the compressed output will not change over time (zstd release and code change).

So my questions are :
- Does zstd guaranty that the compressed output will always be the same (for the same input and configuration) ? 
- If yes, what configuration do I need to store (and reuse) ? Is the compressionLevel enough or I need to store more detailed configuration ? (And which one ?)

**Comment by Cyan4973** [comment]
`zstd` is deterministic given a same input, a same set of parameters, and a **same version**.
"set of parameter" can be reduced to `compressionLevel` only.

**Comment by mgautierfr** [comment]
I was afraid of having this answer. 
I will have to find a way to do with it.
Thanks.

**Comment by felixhandte** [comment]
I'm surprised that you need repeatable/deterministic compression for your use case. Can you describe more why you think it's important?

It sounds like you're describing a system where you store the contents in compressed form but make diffs and apply patches to the uncompressed data. That makes sense (you couldn't really do it any other way). But then you describe wanting the compressed output to not change when you apply a patch. This doesn't make sense to me. If you change the content, its compressed representation will have to change. And if you don't change the content, you don't need to recompress it. So I don't see the problem.

The only situation I can see where this makes sense is if you want different parties to be able to apply a patch, compress the new content, and arrive at a compressed representation that matches (because you want them be able to compare checksums or something). In that case I would recommend comparing checksums of the uncompressed data.

Consider that if zstd guaranteed compression determinism across versions, we would never be able to optimize zstd's performance; we would be locked into a specific behavior.

**Comment by mgautierfr** [comment]
> The only situation I can see where this makes sense is if you want different parties to be able to apply a patch, compress the new content, and arrive at a compressed representation that matches (because you want them be able to compare checksums or something). In that case I would recommend comparing checksums of the uncompressed data.

It is exactly my situation.
The idea is to have two archives in which the content is different but pretty closed (one being a new version of the other).
I want to distribute a patch between the two archives and allow the downloader to recreate the second archive from the patch and the first archive (the user already have).
Doing the diff on the compressed data would be inefficient.
And I want to have the exact same compressed data because there is indeed a checksum.

The solution is indeed to have the checksum on the uncompressed data. But it means you need to decompress the data to be able to check the archive.
Maybe I can introduce a double checksum on compressed and uncompressed data. If the compressed checksum is not matching, implementation would have to use the uncompressed one.

But anyway, I'm at the spec creation stage. Nothing is really implemented (at least on the diff/patch level). I'm just checking what are my options.

> Consider that if zstd guaranteed compression determinism across versions, we would never be able to optimize zstd's performance; we would be locked into a specific behavior.

I totally understand that.
I was hopping that some low level configuration option was fixing a compression output. The optimization being done by extending the configuration options (and the high level `compressionLevel` following the optimization)
But if I've asked the question it is precisely because I was supposing that the compression was not determinist across version. Just wanted to be sure. I'm not asking you to be determinist.

**Comment by heftig** [comment]
Arch Linux tried that with our delta packages (using `xdelta3`, which patches the decompressed data and then recompresses) and the user experience was terrible. Mostly because a) the archives used expensive compression, so recompression ate lots of cpu time, and b) it was very fragile regarding compressor versions and settings.

**Comment by terrelln** [comment]
@heftig zstd offers `--rsyncable` which makes deltas on the compressed data possible, similar to gzip's `--rsyncable` mode. It does this by resetting the compression history every so often (chosen using a hash of the last 64-bytes of content).

You may find that deltaing the compressed blob, if both were compressed with `--rsyncable`, may provide small deltas. It won't be as small as deltaing the decompressed data, but then you don't need to decompress.

If the zstd version changes, the output could still be significantly different, and the delta may be very large. So you'd want the option to fallback to just not sending a delta.
