### ISSUE TITLE
Question: how to avoid a line in a textfile being cut into 2 frames?

### ISSUE THREAD

**Issue by WindBrush** [facebook/zstd#2952]
Suppose that I got a text file with multiple lines,  I wanna compress it with zstd and decompress it to do sth about the data with multi-thread, which means **one thread should decompress one frame and do sth**. 
Here comes the problem:  a line in the text file can possibly be cut into 2 parts and be compressed into 2 different frames by original zstd. And this is really hard to solve in multi-thread.

Here are my plans and questions:
- plan A:  split the file by lines, and compress each split into a  single frame. How to do this? funtion `ZSTD_CCtx_setPledgedSrcSize()` ? Or zstd command can do this? Or anything u could tell me : )
- plan B:  use stream compression like `~/examples/streaming_compression.c`, but I don't know how `ZSTD_compressStream2()` works,  when will it start a new frame? Can I control it to start or not start a new frame?

Thanks for your patience and reading. ^_^
It would be nice that someone can answer my questions or tell me any other good solutions.

**Comment by felixhandte** [comment]
We've gotten requests for this kind of compressor behavior before: #2812, #2543, #2184, all the way back to #395, etc. But at present, a single invocation of zstd will never cut an input into multiple frames.

If you want to cut an input into multiple frames, you need to present each chunk to zstd in its own compression call. The resulting payloads can then be concatenated or whatever, and then decompressed independently.

Edit: just to confirm, because in zstd a "frame" has a [specific meaning](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#frames), this is what you're talking about, right?

**Comment by WindBrush** [comment]
Thx for replying and the info u provided.
> Edit: just to confirm, because in zstd a "frame" has a specific meaning, this is what you're talking about, right?

yes, the main idea comes from `Each frame is independent and can be decompressed independently of other frames. `

> But at present, a single invocation of zstd will never cut an input into multiple frames.

If so,  It seems that I can simply split the text-file by lines,  then a single invocation of zstd for each split and concatenate all `.zst ` files into 1. And when processing this file, I can simply cut it into different splits(or frames, because of the msg I quote )  by `magic_number`  and decompress them independently. 

Again, Thx for your reply and patience. zstd is really a nice algorithm : )

**Comment by felixhandte** [comment]
The only correction I would make to that plan is, instead of cutting by searching for the next appearance of the zstd magic number (which can show up inside frames), you can use the library function [`ZSTD_findFrameCompressedSize()`](https://github.com/facebook/zstd/blob/v1.5.1/lib/zstd.h#L170-L176) to find the size of each frame so you know where the next begins.

**Comment by WindBrush** [comment]
Thx for correction, for now, I use 1 skippable frame to store every frame size(calculate during compression). `ZSTD_findFrameCompressedSize()`  looks like a better way.
btw, Happy New Year.
