### ISSUE TITLE
broken output with `zstd --decompress --quiet`

### ISSUE THREAD

**Issue by eworm-de** [facebook/zstd#2967]
**Describe the bug**

Decompressing with `--quiet` breaks output:

```
$ zstd --decompress --quiet test.zst
test.zst             : 0 B...     %
```

Note this is missing a newline, the `%` is appended by `zsh`.

**To Reproduce**

1. `echo | zstd > test.zst`
2. `zstd --decompress --quiet test.zst`

**Expected behavior**

Giving `--quiet` should not give broken progress output.

**Additional context**

This broke with d2f31b662779f3c13871d54868e9d5839343856d.

**Comment by terrelln** [comment]
The bug is that decompression should not output progress to stderr when `--quiet` is set. The lack of a newline is correct.

As a workaround you could use `zstd --decompress -qq`, which will suppress all the progress info, but will also suppress all error messages.

We are going to release zstd-1.5.2 relatively soon, and will fix this issue for it.

**Comment by eworm-de** [comment]
I think `zstd --decompress --quiet --no-progress` is an even better workaround. 😉
Anyway, it's not critical, just annoying.
