### ISSUE TITLE
How to know the approximation of the output size depending on the input size?

### ISSUE THREAD

**Issue by ghost** [facebook/zstd#2978]
hi, **I would like to predict an approximation of how many bytes will be left after compression**, Sorry for my ignorance and open an issue for a somewhat weird question, Let's say I have `1024` bytes (1KB) so I need to know what size will be left after compression, and if it is exactly (depending on the level)

**Comment by felixhandte** [comment]
Hi @yaskowiak,

There is no way to know what size we will compress an input to without performing the compression.

There are lower and upper bounds fixed by the zstd format, but those bounds are very wide. An input that is maximally compressible (a single byte repeated over and over again) will compress to 13 bytes plus 4 bytes for every 128KB of input. An incompressible input (totally random uncorrelated bytes) will cost the same 13 bytes of header plus the input size plus 3 bytes for every 128KB.

It all depends on the nature of the data you're compressing.
