### ISSUE TITLE
Windows: leaking thread handles

### ISSUE THREAD

**Issue by luben** [facebook/zstd#3051]
On windows, when using workers for compression it looks it's leaking thread-handles (not threads). This issue got reported by user of `zstd-jni` but it looks that's issue with the underlying native code: https://github.com/luben/zstd-jni/issues/203 - he was able to reproduce by using only the `zstd` CLI.

I don't have Windows system to confirm or test a fix, but it looks we need to call https://docs.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-closehandle after joining the thread: https://github.com/facebook/zstd/blob/12c045f74d922dc934c168f6e1581d72df983388/lib/common/threading.c#L23-L77

**Comment by Cyan4973** [comment]
Thanks for the report @luben !

The issue description and the proposed fix look both correct to me.

An indirectly related issue is : how could we detect such Window-specific leaks in CI ?
We already have leak-detection tests, but they only run on Linux,
hence this code, which is only enabled on Windows, isn't tested for leaks.

Since our experience of Windows is limited, we would gladly accept any pointer that would help creating such a test for Windows CI.

**Comment by ghost** [comment]
CC @vnair81 , the author of #2263.
