### ISSUE TITLE
Clarification on small Window_Size checks by zstd -d

### ISSUE THREAD

**Issue by dkcasset** [facebook/zstd#3151]
I have a file containing one compressed block produced by zstd with no options (of Calgary obj1), and then modified for an artificially small Window_Size of 1KB (with Single_Segment_flag = 0).  This file appears to violate 3 points of the zstd format specification:

1. Block_Maximum_Size = Window_Size is less than the Block_Size
2. Block_Maximum_Size = Window_Size is less than the single block's decompressed data size
3. Offsets of > Window_Size occur in the sequence section of the block

Using zstd -d, version 1.5.2 decompresses the file with no errors.  The educational decoder, however, flags a corrupt file (I believe because of an offset > Window_Size).

Using zstd -d version 1.4.5 also flags a corrupt file (not sure of which check fails).

Which of the above checks are being done for zstd -d?

**Comment by terrelln** [comment]
Upon corruption, the zstd decompressor doesn't guarantee that it will catch every error. If you would like to catch corruption errors **that cause decompressed data corruption** then enable the frame checksum.

We guarantee that we will safely decompress any corrupted data, ant won't crash, or access out of bounds memory, etc. But in this case you are likely decompressing in a single decompression operation using e.g. `ZSTD_decompress()`. In this case, we won't even read the window size, since we don't need to allocate a window buffer.

In streaming mode, we'd need to allocate the window buffer, and would flag the corruption.

That said, we do still try to catch corruption errors when it doesn't come at a performance cost. So we could easily add a check that looks at the block size vs. the `Block_Maximum_Size`, and fail if it is larger.
