### ISSUE TITLE
Compression Ration when data file use a few alphabet  is bad

### ISSUE THREAD

**Issue by shulib** [facebook/zstd#3203]
**Describe the bug**
**To Reproduce**
1. Downloads data 'file which contains only 104 size  two characters which its ascii 0x00 and 0x01  '
2. Run '...' with flags 'without flags'
3. Scroll up on the log to '....'
 the error is: 
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
     1      0      64   B       104   B  1.625   None  try78__1_2.zst
literal section compressed to raw
 **Expected behavior**
I expect that the literal section to be compressed by Huffman or FSE.
if I do that handily - I got after decompress and run with log 
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
     1      0      29   B       104   B  3.586   None  try78__1.zst
the file decompressed successfully
I expect to larger compression ration in that case! 
 - OS: linux
 - Version 1.52 latest
 - Compiler gcc
 - Flags  - no flag 
 - Other relevant hardware specs -not relevant
 - Build system -Makefile
The spec is https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.m
[try77_1.zst.txt](https://github.com/facebook/zstd/files/9134667/try77_1.zst.txt)
d

**Comment by shulib** [comment]
the file I sent not correct, but the example is correct

**Comment by terrelln** [comment]
@shulib try compressing with a higher compression level.

At lower compression levels we use heuristics to decide whether or not to use Huffman compression. One of those is based on the size of the literals buffer. Since in most data, the size of the Huffman header outweighs any gains for small data.

If you have many samples of data of a similar nature, you could also try using dictionary compression. That will remove the cost of representing the Huffman header in the frame, because it will be in the dictionary.

I'm going to close this issue, but please re-open if you have further questions!

**Comment by shulib** [comment]
a. I tried to compress with higher lever and got a same result
b. If I have few alphabet symbols (less then 64 (6 bits Huffman length)  - I took only 2!!) - Huffman code for every symbol takes less the 8 bits even when 
I have a  uniform probability each of them. so, for big enough literal stream we get a better compression then raw (even we add a tree).
