### ISSUE TITLE
Passthrough on short files fails

### ISSUE THREAD

**Issue by cgbur** [facebook/zstd#3210]
**Describe the bug**
When trying to use the decompression passed through functionality on files of 0, 1, or 2 bytes the decompressor fails to read enough bytes to understand the context and quits instead of just copying the bytes to the output. This means if you have small files and are trying to use `zstdcat` for all of them, the very small files will fail and not be written to the output.

**To Reproduce**
```fish
echo | zstd -df
echo 1 | zstd -df
echo 12 | zstd -df
echo 123 | zstd -df
```
```fish
echo | zstdcat
echo 1 | zstdcat
echo 12 | zstdcat
echo 123 | zstdcat
```
output
```
zstd: /*stdin*\: unknown header 
zstd: /*stdin*\: unknown header 
zstd: /*stdin*\: unknown header 
123
```

**Expected behavior**
Zstd and gzip support decompression passthrough where the bytes will simply be copied to the output as-is when the following conditions are met:
1. if a file is present that is not in a known format
2. the `-f` flag is present
3. the output will be written to stdout

example
```fish
❯ echo hello there | zstd -df
hello there
```

gzip on the failure cases produces the correct output
```fish
echo | gzip -df
echo 1 | gzip -df
echo 12 | gzip -df
echo 123 | gzip -df
```
```

1
12
123
```

**Screenshots and charts**
Linux x86 - self installed from repo

**Comment by terrelln** [comment]
Thanks for the report, we'll fix this for the next release!

**Comment by terrelln** [comment]
Basically, we read 4 bytes, then if we don't see any magic numbers we recognize, we will go into pass-through mode if we are writing to stdout and `-f` is passed:

https://github.com/facebook/zstd/blob/466e13f7225387a4276738f421378396595a5d4a/programs/fileio.c#L2385-L2386

The fix is to also go into pass-through mode if the file is less than 4 bytes and if pass-through mode is enabled (in https://github.com/facebook/zstd/issues/3211 we'll talk about changing the conditions for enabling pass-through mode, but not consider it for this issue). The relevant checks are here:

https://github.com/facebook/zstd/blob/466e13f7225387a4276738f421378396595a5d4a/programs/fileio.c#L2341-L2352

**Comment by cgbur** [comment]
Thanks I'll take a stab at opening a PR with a fix!
