### ISSUE TITLE
Difference of zstd and Zstandard not explained in manual page

### ISSUE THREAD

**Issue by paulmenzel** [facebook/zstd#3286]
The  manual page zstd(1) [contains the (long(?)) project name *Zstandard* once](https://github.com/facebook/zstd/blob/3b4e47092ea3e6c6d36b5e71d1f930ace4870e51/programs/zstd.1.md?plain=1#L186). It’d be great, if it could be cleared up, when to use what term. The [RFC abstract](https://datatracker.ietf.org/doc/html/rfc8878) has:

> Zstandard, or "zstd" (pronounced "zee standard"), is a lossless data compression mechanism.

**Comment by Cyan4973** [comment]
`zstd` and Zstandard have been used interchangeably so far. There never was an intention to create a clear boundary between those names.

But it's fair to say that, over time, there are a few situations where `zstd` feels more appropriate than Zstandard, and maybe vice versa.

Typically, when it comes to the reference CLI, provided in this repository, `zstd` feels more appropriate, since it's also the command used to invoke it.
Therefore, the specific man page line you linked to should have mentioned `zstd`.
This will be fixed.

Zstandard seems more appropriate when part of some normal english sentences (as opposed to technical documentation). It is also probably a better choice to refer to the ecosystem, or even the format ([RFC 8878](https://www.ietf.org/rfc/rfc8878.html)) which is supported by many other implementations beside the reference one provided in this repository.

**Comment by paulmenzel** [comment]
Thank you.
