### ISSUE TITLE
Question - protocol of zstd

### ISSUE THREAD

**Issue by shulib** [facebook/zstd#3306]
In Spec I read in FSE- Hufman part:
"he number of symbols to decode is determined by tracking bitStream overflow condition: If updating state after decoding a symbol would require more bits than remain in the stream, it is assumed that extra bits are 0. Then, symbols for each of the final states are decoded and the process is complete." 
what is the extra bits?

**Comment by embg** [comment]
I think it's saying that if the final symbol in the stream overflows, the bits that go beyond the end of the stream are assumed to be 0.

@Cyan4973 or @terrelln can provide more context.

**Comment by Cyan4973** [comment]
Yes, that's correct

**Comment by shulib** [comment]
do you mean to the number of bits or to value of it?

**Comment by embg** [comment]
The extra bits have value = 0. The number of extra bits may be greater than 0.

**Comment by shulib** [comment]
Why do we need this assumption? 
the symbol already read.

**Comment by Cyan4973** [comment]
> Why do we need this assumption? the symbol already read.

Indeed, this is an implementation detail, 
more for people willing the understand what's the resulting value of the state in the reference implementation.

But since the last symbol is already read, this last state value will not be used again.
So the state value could be anything, it would not matter.
