### ISSUE TITLE
Protocol question

### ISSUE THREAD

**Issue by shulib** [facebook/zstd#3316]
when jump table field is exist what should be the smallest regenerated_size value? because if we take for example regenerated_size==5 than it could not split evenly in the 3 streams but regenerated_size 4 comply the spec formula.

what about regenerated_size=0?

**Comment by terrelln** [comment]
@shulib I don't think that there is a minimum size. `regenerated_size=0` should work. Obviously, it is inefficient and probably shouldn't be used in practice. But it should work.

I'd suggest generating a block with `regenerate_size=0` with 4 bitstreams, pass it to the decoder, and see if it accepts it. It should accept it.

The only constraint I could think of is if zstd required that Huffman compression shrinks the data. But IIRC the format doesn't specify any such constraint.

You can use this function to run only the literals decoder:

```c
#include <zstd.h>

size_t ZSTD_decodeLiteralsBlock(ZSTD_DCtx *dctx, const void *src,
                                size_t srcSize, /* note : srcSize < BLOCKSIZE */
                                void *dst, size_t dstCapacity,
                                const streaming_operation streaming);

int decompress(uint8_t* dst, size_t dstCapacity, uint8_t const* src, size_t srcSize) {
  ZSTD_DCtx *dctx = ZSTD_createDCtx();
  if (ZSTD_isError(ZSTD_decompressBegin(dctx)))
	return 2;
  size_t const ret = ZSTD_decodeLiteralsBlock(dctx, src, srcSize, dst, dstCapacity, not_streaming);
  if (ZSTD_isError(ret)) {
    fprintf(stderr, "error: %s\n", ZSTD_getErrorName(ret));
    return 1;
  }

  fprintf(stderr, "lits size = %zu\n", ret);
  for (size_t i = 0; i < ret; ++i) {
    fprintf(stderr, "0x%x ", (unsigned)dst[i]);
  }
  fprintf(stderr, "\n");

  ZSTD_freeDCtx(dctx);

  return 0;
}

```

**Comment by terrelln** [comment]
Closing the issue because the question is answered, please create a new issue if you have further questions.

**Comment by shulib** [comment]
what about regeneration size =5
(5+3)/4=2
2 + 2 + 2=6> 5

**Comment by Cyan4973** [comment]
This is a good point @shulib ,

Using 4-streams instead of 1 is always detrimental to compression size.
The cost is ~7.3 bytes larger, which is significant for small data.

Therefore, we simply never use 4-streams for small quantities of literals,
and as a consequence, we never found out this corner case.

Other values which do not work are 2 and 1.
But I think that's all. 6 works. 9 works. anything above works.

We could add a requirement that, to employ 4-streams, a minimum amount of 6 literals is required.

Obviously, it's still silly to use 4-streams for 6 literals, since it's wasteful.
The only reason to employ 4-streams is to improve decompression speed through instruction level parallelism.
In our experience, a better lower-bound which makes the extra cost worthwhile would be around ~256 bytes.
