### ISSUE TITLE
please change references to HTTPS

### ISSUE THREAD

**Issue by GitMensch** [facebook/zstd#3318]
With both `grep` and via GitHub search you'll find a bunch of entries.
The one that is most visible is in the README.md - the link (currently a http-only forward) should be changed to https://facebook.github.io/zstd/#other-languages [and the two for zlib changed to https://www.zlib.net], similar the one in doc/README.md which should point to https://facebook.github.io/zstd/zstd_manual.html directly along with [lib/libzstd.pc.in](https://github.com/facebook/zstd/blob/33562c55deba8a225edaa9b18db30bbeb429247b/lib/libzstd.pc.in) which should link to https://facebook.github.io/zstd/.

Maybe someone that already signed the CLA can do that.

The most others are in the license notices for the GPL which should reference https://www.gnu.org/licenses, maybe something that can be done along with #2663.

**Comment by cwoffenden** [comment]
GitHub supports relative paths that will also take the protocol, e.g.:
```
[Emscripten](//emscripten.org)
```
Resulting in this link: [Emscripten](//emscripten.org), which takes either HTTP or HTTPS (or whatever else) from parent.

It's also possible to to this with Actions too, so that forks don't have the origin's badges and results, e.g.:
```
[![MSVC workflow](/../../actions/workflows/msbuild.yml/badge.svg)]
```
