### ISSUE TITLE
Re-initialize a `ZSTD_DStream` using the same dictionary

### ISSUE THREAD

**Issue by gyscos** [facebook/zstd#336]
In order to decode concatenated frames using a shared dictionary, the `ZSTD_DStream` context has to be re-initialized with `ZSTD_initDStream_usingDict` between each frame. The `ZSTD_DStream` object happens to already include the dictionary content in `dictSource`, however this is not public. 

This means we need to keep the original dictionary allocated just to give it to this initialization function, which could be avoided if either:
* The local dictionary copy was made public, and could be given to the `ZSTD_initDStream_usingDict`. (there is already a special code path for re-using `zstdSource`, but I don't see when it could happen with the current API)
* Streams could be re-initialized, keeping their current parameters, with a new `ZSTD_reinitDStream` or something.

Or was it on purpose to require the full dictionary on each initialization? (Maybe the fact that a copy of the dictionary exists in the context is an implementation detail, and is not part of the contract for the stable API?)

**Comment by Cyan4973** [comment]
Yes, this is a possible optimization.
And I would lean for a "soft-reset" solution.
The code has been partly prepared for it, and that's why `dictSource` exists.
(I also wanted to be sure that users could safely delete their own copy anytime, since `dictSource` is no longer part of the contract after `init`).

It sounds easy, but it will take time to properly test.

**Comment by Cyan4973** [comment]
Latest update in "dev" branch introduces `ZSTD_resetDStream()` in "experimental" section.
It's about the same as `ZSTD_initDStream()` but re-uses the same parameters as previous init.
In this case, it re-uses the same dictionary if one was defined in previous init.

The benefit is that, in contrast with `ZSTD_initDStream_usingDict()`, it doesn't need to reload dictionary.
If used frequently on a lot of small data blocks, it can make a difference, since loading a dictionary implies a startup cost.

Note that, for the time being, there is only `ZSTD_resetDStream()` available.
There is no corresponding `ZSTD_resetCStream()` yet.

I'm also wondering if the naming scheme, `resetDStream()` is explicit enough.

**Comment by Cyan4973** [comment]
For good measure, the API has been completed with an equivalent `ZSTD_resetCStream()` on the compression side (in the `dev` branch).

**Comment by Cyan4973** [comment]
New API `ZSTD_resetCStream()` and `ZSTD_resetDStream()` implemented in v1.1.0
