### ISSUE TITLE
New release version?

### ISSUE THREAD

**Issue by Neustradamus** [facebook/zstd#3427]
Dear Zstandard (zstd) team,

In first, I wish you a Happy New Year!

Can you create a new version?

Already one year since the last one: 1.5.2 (2022-01-20):
- https://github.com/facebook/zstd/releases

Thanks in advance.

**Comment by bdamascen0** [comment]
From [#3275](https://github.com/facebook/zstd/issues/3275#issuecomment-1270297418):
"We have not released 1.5.3 publicly yet. We were experimenting with a different release process where we release internally first, and publicly second. But other priorities took over and we haven't made the public release yet.

I don't know if we will call it 1.5.3 or 1.5.4, but we will make a public release later this year [2022]."

They missed the target date because it is not ready yet, but the new version is surely on the way.

**Comment by terrelln** [comment]
We're actively working on a release, and should have it out in January. We're currently working through our backlog of issues and PRs, so we don't miss any important fixes for the release.

**Comment by svenha** [comment]
@Neustradamus Now that 1.5.4 has been released, please close this issue.
