### ISSUE TITLE
Decompression of Long Range Mode compressed files can fail with applications that accept generic piped input/output 

### ISSUE THREAD

**Issue by gcflymoto** [facebook/zstd#3444]
**Describe the bug**
When using Long-Range-Mode compressed files, the decompression must include --long=X or decompression fails with

/*stdin*\ : Decoding error (36) : Frame requires too much memory for decoding 
/*stdin*\ : Window size larger than maximum : 2147483648 > 134217728 
/*stdin*\ : Use --long=31 or --memory=2048MB 

This poses challenges with black box applications as to what the input compressed file will be. For example, if using gtar and zstd to decompress arbitrary compressed archives 

zstd -9 -T0 --long=31 archive.lrm.tar
gtar --use-compress-program="zstd -d" -xvf archive.lrm.zstd.tar.zst
/*stdin*\ : Decoding error (36) : Frame requires too much memory for decoding 
/*stdin*\ : Window size larger than maximum : 2147483648 > 134217728 
/*stdin*\ : Use --long=31 or --memory=2048MB 

Another example is zutils which invokes "zstd -d" by default. 

This forces the use case like these to *always* use "zstd --long=31" even if the input compressed files did not use Long-Range-Mode. 

On the positive side, zstd does not use extra memory unless needed.
% time --portability -v zstd --force -d --long=31 archive.lrm.zstd.tar.zst
        Maximum resident set size (kbytes): 2102020

% time --portability -v zstd --force -d --long=31 archive.zstd.tar.zst
        Maximum resident set size (kbytes): 5380

% time --portability -v zstd --force -d archive.zstd.tar.zst
        Maximum resident set size (kbytes): 5380

Furthermore, I don't see any information in "zstd -l <file.zst>" to determine whether the file was compressed with LRM. This could help with configuring apps to invoke zstd with --long=X or not.

**Expected behavior**
Ideally, zstd will automatically adjust its memory to the requirements of the input compressed file.

**Comment by Cyan4973** [comment]
With this description, the `zstd` CLI is working _as intended_ .

Requiring the reservation of huge amounts of memory based on the content from an unknown source can be considered a type of DoS attack in network applications. Therefore, by default, the memory usage capped.

However, any application can opt-in to accept frames with much larger memory requirement if they want to.
That's the purpose of `-d --long=31`, and any user application can select it.
The reverse is also possible : users can restrict memory usage even more than the default capped value.

As mentioned, the `-d --long=31` setting is not going to blindly use 2 GB no matter what, it's only an authorization to use _up to_ 2 GB when that's necessarily. And since in many cases it's not necessary, the decoder will be smart enough to only use the amount of memory needed.

The memory requirement of the decoder is a direct consequence of the `Window size` setting. `Window size` is generally impacted when employing the `--long` mode, but it can be impacted by other parameters too. The source of the impact is of no importance to the decoder. What matters for the decoder is only the `Window size` value. This value is indicated directly in the compressed frame header, and can be consulted using `-lv` command.

**Comment by gcflymoto** [comment]
Thank you for the explanation @Cyan4973. We will use --long=31 to be flexible.
