### ISSUE TITLE
WebAssembly version `ZSTD_getFrameContentSize()` returns 'ZSTD_CONTENTSIZE_ERROR'

### ISSUE THREAD

**Issue by linuxaged** [facebook/zstd#3504]
wasm code:
```
bool BonApi_loadBonM(char* data, const size_t dataSize) {
    printf("loadBonM\n");
    std::vector<char> buffer;
    unsigned long long const realSize = ZSTD_getFrameContentSize(data, dataSize);
    if(realSize == ZSTD_CONTENTSIZE_ERROR || realSize == ZSTD_CONTENTSIZE_UNKNOWN) {
        printf("invalid zstd format, %lld\n", realSize);
        return false;
    }
    buffer.resize(realSize);
    printf("realSize %llu\n", realSize);
    size_t const dSize = ZSTD_decompress(buffer.data(), realSize, data, dataSize);
    printf("dSize %zu\n", dSize);
    return dSize == realSize;
}
```
CMake
```
add_library(${PROJECT_NAME}
    zstd.h
    zstddeclib.c
    API.h
    main.cpp
)
```
Build with
```
emcmake cmake -G Ninja ^
   	-DCMAKE_MAKE_PROGRAM="C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"
cmake --build .
emcc -o main.wasm libBonWasm.a --no-entry -sEXPORTED_RUNTIME_METHODS=ccall  -sALLOW_MEMORY_GROWTH -sMAXIMUM_MEMORY=4GB -s EXPORTED_FUNCTIONS=_malloc,_BonApi_loadBonM
emcc -o main.js libBonWasm.a --no-entry -sEXPORTED_RUNTIME_METHODS=ccall  -sALLOW_MEMORY_GROWTH -sMAXIMUM_MEMORY=4GB -s EXPORTED_FUNCTIONS=_malloc,_BonApi_loadBonM
emcc -o main.html libBonWasm.a --no-entry -sEXPORTED_RUNTIME_METHODS=ccall -sALLOW_MEMORY_GROWTH -sMAXIMUM_MEMORY=4GB -s EXPORTED_FUNCTIONS=_malloc,_BonApi_loadBonM
```

called by JavaScript:
```
Promise.all(
            [fetch(
              "https://casedata-new.oss-cn-hangzhou.aliyuncs.com/DYTK/P1/Model/0.BonM"
            ).then((res1) => res1.arrayBuffer())]
          )
          .then(([result1]) => {
            var arrayBonM = new Uint8Array(result1);
            let bufferBonM = Module._malloc(arrayBonM.length);
            let bonm = new Uint8Array(Module.HEAPU8.buffer, bufferBonM, arrayBonM.length);
            bonm.set(bufferBonM);


            console.log("bonm " + arrayBonM.length);

            Module.ccall('BonApi_loadBonM', null, ['number', 'number', 'number', 'number'], [bufferBonM, arrayBonM.length, 800, 600]);

          })
          .catch(function(error){
[wasm32.zip](https://github.com/facebook/zstd/files/10722961/wasm32.zip)

            console.warn(error);
          });
```

the native version works correctly with the same data.

zstd.h/zstddeclib.c  v1.5.0
emscripten v3.1.31
[whole project files](https://cowtransfer.com/s/8203de1725374b)

**Comment by Cyan4973** [comment]
`ZSTD_getFrameContentSize()` returns a `unsigned long long` type, 
aka it can't be a negative number.

Assuming some kind of conversion like `(int)` happens, implicitly or not, then indeed some of the results of `ZSTD_getFrameContentSize()` will be interpreted as negative numbers,
with notably `ZSTD_CONTENTSIZE_ERROR` corresponding to `-2`
(aka: the decoding operation of the frame header was unsuccessful).
But note that many other numbers will end up in negative territory, or be otherwise transparently truncated, so this is not a relevant operation to do.

The `ZSTD_CONTENTSIZE_ERROR` scenario should have been correctly captured in your early code : 
```
    unsigned long long const realSize = ZSTD_getFrameContentSize(data, dataSize);
    if(realSize == ZSTD_CONTENTSIZE_ERROR || realSize == ZSTD_CONTENTSIZE_UNKNOWN) {
        printf("invalid zstd format, %lld\n", realSize);
```
so it should have taken this branch.

But apparently it did not, and what happens exactly when the code get compiled by the `wasm` compiler, or how is it interpreted by the `wasm` machine, this is not clear. All sorts of side effects might happen in this world, and this repository is not specialized in `wasm` questions and answers. 

The only thing we can say is that `ZSTD_getFrameContentSize()` does not return a negative number, and if it seems it does, then something is wrong either with the code, or with the limits of the target language.
After which point, this becomes a question for another repository or scope.

**Comment by linuxaged** [comment]
sorry, my fault, the data downloaded with async fetch not yet finished before calling zstd decompress
