### ISSUE TITLE
Building 1.5.4 with clang-cl and lld-link fails because faulty linker checks in CMake.

### ISSUE THREAD

**Issue by tru** [facebook/zstd#3522]
**Describe the bug**

Build 1.5.4 with clang-cl/lld-link on Windows with CMake you get this:

```
11:19:41 lld-link: warning : ignoring unknown argument '-z'
11:19:41 lld-link: error : could not open 'noexecstack': no such file or directory
```

**To Reproduce**

`cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_LINKER=lld-link ..\build\cmake && ninja`

**Expected behavior**
The problem is the check here:
https://github.com/facebook/zstd/blob/dev/build/cmake/CMakeModules/AddZstdCompilationFlags.cmake#L74

This is in the block for Clang, but checks linker flags by calling the compiler. On Windows the compiler is not used as the linker like on Unix systems.

It needs to be a check around this to correctly detect lld-link or re-tool the linker checks to use `CMAKE_LINKER` instead to perform these checks.

**Screenshots and charts**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Compiler: Clang-cl 15.0.7
 - Build system: CMake

**Comment by terrelln** [comment]
@tru we would really appreciate a PR to fix this issue, since it is hard for us to reproduce, because we don't naturally use Windows. We use `CHECK_LINKER_FLAG()` [here](https://github.com/facebook/zstd/blob/1be95291a89160be121c987c2e385331a65a4a0e/build/cmake/CMakeModules/AddZstdCompilationFlags.cmake#L37), maybe we're calling it wrong.

We are preparing a new release in the next few weeks, so if we get a PR by then we can include it in the release.

**Comment by tru** [comment]
Sent a PR for this now.
