### ISSUE TITLE
src size exactly 1<<17 give me an error 

### ISSUE THREAD

**Issue by shulib** [facebook/zstd#3615]
Hi, 
when I run zstd tool  I get the following error:
"  check srcSize >= (1<<17) failed, returning ERROR(srcSize_wrong): "
the block is block 1 
[zst.bin.file.zst.txt](https://github.com/facebook/zstd/files/11231870/zst.bin.file.zst.txt)
number 19  ( I add suffix .txt to put it here).
according to spec max size is 128k without define window size for compressed and decompressed data.
so - why it is >=?
thanks
Shuli,

**Comment by Cyan4973** [comment]
Check again with a more recent version (`v1.5.5`) of `zstd`

**Comment by shulib** [comment]
Thanks, 
It solved this problem.

**Comment by Cyan4973** [comment]
These types of blocks (compressed block of size exactly 128 KB) were not and are still not generated by the reference `zstd` implementation (even the updated specification allows them).
As a consequence, this use case can only be generated by a 3rd party `zstd` compressor.

The decoder limitation was fixed in `v1.5.4`, but versions `v1.5.2` and before are affected by this limitation.

Consequently, if you plan on releasing a compressor in an environment which cannot guarantee that all reachable decompressors are necessarily `v1.5.4` or higher, please refrain generating compressed blocks of size exactly 128 KB, even if they are allowed by the spec, as some decompressors may incorrectly flag them as corrupted.

By the way, this is not the only limitation to respect in order to remain compatible with the broader ecosystem of deployed `zstd` decoders. For a more complete list or known limitations, please have a look at this document : 
https://github.com/facebook/zstd/blob/dev/doc/decompressor_errata.md
