### ISSUE TITLE
Should multithreading be enabled by default in cli?

### ISSUE THREAD

**Issue by cgbur** [facebook/zstd#3635]
Ive read #2364 but I don't think this quite applies. I am wondering why when no threading is specified in the cli, it defaults to `T1` instead of `--single-thread`? I feel like not specifying the threading option should default to single-threaded, and specifying `T1` should be required to enable multithreading. The default `T1` currently consumes a huge anount of memory compared to the single threaded and only runs 3-5% faster on my system with some test files. However `zstd` is supposed to be fast so going for the extra speed is understandable.

In the past it has not been a big concern for me but recently discovered massive memory usage when setting custom window logs. 

**As a follow up question**: I am very confused on why `T1` vs `--single-thread` makes such a huge difference in memory usage for the below example. I would expect the memory usage to be ~2x?

```sh
# 541 MB
zstd -9 1_gb_log_file -c --zstd=wlog=25 
# 46 MB
zstd -9 1_gb_log_file -c --zstd=wlog=25 --single-thread
```

I am looking for a discussion on this and not trying to be pushy in asking for a change. Any past context would be appreciated.

**Comment by Cyan4973** [comment]
`-T1` was selected as default because : 
- The memory requirement grows (roughly) linearly with the nb of parallel worker threads. `-T1` should be fine for most systems, while higher counts, including the automatic `-T0`, have a higher chance of triggering an OOM error.
- There is a general expectation that a CLI process shall consume ~1 thread, and therefore can max out 1 core. Employing more cores is certainly possible, but doing so "by default" could overload a currently active server that could need the power for other business tasks. 
- Note that it's always possible to override the binary-defined default with environment variable `ZSTD_NBTHREADS`. See https://github.com/facebook/zstd/tree/dev/programs#passing-parameters-through-environment-variables for details.
- The compressed output of `-T1` is binary identical to any other `-T#` setting. This is considered desirable for predictability.

The usual cons are : 
- One might prefer to employ many threads by default, perhaps because it's running on a local single-user desktop system, and when compression is employed, it's assumed that there is probably not much else going on on the same system. It's also assumed that there is plenty of local memory available to complete the compression process without a hiccup.
    + Note that's why environment variable `ZSTD_NBTHREADS` exists. 
- `--single-thread` uses less memory than `-T1`. It can be preferable in memory constrained environments.
    + Note that it's possible to compile `zstd` without multithreading support, in which case, it will necessarily default to `--single-thread`. There is often an overlap between "memory constrained" and "limited multithreading support", but that's not a guarantee.
    + `--single-thread` is a bit slower. For example, on a local M1 laptop, compressing `enwik9` with default compression level costs <=3.5sec with `-T1`, vs >=4.0sec with `--single-thread`, a ~15% difference.
    + The generated compressed payload is different. This can be problematic for some systems and tests which expect stability whatever the nb of threads employed for compression. A good example of such use cases are package managers.
        * Note that the compression ratio itself is essentially equivalent. But at a binary comparison level, there are differences here and there.

As usual, it's a trade off, so it's always possible to have a personal usage which differs from the generic baseline and would prefer different defaults. That's why these options remain controllable, some via environment variables, most via the command line.
When working in a command line environment, a relatively universal way to enforce one's default is to employ `alias`, bundling a bunch of default parameters with `zstd` when invoking `zstd` on the command line.
For the more courageous ones, many build options exist, which can be selected at compilation time. But this would be a completely different discussion.

**Comment by cgbur** [comment]
Thank you for the detailed response that seems very reasonable. On the follow up question, any particular reason `T1` has this geometric growth and single thread does not? Also why the `T1` is so much larger in magnitude?

![image](https://user-images.githubusercontent.com/9002722/235536877-d9badfcb-4bf4-4a35-b42d-792a0de78c5a.png)

**Comment by cgbur** [comment]
Following up on how to roughly calculate the memory usage for a given window log and threading parameter.

```python
SLACK_BUFFERS = 3


def mem(wlog, num_workers):
    target_section_size_log = max(20, wlog + 2)
    target_section_size = 1 << target_section_size_log

    sections_size = target_section_size * num_workers
    slack_size = target_section_size * SLACK_BUFFERS
    window_size = 1 << wlog

    round_buf_cap = max(window_size, sections_size) + slack_size
    out_buf_cap = target_section_size

    return round_buf_cap + out_buf_cap


print(mem(wlog=22, num_workers=1))  # 80MiB
print(mem(wlog=24, num_workers=1))  # 320MiB
print(mem(wlog=26, num_workers=1))  # 1.3GiB
```

I am curious what the `+2` happening to window log is for? Does this mean that each thread is getting `4*window_size` as input to do compression on?

I set `SLACK_BUFFERS` to three because its `2 +  (target prefix > 0)` which i believe will be true most of the time. Are these slack buffers for loading up extra so there is no waiting for input output?

**Comment by Cyan4973** [comment]
In multi-threading mode, a majority of the memory budget is currently consumed by buffers.
If you want multiple threads to work in parallel without interference, each one must have its own set of buffer to write into and read from.

So, what is this buffer size ?
Each worker thread works on a job unit, the buffer size derives directly from it.
A typical job unit is 4x the window size.
There are exceptions to this rule (`--long` mode), and job size can even be directly controlled (`-B#`), but that's a typical default situation, so let's use that for the illustration.
For a window size of 64 MB, that means a job unit of 256 MB.
Hence a worker thread will operate on a 256 MB chunk of input .
On top of that, it will generate a "certain amount" of output, which is yet unknown before compression is completed. But the maximum is bounded. So it needs another write buffer of size `ZSTD_compressBound(inputSize)`, which is a little more than 256 MB.

So there you have it, each worker thread will need a bit more than 8x window size just for buffers. On top of that, each worker thread necessitates a compression context which carries the search structures for match detection. That also costs memory. But buffers are typically the lion share of the memory budget.

One buffer to read, one buffer to write, that's what's needed by an active worker thread in order to compress. But there is more.

When ingesting data, there is a duration during which data is "just" ingested. This operation requires an ingestion buffer. This buffer will _then_ become an input buffer for the next compression thread, so it has the same size (256 MB). It might be filled (and it should) _in parallel_ with the worker thread(s). In which case, the memory budget for this buffer comes _on top of_ the memory budget already required by each worker thread.

As can be guessed, the same situation happens on the output : once a worker thread is done, it "releases" its input buffer, and move on to the next job in the queue, but the generated output buffer will remain in memory as long as it's not entirely flushed to output. So, on top of the previous memory budget, there is an output buffer, of size `ZSTD_compressBound(inputSize)`, which will hang around for a while  (exact duration depending on I/O performance).

So, we are now at 8x window size + 1 context per worker thread, + another 8x window size for the I/O thread. That's 16x window size for a single worker thread. If window size is 64 MB, just these buffers amount to a bit more than 1 GB. And of course, there are additional sources of costs beyond just these buffers.

Now, note that the above values are large because we start from a 64 MB window size, which is not a "default" one. In most cases, window size is in the 2 to 4 MB range, resulting in substantially smaller memory budgets. In the graph above, this results in a 45 to 77 MB memory budget, which is not "cheap", but is not as extravagant as 1 GB, and is generally okay for modern platforms with a typical RAM budget of multiple GB.

Single-thread mode is significantly more frugal, because it doesn't have all these buffers. It's progressing block by block throughout the input (128 KB at a time) and immediately produces and requires flushing of the producing block. There's no preloading, it's not keeping around a write buffer for lazy flushing. 
This comes at the cost of performance, though it's not huge (~-15%), so it could be debated. More importantly, for reasons too complex to detail here, `--single-thread` mode will produce a different compressed output than `-T1`, whereas `-T1` produces exactly the same output as any other `-Tn`, resulting in directly comparable outcomes. Both these properties explain why `-T1` is the default for `zstd` when multi-threading is available.

In streaming mode, the compression context has to cache input up to 1x window size in order to find matches. In the example above, that's what ends up costing the majority of the memory budget when pushing the window size to 64 MB. But once again, 64 MB window size is an unusual setup, not a "default" one. And even that budget can be "delegated" when memory addresses remain stable (aka entire buffer-to-buffer compression, or `mmap` input file).

**Comment by cgbur** [comment]
All making sense now, thank you very much!
