### ISSUE TITLE
8-States FSE implementation

### ISSUE THREAD

**Issue by pingladd** [facebook/zstd#3649]
**Is your feature request related to a problem? Please describe.**
The default FSE implementation is 2-States. I implemented the 8-States, which gives us consistent uplift (up to 6%) across levels on various workload sizes (1MB - 70MB). Meanwhile, it brought a slight deficit on some compress levels during decoding. 
For the unit tests, I passed the "fuzzer.exe" test from the FiniteStateEntripy repository. However, I run into some issues when testing the "fuzzer.exe" in this repository. Here might be the reasons:
1. 8-States might generate a couple more compressed bytes, which are not equal to the specified testing sizes.
2. Here needs a mechanism to decide when to use 2-States other than 8-States. The matching pair of encode and decode is needed. 

**Describe the solution you'd like**
I would like to know what are the next steps.
Is it possible to submit a Pull request?

**Comment by yoniko** [comment]
Hi @pingladd,
In order to maintain backwards and RFC (https://www.rfc-editor.org/rfc/rfc8478) compatibility the FSE states count in Zstd is locked to 2.
While increasing state count may indeed result in improved performance on newer platforms, afaik this is not something we can change without breaking compatibility.
If however, you can increase the state count without causing breaking changes, I'll be interested in seeing the PR.

**Comment by pingladd** [comment]
Hi @yoniko,
I got it, and thanks! Would it be possible to create a fork and put my 8-States code somewhere available for public discussion?

**Comment by embg** [comment]
> Hi @yoniko, I got it, and thanks! Would it be possible to create a fork and put my 8-States code somewhere available for public discussion?

You are welcome to create a fork. Just be aware that if you make a breaking change to the wire format, we cannot merge your code into the facebook/zstd repository.
