### ISSUE TITLE
[Question] Does zstd decompression provide support for Chained IOBuf

### ISSUE THREAD

**Issue by akankshamahajan15** [facebook/zstd#3652]
Does zstd decompression provide support for Chained IOBuf?
Thanks

**Comment by felixhandte** [comment]
Hi @akankshamahajan15,

This repo hosts the zstd reference implementation, which is built in C and has no understanding of C++ concepts like `folly::IOBuf`. The API you get here is [`ZSTD_decompressStream()`](https://github.com/facebook/zstd/blob/v1.5.5/lib/zstd.h#L878-L893) which more or less operates on raw buffers. (Although there are detailed/advanced parameters like [`ZSTD_d_stableOutBuffer`](https://github.com/facebook/zstd/blob/v1.5.5/lib/zstd.h#L2356-L2386) that can affect how zstd operates on those buffers.)

However, `folly` does offer a [compression API](https://github.com/facebook/folly/blob/main/folly/compression/Compression.h#L179-L181) that takes and produces `IOBuf`s. (Are you already using this API?) This API will always handle chained `IOBuf`s in the sense that it will never miss data that was provided to it in chained `IOBuf`s. However, it may `coalesce()` the buffers internally rather than operate on them in chained form.

Does that answer your question?
