### ISSUE TITLE
incorrect nbSeq writing in zstd_compress_superblock.c 

### ISSUE THREAD

**Issue by ip7z** [facebook/zstd#3667]
zstd_compress_superblock.c
```
    if (nbSeq < 0x7F)
        *op++ = (BYTE)nbSeq;
```
zstd_compress.c:
```
    if (nbSeq < 128) {
        *op++ = (BYTE)nbSeq;
```

**Comment by Cyan4973** [comment]
It's not a "bug", in the sense that generated data is not incorrect.
It can be argued that it's less efficient though, because for the value `nbSeq==127` specifically, `if (nbSeq < 0x7F)` will use the 2 bytes format, while the 1 byte format would have been enough.
But both formats are valid, and will be correctly decoded to the same value.
