### ISSUE TITLE
How to use ZDICT_trainFromBuffer() to generate a dict file?

### ISSUE THREAD

**Issue by leviathan0992** [facebook/zstd#3675]
Hi all

I found the zstd has implemented ZDICT_trainFromBuffer() to train a dictionary from an array of samples but I want to know if that can generate a dictionary file.

**Comment by Cyan4973** [comment]
Well, `ZDICT_trainFromBuffer()` itself generates dictionary data into a buffer,
but if you save the resulting data into a file,
then yes, you have a dictionary, equivalent to the one generated by the `zstd --train` CLI.

**Comment by leviathan0992** [comment]
@Cyan4973 Thank you very much for your response.

I completely understand what you explain. Then if  I have many arrays of string as samples, I can not pass them into ZDICT_trainFromBuffer() once.  so How do I invoke ZDICT_trainFromBuffer() more times and only generate one dictionary file?

**Comment by Cyan4973** [comment]
All samples must be provided as a single continuous buffer.
Hence the name `trainFromBuffer()`.
This is documented in the interface : 
https://github.com/facebook/zstd/blob/v1.5.5/lib/zdict.h#L190

**Comment by leviathan0992** [comment]
@Cyan4973   If I have a 10G file as a sample and I must read it into memory? and has any more elegant way to do that?

**Comment by Cyan4973** [comment]
If you have a 1GB file, it probably doesn't need a dictionary.

Dictionaries are only effective for small files.

**Comment by leviathan0992** [comment]
@Cyan4973 

ok, I see. 

And do you have more details about the function ZDICT_trainFromBuffer? For example, what is the size limit for the `samplesBuffer`  parameter that is passed in?

**Comment by Cyan4973** [comment]
It's all explained in the doc : 
https://github.com/facebook/zstd/blob/v1.5.5/lib/zdict.h

There is a no "hard" limit,
but there are general rule of thumbs which tend to work well enough.
In general, a good amount of data for training is likely to be in the 10 MB - 100 MB range.
It's a soft recommendation rather than a strict limit.

**Comment by leviathan0992** [comment]
@Cyan4973 Thank you very much for your response

**Comment by romanovj** [comment]
> If you have a 1GB file, it probably doesn't need a dictionary.
> 
> Dictionaries are only effective for small files.

Is'it possible to speed up zram decompression with something like dictionary?

**Comment by Cyan4973** [comment]
This is at least theoretically possible. zram blocks are about the right size for dictionaries to be effective.

But the next issue is that a dictionary must be trained, so one needs a training data set.
And for the dictionary to be effective, data must have some "general regularities", a structure, or a sequence of bytes, that tend to generally be present in most samples.

For zram, it's unclear if such generality exists. Maybe it does, and one will need a representative dataset to observe it. But I'm not sure if a "representative dataset" for zram actually exists.

**Comment by romanovj** [comment]
> This is at least theoretically possible. zram blocks are about the right size for dictionaries to be effective.
> 
> But the next issue is that a dictionary must be trained, so one needs a training data set. And for the dictionary to be effective, data must have some "general regularities", a structure, or a sequence of bytes, that tend to generally be present in most samples.
> 
> For zram, it's unclear if such generality exists. Maybe it does, and one will need a representative dataset to observe it. But I'm not sure if a "representative dataset" for zram actually exists.

I just thought that zram_dedup is a thing, so why there's no zram_dict? 

I will try to dump memory pages as files and see what I can theoretically have.

**Comment by leviathan0992** [comment]
@Cyan4973 I know from reading the documentation that if I compress the data, there will be a header close to 20 bytes. If I want to compress small data by dictionary compression, such as a string of 32 bytes with repeated prefixes, can the zstd solve my situation?

**Comment by Cyan4973** [comment]
32-bytes inputs are on the low side, even for dictionary compression.

There are multiple sources of header cost, minimum frame + block header cost is ~10 bytes, which is a major budget for such tiny targets.
The magic-less format would help reduce this cost by 4 bytes, but that's still a lot of header for such a small target, on top of producing a frame incompatible with general 
`zstd` decoders

Our size recommendations for dictionary compression is that it can be expected to work fine for input sizes down to ~100 bytes. Below that point, and especially below 50 bytes, it's increasingly harder to get compression benefits, due to multiple sources of small fixed costs.
