### ISSUE TITLE
[Question] For static (non-malloc'd) streaming compression, when estimating CStream size, is estimated src size the total size to be compressed, or the max of each time ZSTD_compressStream2 called?

### ISSUE THREAD

**Issue by xzn** [facebook/zstd#3678]
As titled:

Assuming doing streaming compression like so:

```
srcSize = <some_number>;
cParams = ZSTD_getCParams(compLevel, srcSize, 0);
wsSize = ZSTD_estimateCStreamSize_usingCParams(cParams);
CStream = ZSTD_initStaticCStream(CStream, wsSize);
rc = ZSTD_compressStream2(CStream, cur_output, cur_input, ZSTD_e_continue);

...
```

Is srcSize supposed to be the total size of all cur_input passed to ZSTD_compressStream2, or the max of each one passed?

Thanks in advance for any help!

**Comment by Cyan4973** [comment]
I'm assuming you are re-using the `CStream` state for multiple rounds of compression,
and that you are on a memory-constrained device,
hence the use of static allocation,
and the choice of `ZSTD_estimateCStreamSize_usingCParams()` instead of `ZSTD_estimateCStreamSize()`,
which main advantage is to allow setting a much tighter memory budget if one can bound `srcSize`.

One missing operation in this example is to set the compression parameters to `cParams` as defined line 2.
Now, you have your parameters settled for future compressions, and you know these parameters are properly covered by the reserved memory budget,

After that, there is no "right" or "wrong" value of `srcSize`.
`srcSize` was only needed to settle on `cParams`.

As a general rule of thumb, I tend to recommend to set `srcSize` to the size of the largest input you expect to deal with.
But it also is the largest memory budget to expect.

Now, if you select a different (smaller) `srcSize`, it's not going to crash. It will just (potentially) select different parameters, that may end up being less optimal for large inputs. 
For example, if you are asking for parameters for a `srcSize == 16 KB`, you will probably end up with parameters focused on a Window size of 16 KB. But if data to compress is actually 1 MB, then a 16 KB window size pretty limitative, and results in worse compression ratio. But also in a much tighter memory budget. And also, the selected parameters might actually be more optimal for small inputs <= 16 KB. 
Therefore, in situations where there are a lot of small inputs and just a handful of large ones, it *might* be worthwhile to "sacrifice" the compression ratio of the few "large" samples and prefer a better fit for the majority of "small" samples, on top of a tighter memory budget.

Of course, another option is to update compression parameters between each compression, in order to have more adjusted parameters for each sample. But since the size of the state was decided at the beginning, you should never ask for more memory than what was statically assigned at the beginning.
That's why it's often simpler to just set parameters once and let the state run continuously with the same parameters.
