### ISSUE TITLE
Add installing to the tests

### ISSUE THREAD

**Issue by QBos07** [facebook/zstd#3691]
Currently the automated test doesn't include any test that check if the installing acctually works

This shoud be a job for every platform you want to support. (MSYS2, Cygwin, ubunut, etc...)

Another way would be to let the test programms compile agains a local install in a temp directory or so, wich woud be automicly done.

Reason is that there might be something wrong with the installation process on cygwin because the use this patch: [zstd-1.5.5-cygwin-build.patch](https://cygwin.com/cgit/cygwin-packages/zstd/tree/zstd-1.5.5-cygwin-build.patch) and I think something as easy as copying some files shoud be supported on as many platforms as possible

**Comment by Cyan4973** [comment]
`zstd` supports staged install via the [standard `DESTDIR` environment variable](https://www.gnu.org/prep/standards/html_node/DESTDIR.html).
This is the recommended way to test the installation script on a local system.

Staged install tests are also run in CI, but it's not possible to test all possible environments there, so special corner cases are bound to happen.

If the installation script can be improved with a patch, we'll be glad to accept a PR.

From what I can see in the cygwin patch, the main modification is that the `filter()` function see its arguments reserved, likely in order to support wildcard, presumably because `cygwin` unames are not "stable" as they bundle the version number.

**Comment by QBos07** [comment]
Did some more research and found out that MSYS2 also use a similar naming.
The `uname` result for Cygwin and MSYS2 are like this:
```
MSYS_NT-{windows version}-{windows build}
CYGWIN_NT-{windows version}
```
Another possible fix for that is the [MSYS2-Way](https://github.com/msys2/MINGW-packages/blob/df108959125910416ca3a7ca9e33dd1ad7590f25/mingw-w64-zstd/pzstd-c%2B%2B11.patch) by using `uname -o` wich woud output `Cygwin` and `Msys` but they since then moved on to use cmake.
So I woud like to know wich build system is your most supported because I am maintaing zstd as a companion library in crosstool-ng wich builds it from source for cross-compilation? (currently using make)

**Comment by Cyan4973** [comment]
At this time, our primary build system is `make`.
