### ISSUE TITLE
The block size from ZSTD_compressBlock_targetCBlockSize API is not accurate as targetCBlockSize

### ISSUE THREAD

**Issue by kongsuozt** [facebook/zstd#3696]
**Describe the bug**
I am trying to port ZSTD as a compressor for EROFS, this fs need a fixed 4KB compressed blocks output. I checked code, there is only **ZSTD_compressBlock_targetCBlockSize** seems match this request. After I build a ZSTD binary and use **--target-compressed-block-size=4096** paremter to compress an input file, then I parsed each block in this file with a python script, the print show that each block size is not less or equal to 4096, size of many blocks are large than 4096.

0085C979: 007fcc     block header: last : 0, type: compressed block, block size:4089
0085D975: 008024     block header: last : 0, type: compressed block, block size:**4100**
0085E97C: 007fdc     block header: last : 0, type: compressed block, block size:4091
0085F97A: 007fbc     block header: last : 0, type: compressed block, block size:4087
00860974: 007fd4     block header: last : 0, type: compressed block, block size:4090
00861971: 009be4     block header: last : 0, type: compressed block, block size:**4988**
00862CF0: 007f94     block header: last : 0, type: compressed block, block size:4082
00863CE5: 007f9c     block header: last : 0, type: compressed block, block size:4083
00864CDB: 007f9c     block header: last : 0, type: compressed block, block size:4083
00865CD1: 007fa4     block header: last : 0, type: compressed block, block size:4084
00866CC8: 007f84     block header: last : 0, type: compressed block, block size:4080
00867CBB: 00dc14     block header: last : 0, type: compressed block, block size:**7042**
00869840: 0cba1c     block header: last : 0, type: compressed block, block size:**104259**
00882F86: 007fd4     block header: last : 0, type: compressed block, block size:4090
00883F83: 003f24     block header: last : 0, type: compressed block, block size:2020
0088476A: 007f94     block header: last : 0, type: compressed block, block size:4082
0088575F: 007f7c     block header: last : 0, type: compressed block, block size:4079
00886751: 007f7c     block header: last : 0, type: compressed block, block size:4079

**To Reproduce**
1. Downloads zstd git code
2. build a zstd bin
3. compress a file with --target-compressed-block-size=4096 arg
4. check each block size with a script

**Expected behavior**
block size should try to equal or less than the --target-compressed-block-size paramter.

**Screenshots and charts**

**Additional context**
[block parse script]
```python
#!/usr/bin/python3
#coding=utf-8

import os,sys,re,struct
import subprocess

if len(sys.argv) < 2 or len(sys.argv) > 3:
	print("using it like: zstd_block_parse.py [input file]")
	exit(-1)

in_file = sys.argv[1]

single_segment     = 0
frame_content_size = 0
dictinary_id       = 0
window_size        = 0
block_size         = 0
last_block         = 0
content_checksum   = 0

fcs_size_table     = [0, 2, 4, 8]
type_str           = ["raw block", "RLE block", "compressed block","Reserved"]


if os.path.exists(in_file) == 0:
	print("in_file: " + in_file + " not exisit")
	exit(-1)

def decode_frame_header(header) :
	global dictinary_id
	global frame_content_size
	global single_segment
	global content_checksum

	dictinary_id       = (header & 3)
	single_segment     = (header >> 5) & 1
	fcs_flag           = (header >> 6) & 3
	content_checksum   = (header >> 2) & 1
	if single_segment == 1 :
		fcs_size_table[0] = 1
	else :
		fcs_size_table[0] = 0
	frame_content_size = fcs_size_table[fcs_flag]

	print('                     dictionary id flag      : ' + str(dictinary_id))
	print('                     content checksum flag   : ' + str(content_checksum))
	print('                     single segment flag     : ' + str(single_segment))
	print('                     frame content size flag : ' + str(fcs_flag) + " --> " +
								  str(frame_content_size) +
	      ' bytes')
	return

def decode_window_size(window) :
	global window_size

	exponent = window >> 3 & 31
	mantissa = window & 7
	window_base = (1 << (exponent + 10))
	window_size = window_base + (window_base >> 3) * mantissa
	print('                     exponent                : ' + str(exponent))
	print('                     mantissa                : ' + str(mantissa))
	print('                     window_size             : ' + str(window_size))
	return

def decode_block_header(header) :
	global block_size
	global last_block

	last_block = header & 1
	btype      = (header >> 1) & 3
	block_size = header >> 3
	string = 'last : ' + str(last_block) + ", type: " + type_str[btype]
	if btype == 1 :
		string     = string + ', repeat size:' + str(block_size)
		block_size = 1;
	else :
		string = string + ", block size:" + str(block_size)
	return string

#open and get header of each part
with open(in_file, "rb") as zstd :
	offset = 0
	print("OFFSET    CONTENT    MEANING")
	print("-------------------------------------------------------------")
	while True:
		buf = zstd.read(16)
		if len(buf) != 0 :
			b_tmp = buf[0:4]
			magic = int.from_bytes(b_tmp, 'little')

			# check if it is frame header
			if magic == 4247762216 : #0xFD2FB528
				print("-------------------------------------------------------------")
				print('%08X: %08x   frame header magic' % (offset, magic))
				offset = offset + 4
				b_tmp  = buf[4:5]
				frame_header = int.from_bytes(b_tmp, 'little')
				print('%08X: %02x         frame header :' % (offset, frame_header))
				decode_frame_header(frame_header)
				offset = offset + 1

				if single_segment :
					# TODO:
					offset = offset + 0
				else :
					b_tmp  = buf[offset : offset + 1]
					window = int.from_bytes(b_tmp, 'little')
					print('%08X: %02x         window :' % (offset, window))
					decode_window_size(window)
					offset = offset + 1

				if dictinary_id :
					b_tmp  = buf[offset : offset + dictinary_id]
					dic_id = int.from_bytes(b_tmp, 'little')
					print('%08X: %08x   dictionary ID' % (offset, dic_id))
					offset = offset + dictinary_id

				if frame_content_size :
					b_tmp    = buf[offset : offset + frame_content_size]
					fcs_size = int.from_bytes(b_tmp, 'little')
					print('%08X: %08x   frame content size' % (offset, fcs_size))
					offset = offset + frame_content_size
				zstd.seek(offset)
				continue

			# parse each block
			b_tmp = buf[0:3]
			block_header = int.from_bytes(b_tmp, 'little')
			print('%08X: %06x     block header: ' % (offset, block_header) + decode_block_header(block_header))
			offset = offset + 3 + block_size
			if last_block and content_checksum :
				offset = offset + 4
				
			zstd.seek(offset)
		else :
			break

**Comment by Cyan4973** [comment]
Indeed, `_targetCBlockSize` API doesn't _guarantee_ a maximum compressed block size,
it only _tries_ to roughly fit into the requested budget
(though the few very large variations from the target size are more surprising to me).
That's a different contract.

**Comment by kongsuozt** [comment]
@Cyan4973  Yes, Some output frames are realy very large than target size. May over 100KB compared with 4KB target. 
BTW, can ZSTD team help to develop a api which can guarantee max compressed block size limit to target set? 
I have tried in LZ4, it have a API **LZ4_compress_destSize** which seems match this requirement. From following log that most output size matches target, only very few blocks have size less than target(mainly end of input stream)

> src size:298196 ->  4551, dstsize: 4096, ret: 4096
src size:293645 ->  4337, dstsize: 4096, ret: 4096
src size:289308 ->  4488, dstsize: 4096, ret: 4096
src size:284820 ->  4716, dstsize: 4096, ret: 4096
src size:280104 ->  4303, dstsize: 4096, ret: 4096
src size:275801 ->  4682, dstsize: 4096, ret: 4096
src size:271119 ->  4518, dstsize: 4096, ret: 4096
src size:266601 -> 139244, dstsize: 4096, ret: 4096
src size:127357 -> 127357, dstsize: 4096, ret: **2288**
Processing firmware/w2_bt_fw_usb.bin ...src size:655368 ->  5054, dstsize: 4096, ret: 4096
src size:650314 ->  4461, dstsize: 4096, ret: 4096
src size:645853 ->  4406, dstsize: 4096, ret: 4096
src size:641447 ->  4626, dstsize: 4096, ret: 4096
src size:636821 ->  4589, dstsize: 4096, ret: 4096
src size:632232 ->  4791, dstsize: 4096, ret: 4096
src size:627441 ->  4769, dstsize: 4096, ret: 4096
src size:622672 ->  4670, dstsize: 4096, ret: 4096
src size:618002 ->  4750, dstsize: 4096, ret: 4096
src size:613252 ->  4474, dstsize: 4096, ret: 4096
src size:608778 ->  4437, dstsize: 4096, ret: 4096
src size:604341 ->  4594, dstsize: 4096, ret: 4096
src size:599747 ->  4808, dstsize: 4096, ret: 4096
src size:594939 ->  4951, dstsize: 4096, ret: 4096
src size:589988 ->  4604, dstsize: 4096, ret: 4096
src size:585384 ->  4406, dstsize: 4096, ret: 4096
src size:580978 ->  4755, dstsize: 4096, ret: 4096
src size:576223 ->  4549, dstsize: 4096, ret: 4096
src size:571674 ->  4495, dstsize: 4096, ret: 4096
src size:567179 ->  4597, dstsize: 4096, ret: 4095
src size:562582 ->  4596, dstsize: 4096, ret: 4096
src size:557986 ->  4440, dstsize: 4096, ret: 4096
src size:553546 ->  4319, dstsize: 4096, ret: 4096
src size:549227 ->  4477, dstsize: 4096, ret: 4096
src size:544750 ->  4571, dstsize: 4096, ret: 4096
src size:540179 ->  4539, dstsize: 4096, ret: 4096
src size:535640 ->  4781, dstsize: 4096, ret: 4096
src size:530859 ->  4746, dstsize: 4096, ret: 4096
src size:526113 ->  5247, dstsize: 4096, ret: 4096
src size:520866 ->  5244, dstsize: 4096, ret: **4095**
src size:515622 ->  4867, dstsize: 4096, ret: 4096
src size:510755 ->  4807, dstsize: 4096, ret: 4096
src size:505948 ->  4358, dstsize: 4096, ret: 4096
src size:501590 ->  4574, dstsize: 4096, ret: 4096
src size:497016 ->  4909, dstsize: 4096, ret: 4096
src size:492107 ->  4782, dstsize: 4096, ret: 4096
src size:487325 ->  4580, dstsize: 4096, ret: 4096
src size:482745 ->  4741, dstsize: 4096, ret: 4096
src size:478004 ->  4786, dstsize: 4096, ret: 4096
src size:473218 ->  4552, dstsize: 4096, ret: 4096
src size:468666 ->  4629, dstsize: 4096, ret: 4096
src size:464037 ->  4953, dstsize: 4096, ret: 4096
src size:459084 ->  4589, dstsize: 4096, ret: 4096

**Comment by Cyan4973** [comment]
`_destSize()` is a capability which is almost unique to LZ4.

Achieving the same thing with `zstd` is going to be difficult, because, in contrast with LZ4, one cannot simply calculate in advance and for sure the final size of a compressed block: one can only evaluate it, and then try it. In cases where actual compressed size of the block ends up being larger than expected, aka larger than limit, one needs to retry, or amend the block definition. This is not impossible, but it costs additional cpu budget, which is often incompatible with fast speed requirements. And also some additional memory budget while at it.

Therefore, while it's not impossible, achieving these objectives properly, and maintaining them with a continuous high level of quality, is a serious investment. I'm afraid I don't see our team having the bandwidth to ensure the completion of such a project in the near future.

**Comment by hsiangkao** [comment]
Hi Cyan, I've finished deflate fixed-sized output compression recently (just almost < 1.5kLOC to match zlib ability) and EROFS will support deflate algorithm (because there are already several deflate hardware accelerators on the market) as the 3rd supported algorithm in the near future in addition to LZ4 and LZMA to fulfill end-user needs.

About zstd, even though I'd like to support zstd as the 4th algorithm but I'm not sure how to proceed this (IMHO, zstd format is designed complex than deflate and consider that zstd official encoder is not planned to support this in the near future [I've already raised this request 2 years before], maybe _someday_ I will write another zstd encoder for this requirement but I don't know).

Alternatively we could compress data with fixed-sized length (like 128kb) into several filesystem blocks (like 4kb) and allow the last block not completely full but it becomes suboptmal (it totally works, just near-near-suboptimal). Although I think it's matchable to btrfs and f2fs (as well as maybe zfs) on-disk approaches, I don't tend to support zstd in this way this since it sounds suboptimal.

BTW, `I am trying to port ZSTD as a compressor for EROFS, this fs need a fixed 4KB compressed blocks output.` which is **NOT** true now since EROFS supports 4k*n cluster sizes to contain compressed data not just **4KB**, which means each cluster can be multiple of 4k blocks. For example, you could keep compressed data as (24kb, 8kb, 16kb, 12kb, 8kb, 4kb,  24kb, ...), the last filesystem block of each filesystem cluster may not be completely full as I mentioned above.

**Comment by kongsuozt** [comment]
@Cyan4973  thanks for your explain. So, even if we can't get accurate size of output package. But there are still many frames which have size very larger than target size. Could you please help to fix this problem. If the output size is just near target size or a bit larger than target size. Then I think we can do some other work such as try to reduce target size a bit to meet 4K target.

@hsiangkao Also thanks for your help about introducing ZSTD for EROFS. Why we want to try zstd with output 4k size is that currently our hardware only support this size.

**Comment by Cyan4973** [comment]
> EROFS supports 4k*n cluster sizes to contain compressed data not just 4KB, which means each cluster can be multiple of 4k blocks.

I think the main difference between most other compressed filesystems (BtrFS, ZFS, SquashFS, etc.) and EroFS is that other filesystems target a fixed _uncompressed_ size, then discover how much it can be compressed, and then allocate an appropriate nb of 4 KB blocks for storage purpose,
whereas EroFS targets a fixed _**compressed**_ size, and then discovers how much uncompressed data can fit into this budget.

`zstd` is already used in the first scenario,
but not yet in the second scenario.

When you state "EROFS supports 4k*n cluster sizes to contain compressed data", I read it as still being in the second scenario, i.e. there is a target compressed size, even if this target is no longer limited to 4KB only.

**Comment by hsiangkao** [comment]
> > EROFS supports 4k*n cluster sizes to contain compressed data not just 4KB, which means each cluster can be multiple of 4k blocks.
> 
> I think the main difference between most other compressed filesystems (BtrFS, ZFS, SquashFS, etc.) and EroFS is that other filesystems target a fixed _uncompressed_ size, then discover how much it can be compressed, and then allocate an appropriate nb of 4 KB blocks for storage purpose, whereas EroFS targets a fixed _**compressed**_ size, and then discovers how much uncompressed data can fit into this budget.
> 
> `zstd` is already used in the first scenario, but not yet in the second scenario.
> 
> When you state "EROFS supports 4k*n cluster sizes to contain compressed data", I read it as still being in the second scenario, i.e. there is a target compressed size, even if this target is no longer limited to 4KB only.

Nope, if you dig into these filesystem internals, Btrfs, ZFS, F2FS, etc are all compressed into their filesystem blocks (typically 4kb or 1kb), and the last filesystem block of each compression cluster can partially leave empty (0).  Because all generic filesystems allocate space in filesystem blocks (typically 4kb, they don't have a way to allocate space in a sub-filesystem block way, IOWs, you cannot allocate 1kb space with 4kb block-sized filesystems).  EROFS also keeps compressed data in filesystem blocks as Btrfs, ZFS, F2FS and the main difference is that EROFS supports byte-granularity uncompressed data (but you could still leave uncompressed data aligned within a fixed unit, such as 128kb or whatever), and because of this EROFS now supports rolling-hash content-defined chunking since v6.1 (but Btrfs, ZFS, F2FS, even SquashFS cannot support CDC since their uncompressed data is aligned to a fixed size (for example, squashfs is 128kb).)

Only SquashFS is special, because its compressed data is not aligned to any unit (IOWs, byte-granularity compressed data), that is the main reason why its image size is smaller than Btrfs, ZFS, F2FS, etc. but that is I/O ineffecient since physical disks are organized in fixed-sized physical blocks much like filesystem blocks.

**Comment by hsiangkao** [comment]
> there is a target compressed size, even if this target is no longer limited to 4KB only.

I need to clarify that "EROFS supports 4k*n cluster sizes to contain compressed data", here `n` is not a fixed number (although for LZ4/LZMA/DEFLATE, `n` is usually a fixed number which given by users as a command line argument). Each EROFS compression cluster can have different `n`, no need to fix a unique `n` for all EROFS compression clusters.  So even EROFS can work as Btrfs, ZFS, F2FS, etc (but unlike squashfs), just compression ratio loss compared to `fixed-sized compressed size`.
