### ISSUE TITLE
correct way to use streaming with small buffers?

### ISSUE THREAD

**Issue by ahenning** [facebook/zstd#371]
Changing the streaming_compression.c example to use a small input buffer size e.g. buffInSize=64 causes a segfault here. What would be the correct way to use streaming with small buffers?

**Comment by Cyan4973** [comment]
If you change `buffInSize` to a smaller amount, you will have to change [line 79](https://github.com/facebook/zstd/blob/dev/examples/streaming_compression.c#L79).

This line reads as many bytes as suggested by `ZSTD_compressStream()`.
This amount is guaranteed to be `<= ZSTD_CStreamInSize()`, so it works with original example.
But if you manually set `buffInSize` to a smaller size, it's also necessary to read less bytes, to not overflow `buffIn`.
 Typically, read `buffInSize` instead of `toRead`.

Modifying `buffInSize` is not expressly supported by the example.
But I could update the example to safely handle such case.

**Comment by ahenning** [comment]
Thanks, the new line 84 solves it:
`if (toRead > buffInSize) toRead = buffInSize;   /* Safely handle when buffInSize is manually changed to a smaller value */`
