### ISSUE TITLE
Zstd command line argument parsing edge cases

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#375]
A couple of edge cases in the zstd CLI have popped up while I'm fixing pzsd's CLI:

1.  `zstd -Do` is accepted and equivalent to `-oD`, but it should probably be disallowed, since both options require arguments.  Zstd parses them as `zstd -Do <dict> <outfile>` and `zstd -oD <dict> <outfile>`.
2.  POSIX allows the arguments of short options to be in the same token or separated, so `zstd -ofile` should be the same as `zstd -o file`.  So any short option that requires an argument must be the last argument in its argument set.  According to POSIX `zstd -of` is writing to the file `f`.  According to the letter of the standard, options with arguments must stand alone, but I belive getopt allows combined options, so long as the option that requires an argument is last.
3.  If negative compression levels are supported in the future, the command line could get confusing, since `-22` is the highest level and `--22` is very low.  If a short option was given to the compression level, it might be less confusing.  E.g.  `-l22` vs `-l-22`, both of which are POSIX compliant, and equivalent to `-l 22` and `-l -22`, or `--level 22` and `--level -22`.

**Comment by Cyan4973** [comment]
These are good points @terrelln .
Although they suppose we fully adopt `getopt()` convention.

It's not a bad objective in itself, but : 
- `getopt` is a posix library, so it introduces portability issues outside of posix (and potentially even within posix universe, judging by prior experience with posix libraries on multiple Unix types and versions).
- I'm especially worried if behaviors and combinations which work fine today on `zstd` are broken by new convention.

#### Regarding dependency : 

I'm okay to get closer to getopt(), but not to blindly include a posix dependency within `zstdcli.c` (note : `pzstd` is free to do so, its own portability requirement is less strict).

Currently, we handle system-specific dependencies by grouping them inside `utils.h`.
Its job is to ensure OS detection in order to include the right dependency, and potentially some glue code around it.
There is typically one path for posix (well, sometimes several...), one path for windows, and one path for neither. This is this last path which puzzles me. Sometimes, we can get away with simply removing the functionality (for example, no `-r` recursive mode for such target), but here it's not possible : we cannot "not parse" the command line.

So an all-encompassing solution would be to re-implement getopt() locally.
Re-implementing all features may introduce too much complexity for its usefulness. So maybe we can get away with a subset.

This is in essence what `zstdcli.c` does now.
We can upgrade it to make it closer to getopt().

#### Regarding behavior

`-Do` and `-oD` are indeed strange corner cases, that I don't expect to be of any use currently. We can modify them to work properly.

> According to the letter of the standard, options with arguments must stand alone, but I belive getopt allows combined options, so long as the option that requires an argument is last.

This sounds fine.
I believe it's possible to modify `zstdcli.c` to provide such restriction.

> According to POSIX zstd -of is writing to the file f

This one is more embarrassing. I've been using `-of` as it felt natural to me, so it's present in many tests, but that's not a problem. I mostly hope that no one else has been doing so, because this behavior would be changed in a breaking way.

If prior mechanism is implemented, it means `-of` becomes forbidden, and must be replaced by `-fo`.
That's already an inconvenience, but hopefully a manageable one, which can receive a proper error message.

Whereas making `-of` valid and meaning "write to `f`" sounds one step too far. It risks creating unforeseen issues for anyone using such construction now, since it is valid and has a different meaning currently.

> If negative compression levels are supported in the future, the command line could get confusing, 

I agree.
We can introduce a new short/long option `-l` / `--level` for this.
We still need to support current way of setting (positive) compression levels, such as `-9`. It's a basic expectation of every `zstd` user, plus it's the way it works for other compressors. So `-l` is effectively optional for positive levels.

**Comment by Cyan4973** [comment]
Added in `dev` branch :
protection for commands requiring argument.
Now they must be followed by argument.

Situations such as `-Do` or `-oD` will now generate an error message.
`-of` is invalid too.
though `-fo` still works, if it's followed by another separate argument providing output file name.

**Comment by Cyan4973** [comment]
fixed into v1.1.0
