### ISSUE TITLE
memory leak in function 'UTIL_mirrorSourceFilesDirectories'

### ISSUE THREAD

**Issue by JoraGevorgyan** [facebook/zstd#3764]
The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)
memory is allocated [here](https://github.com/facebook/zstd/blob/1c007e64b85248b989aa7a9bea50897aae8fdb41/programs/util.c#L1262) may left w/o free in case of [exit](https://github.com/facebook/zstd/blob/1c007e64b85248b989aa7a9bea50897aae8fdb41/programs/util.c#L62) from macro ['CONTROL'](https://github.com/facebook/zstd/blob/1c007e64b85248b989aa7a9bea50897aae8fdb41/programs/util.c#L1269C13-L1269C13)

**Comment by Cyan4973** [comment]
It's indeed technically a leak, though one with a very low reach.
I guess the expectation here is that, since the program ends immediately on reaching `exit()`, the OS will reclaim all memory allocated by the process, whether it was explicitly `free()` or not.

Let's see how we can nonetheless improve this, hopefully in a way which doesn't burden code's maintenance.
