### ISSUE TITLE
spec: Empty compressed blocks not allowed

### ISSUE THREAD

**Issue by klauspost** [facebook/zstd#3775]
**Describe the bug**

It appears the decoder rejects compressed blocks with 0 sequences and 0 literals. This makes sense, since it is a waste of resources, but it is not part of the format specification.

The closest I could find is:

> if `(Number_of_Sequences == 0)` : there are no sequences. The sequence section stops immediately, FSE tables used in Repeat_Mode aren't updated. Block's decompressed content is defined solely by the Literals Section content.

There is no mention that if there are no literals the decode should fail.

I think it belongs in the [compressed block](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#compressed-blocks) section:

> The results of the two sections are then combined to produce the decompressed data in [Sequence Execution](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#sequence-execution). 

-> 

> The results of the two sections are then combined to produce the decompressed data in [Sequence Execution](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#sequence-execution). _If both provide no output the block must be rejected as invalid._

Does this make sense, or did I miss it somewhere in the spec?

**Comment by klauspost** [comment]
Ah... ~It could be extra block data failing [this check](https://github.com/facebook/zstd/blob/dev/lib/decompress/zstd_decompress_block.c#L723)... Closing until I've clarified.~

No. This doesn't appear to be it.

**Comment by klauspost** [comment]
This appears to be something that has changed, with a `MIN_CBLOCK_SIZE`. Latest version appear to decode this.

Closing, since it appears these blocks now decode.

**Comment by Cyan4973** [comment]
Indeed,
this is a known limitation of older decoder versions.

It's documented here : 
https://github.com/facebook/zstd/blob/dev/doc/decompressor_errata.md#compressed-block-with-0-literals-and-0-sequences

It has been fixed since.

Even though newer versions of `zstd` decode such blocks, it's recommended to avoid generating such block, in order to improve compatibility with the installed base of `zstd` decoders. Besides, as you noticed, it's just a wasteful way to represent "empty", so it's good practice for the encoder to select a more compact representation.
