### ISSUE TITLE
Check data is compressible

### ISSUE THREAD

**Issue by OkobaPatino** [facebook/zstd#3779]
What is the fastest way to check a data is compressible?
I can compress it and see if the output is reduced, but it seems wasteful, as the real output is already written.
Is there any flag or custom way to ask ZSTD to check the content for being compressible as fast as possible?

**Comment by Cyan4973** [comment]
`zstd` is already making such check internally.
If you were to test `zstd` speed on incompressible data, you would notice that it doesn't spend much time on such data, and moves on quickly.

**Comment by OkobaPatino** [comment]
Yes, I noticed that, but it tries the whole data. For example, for a 1GB of MP4, it takes near 1 second on my computer. But we knew that it could not compress it—maybe 1 or 2 kilobytes. So I was thinking about compressing a sample of it, like 1 MB, and if it cannot be compressed, I will rule out the whole file. It can lead to false flags, but that is acceptable. Your point is that ZTSD moves on, but it writes the data in the new frame. My need was to ask if there is a way to tell ZTSD to just ignore the compression, or, in this case, write a new frame.

**Comment by Cyan4973** [comment]
The risk of false positive is pretty high when testing just the first kilobytes.
Therefore, `libzstd` doesn't use this strategy.

If one wants to ground the decision to compress a 1 GB file based on the performance of the first block,
one can do that explicitly, by testing compression on first few KB,
either as a separate first pass, or by flushing a first block when employing the streaming API,
but that's indeed a decision making strategy which happens outside of `libzstd`.

For reference, there is a "compression detector" inside BtrFS which uses essentially the same strategy. When enabled, it has been shown to reduce compression ratio by a sizable amount, precisely because it skips compression too easily.

**Comment by OkobaPatino** [comment]
Thank you for the note.
One question, as you benchmarked everything. How much of the time of compression is writing of the compressed data? Is there any benefit to tell ZSTD to compress but not write? For example using it in a preparation step to just check for compressible or tasks like that.

**Comment by Cyan4973** [comment]
If you mean `zstd` the CLI, then one can avoid I/O write by just redirecting the flow to a byte counter via `stdout`:
`cat file | head -c 10000 | zstd | wc -c`
Then it becomes just a copy into a buffer. Same for the API.
In which case, this copy operation is just a minor part of the already fast compression speed in presence of incompressible data (and negligible one in presence of normally compressible data).

**Comment by OkobaPatino** [comment]
No I was talking about the API.
For API, the writing part of the compressed data is negligible then? Do you have a napkin estimation of it? IS there any worth into customizing the compression code to prevent writing in such cases?

**Comment by Cyan4973** [comment]
Probably not,
but that's difficult to provide an estimation.
Trying it to clarify the potential uptake is non-trivial development work.

**Comment by OkobaPatino** [comment]
That was what I was looking for.
Thank you for your help.
