### ISSUE TITLE
Compressing/Decompressing Small Data With Dictionaries

### ISSUE THREAD

**Issue by kklouzal** [facebook/zstd#378]
Does ZStd provide the ability to further tune a dictionary file after each successive compression and decompression?

I feel this could further optimize compression ratios and decompression speeds.

**Comment by Cyan4973** [comment]
Keep in mind that a dictionary must be re-distributed after being updated, to keep decoder and encoder synchronized.
And yes, this is possible, I know of at least one solution along these lines, which works very well,
but it's an external module, requiring network transaction.
`zstd` is part of it, rather than the other way round.
