### ISSUE TITLE
In function ZDICT_trainBuffer, filePos is built but is not used

### ISSUE THREAD

**Issue by rockeet** [facebook/zstd#381]
In function ZDICT_trainBuffer, `filePos` is built but is not used, what is the intention? should delete it?

**Comment by Cyan4973** [comment]
Indeed.
This table tracks borders between samples.
It was built to take this information in considering while creating the dictionary.
The experimentation wasn't a success, so most of its code was removed, but this part remained, because it is expected to be useful again in a future update.

**Comment by rockeet** [comment]
I see, thanks! Another question: in many cases, the selected fragment has a length limit, and there may have better matches cover the cutting point, have you planned to write an algorithm for this case?

**Comment by Cyan4973** [comment]
In such case, fragments are supposed to be "joined" at a later stage of the algorithm.
It mostly works, but there are still edge cases which are not properly covered.
That's something that can still be optimized a bit.

You can observe the result by using `--train -v`.
It will provide a short list and sample view of the best fragments at the end.
In many cases, best fragments are > length limit, because they are combined fragments.

**Comment by Cyan4973** [comment]
added in comment in latest "dev" branch to explain `filePos` status

**Comment by rockeet** [comment]
@Cyan4973 Very thanks for you explain!
