### ISSUE TITLE
Disable auto vectorization of xxhash64, when AVX512 is present. 

### ISSUE THREAD

**Issue by TocarIP** [facebook/zstd#3819]
AVX512 adds support for `VPMULLQ` instructions, which makes is possible to vectorize `XXH64_update`.  Here is a minimal reproducer where clang already vectrozies it with avx512 enabled: https://godbolt.org/z/cnM3986dx . Unfortunately some architectures (e.g skylake) have a very significant latency (uops.info report 15+ cycles), so this makes `xxhash` ~2x slower. Trivial benchmark shows `BM_hash/16M 1.29ms ± 3%` vs `BM_hash/16M 2.74ms ± 4%`. We already disable vectorization for xxhash32 if sse4 is present, so we should probably do the same for xxhash64 and avx512.

**Comment by Cyan4973** [comment]
> We already disable vectorization for xxhash32 if sse4 is present, so we should probably do the same for xxhash64 and avx512.

Indeed,
this seems like the same issue,
and we should probably use a similar solution.

**Comment by TocarIP** [comment]
Someone asked me about AMD offline so might as well post here. On genoa (Zen4) AVX512 is actually ~30% faster  ( 1135871 ns/op vs 885935 ns/op).

**Comment by Cyan4973** [comment]
OK, so it makes the situation a bit less clear,
since `avx512` is now sometimes beneficial, sometimes detrimental.
It probably opens the door towards offering a user choice on this topic.

However, it doesn't remove the question of "what's a good default",
and if I read the situation correctly, it seems that disabling `avx512` for `xxh64` remains a reasonable default at this point in time.

**Comment by TocarIP** [comment]
Regression on Intel is bigger than gain on AMD, so disabled by default makes sense. Using the same `XXH_ENABLE_AUTOVECTORIZE` to allow opt-in is probably the best.

**Comment by Cyan4973** [comment]
https://github.com/Cyan4973/xxHash/pull/924
