### ISSUE TITLE
Compressing files (and licences)

### ISSUE THREAD

**Issue by GuillaumeHolley** [facebook/zstd#405]
Hi there,

I have an MIT-licensed program/library in which I would like to use ZSTD to compress files I generate. The ZSTD library is BSD-licensed but the command line utility to compress files is GPL v2. I am not really good with licenses but if I am right, if I want to use the functions of fileio.c/h (command line utility) to compress the files I generate, I need to change my license from MIT to GPL v2 right? If so, why does the license of the command line utility is different from the rest of the library?

Thank you for your time and help.

Best,
Guillaume

**Comment by GuillaumeHolley** [comment]
Related question: Is there any way to compress files directly from the library (zstd.h) without using the code of the command line utility?

**Comment by terrelln** [comment]
All of Zstandard is now under the BSD license as of version 1.0.0.  I see there are some residual comments claiming that the CLI files are GPLv2.

See the [LICENSE](https://github.com/facebook/zstd/blob/dev/LICENSE) and [PATENTS](https://github.com/facebook/zstd/blob/dev/PATENTS) files.

**Comment by Cyan4973** [comment]
It used to be that Zstandard project _was_ using a dual-license : 
- BSD for library (`/lib` directory)
- GPLv2 for everything else

The reason for this choice is that only the library is thoroughly tested to be included into 3rd party programs. The others files are meant to be compiled in their own context. They can be used for inspiration, but borrowing them directly to be integrated into another program/context is likely to trigger untested problems and/or limitations.

As a consequence, I would recommend using functions from `lib/zstd.h` rather than `programs/fileio.h`.

Anyway, since v1.0 and moving under Facebook Open Source program, the entire project is now BSD licensed. There are a few relics of older era here and there, that are going to be cleaned by @terrelln patch #414 .

**Comment by GuillaumeHolley** [comment]
Thanks for the clarifications, it helped a lot!
