### ISSUE TITLE
zstd 1.5.5+ has worse performance on Graviton2 nodes than v1.4.4

### ISSUE THREAD

**Issue by aidar-stripe** [facebook/zstd#4075]
**Describe the bug**
`zstd -T128 -b` shows performance degradation compared to `1.4.4` version on AWS Graviton2 i4g.16xlarge instance. 
Tested on ubuntu 20.04 (zstd: `1.4.4`) focal and ubuntu 24.04 (zstd: `1.5.5`) noble.

**Expected behavior**
Similar or better performance on newer versions

**Additional context**
```
i4g.16xlarge (graviton2)
instance-name-stripped:~$ zstd --version
*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
instance-name-stripped:~$ zstd -T128 -b
 3#Synthetic 50%     :  10000000 ->   3231065 (3.095), 227.1 MB/s ,1000.5 MB/s

i4g.16xlarge (graviton2)
instance-name-stripped:~$ zstd --version
*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***
instance-name-stripped:~$ zstd -T128 -b
 3#Synthetic 50%     :  10000000 ->   3230491 (x3.096),  128.0 MB/s,  773.7 MB/s
 ```
 
Is there something that I'm missing here? Maybe the benchmark logic have changed from 1.4.4 to 1.5.5?

**Comment by Cyan4973** [comment]
On a `macos` laptop using an `arm64` `M1` cpu, I'm seeing an increase in performance between those 2 versions: 

```
v1.4.4: 3#Synthetic 50%     :  10000000 ->   3231410 (3.095), 364.3 MB/s ,1931.9 MB/s
v1.5.5: 3#Synthetic 50%     :  10000000 ->   3230847 (x3.095),  415.6 MB/s  1975.9 MB/s
```

This is for single-threaded performance.

When it comes to multi-threaded performance though, `v1.4.4` ramps up more than `v1.5.5`.
That's because job's size has increased at level 3 between `v1.4.4` and `v1.5.5` (as a side effect of Window size).
`v1.4.4` uses a `4 MB` job size, while `v1.5.5` uses a `8 MB` job size.
Therefore, `v1.4.4` will use ~2.3 threads, while `v1.5.5` will only use ~1.2 threads. This can be checked using `time`.
It doesn't matter if 128 threads are defined as available, `zstd` will never use more than that for this workload, because the workload is too small (10,000,000 bytes) to be split into more jobs.

To increase the nb of jobs run in parallel, either:
- increase the size of the sample to compress
- take control of the job's size directly

For example, using the same sample: 
```
v1.4.4: 3#Synthetic 50%     :  10000000 ->   3231065 (3.095), 687.9 MB/s ,2019.1 MB/s
v1.5.5: 3#Synthetic 50%     :  10000000 ->   3230491 (x3.096),  481.5 MB/s  1937.7 MB/s # default window size
v1.5.5: 3#Synthetic 50%     :  10000000 ->   3229201 (x3.097),  868.1 MB/s, 1932.0 MB/s # 1 MB window => 4 MB jobSize
```

Here is another example, on the same computer, using `-T128` threads and a non-synthetic sample of 1,000,000,000 bytes:
```
v1.4.4: 3#enwik9            :1000000000 -> 313717661 (3.188),2103.9 MB/s ,1226.9 MB/s
v1.5.5: 3#enwik9            :1000000000 -> 312548982 (x3.199), 2244.6 MB/s  1182.1 MB/s
```

**Comment by aidar-stripe** [comment]
Thanks for quick and detailed explanation! I've followed your advice on using enwik9 and  single threaded results make much more sense now:

 `zstd enwik9 -b`:
 ```
 1.4.4: 3#enwik9            :1000000000 -> 313417240 (3.191), 110.2 MB/s , 503.4 MB/s
 1.5.5: 3#enwik9            :1000000000 -> 312247462 (x3.203),  108.4 MB/s,  513.7 MB/s
 1.5.6: 3#enwik9            :1000000000 -> 312247462 (x3.203),  124.1 MB/s,  612.1 MB/s
 ```
 
Performance using 128 threads is still suspiciously lower on newer version though:
 `zstd -T128 enwik9 -b`:
```
1.4.4: 3#enwik9            :1000000000 -> 313717661 (3.188),4175.6 MB/s , 523.8 MB/s
1.5.5: 3#enwik9            :1000000000 -> 312548982 (x3.199), 3472.8 MB/s   512.7 MB/s
1.5.6: 3#enwik9            :1000000000 -> 312548982 (x3.199), 3663.7 MB/s   611.7 MB/s
 ```
 
 Is there still something incorrect with the way I'm testing?
 
 Adding more info on CPU in case if it is useful.
`lscpu`:
```
Architecture:                       aarch64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
CPU(s):                             64
On-line CPU(s) list:                0-63
Thread(s) per core:                 1
Core(s) per socket:                 64
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          ARM
Model:                              1
Model name:                         Neoverse-N1
Stepping:                           r3p1
BogoMIPS:                           243.75
L1d cache:                          4 MiB
L1i cache:                          4 MiB
L2 cache:                           64 MiB
L3 cache:                           32 MiB
NUMA node0 CPU(s):                  0-63
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; CSV2, BHB
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
```

**Comment by Cyan4973** [comment]
It's a side effect of the nb of jobs. The final speed is driven by the speed of the slowest thread. 

This impact was not visible on my laptop because the nb of concurrent threads there is much more limited.

This Graviton system seems to feature 64 cores, so it's advisable to keep the nb of threads to 64 or lower. That's still a lot compared to the total nb of jobs available. 

If you want the same nb of jobs in `v1.5.5` (compared to `v1.4.4`), use `--zstd=wlog=20`.

**Comment by aidar-stripe** [comment]
Thanks! I was able to achieve comparable numbers on newer versions with `zstd enwik9 -T64 -b --zstd=wlog=20`:
```
 1.5.5: 3#enwik9            :1000000000 -> 313556714 (x3.189), 4078.7 MB/s   537.0 MB/s
 ```
