### ISSUE TITLE
[Question] Do you use GPLv2 or GPLv2+?

### ISSUE THREAD

**Issue by topin89** [facebook/zstd#4132]
In process of [adding zstd support in Valgrind](https://bugs.kde.org/show_bug.cgi?id=469782), authors asked if you use GPLv2 or "GPLv2 or later". Mostly because Valgrind itself is GPLv2+, and authors prefer this license over BSD if possible.

Can you clarifiy, do you allow to license Valgrind under GPLv3 or later license? I know that you can use it in GPLv3 code using BSD license, and mostly being pedantic. Still, it would be nice to have clarification

**Comment by Cyan4973** [comment]
`zstd` is delivered with 2 licenses, and each user can select whichever is better for their need:
- GPL v2: which is primarily there to ensure clear compatibility with the Linux Kernel
- BSD 3-clauses: for eventually everything else, since BSD seems compatible with every other open source license out there.

The debate of `v2` vs `v2+` is relatively new, and it's unclear if it does really matter.
It would if our license was limited to `GPL v2 only`, and the intention was to integrate it into some`GPL v3` project.

But that's not the case: `BSD` is compatible with `GPL v3`, so there is no such limitation.

**Comment by terrelln** [comment]
As @Cyan4973 mentioned, Zstd is dual licensed under GPLv2 and BSD 3-clause. Zstd is **not** licensed under GPLv2+, but choosing the BSD license may be preferable for you, if you need GPLv2 compatibility.
