### ISSUE TITLE
Methods for FSE, huff0, xxhash32 are not exported to DLL/LIB

### ISSUE THREAD

**Issue by KrzysFR** [facebook/zstd#472]
Looking at some of the issues (like #468), I wanted to play with `FSE_xxx` or `HUFF_xxx` methods, from .NET code. But these methods are not currently exported, so I can't consume them directly via `libzstd.dll`. There are also helper methods (like xxhash, maybe some stuff from bitstream.h?) which could be helpful since they are already in the native library.

The current way to mark method as exported is with the `ZSTDLIB_API` macro, but I'm not sure if using the same macro to export FSE , huff0 or xxhash methods as well would be ideal, since people may not want to export everything by default?

Do you think that adding other macros like `FSE_API` or `HUFF0_API` would be a good compromise? We could decide whether or not these macros are define to 0 or 1 by default in the various makefiles and VS projects, while letting people who want to build custom versions decide what they want or not... (though, if exporting a method or not does not change the size of the dll, maybe it's a moot point?)

If yes, I think that the best place to define these macros would in their respective .h (`fse.h`, `huf.h`, `xxhash.h`, ..) ?

**Comment by Cyan4973** [comment]
It's not recommended to try to access `FSE_*` nor `HUF_*` methods from `libzstd`.
They are purely internal dependencies, which ideally should not be exposed.
Even if they are currently exposed, due to too permissive standard C policy in this regard, 
this will not last forever.
These internal methods can be changed anytime,
and one of these days, they might be entirely rewritten, or made completely private.

Now, it happens that currently, zstd uses fse and huff0 libraries "as is".
I stated in previous paragraph, this will probably change some day in the future, but that's the current situation.

Now if we restrict the discussion to these "autonomous" libraries (well, huff0 depends on fse to be exact), yes it makes sense to create `FSELIB_API` and `HUFLIB_API` macros, following the model of `ZSTDLIB_API`, in their respective headers `fse.h` and `huf.h`.

But don't rely on accessing them from `libzstd`. That's not part of this library contract.

**Comment by Cyan4973** [comment]
In latest `dev` update, the DLL is now compiled with visibility set to hidden by default.
Which means all symbols which have not been made explicitly public in `zstd.h` are no longer exposed.
This is of importance to gcc/clang unix users only, since Visual users already have this policy in place.

Note that the policy is only applicable to the dynamic library, not the static library.

**Comment by KrzysFR** [comment]
Ok, so as I understand you are saying that if I want to use FSE by itself, I would be better off compiling and using https://github.com/Cyan4973/FiniteStateEntropy as a windows DLL, even if the same code is probably present in libzstd.dll (but could change or even become not backward compatible at any time).

Though, I will still need to add the FSE_API macro in https://github.com/Cyan4973/FiniteStateEntropy/blob/dev/lib/fse.h and change https://github.com/Cyan4973/FiniteStateEntropy/blob/dev/Visual/VC2012/FSE/FSE.vcxproj accordingly, if I want to export the methods in "libfse.dll"

**Comment by Cyan4973** [comment]
exactly

**Comment by KrzysFR** [comment]
I have move the issue to the other repository.
