### ISSUE TITLE
Not enough memory; training on 1570 MB only...

### ISSUE THREAD

**Issue by bluezone2015** [facebook/zstd#486]
I'm training dictionary by:
./zstd --train ./train_data/* -o ./ZstdDictionary.dat
but I encountered such problem:

**Not enough memory; training on 1570 MB only...
sorting 101 files of total size 12 MB ...                             
finding patterns ... 
statistics ...                                                        
Save dictionary of size 112640 into file .//ZstdDictionary.dat** 

but the Server has enough memory:
**[xx@xx /xx/xxx/xxx/zstd/zstd-1.1.1]$ free -m
             total       used       free     shared    buffers     cached
Mem:         15758      15451        306          0         11      14593
-/+ buffers/cache:        847      14911
Swap:         2055          7       2047**

the training file is **13G**, so what the problem is, I need help, thanks

**Comment by Cyan4973** [comment]
1) Is your version of `zstd` compiled for 32 or 64-bits ?
    It can be checked using `zstd -V`.
    Only 64-bits version allows training over large amount of data.

2) The dictionary builder uses a 3rd party file which is limited to 2 GB input.
    So this is going to be the absolute limit anyway.
    We will need to change the algorithm to get rid of this limit.

3) The status also says :  _sorting 101 files of total size 12 MB ..._
    That's much less than 13 GB.
    It means that your sample set contains very large files.
    This is not recommended.

Dictionary compression only helps for small files.
On large files, the dictionary builder only uses the beginning of the file as training set, since dictionary compression is only useful for small files, or the beginning of large files.

In your training set, don't substitute multiple small files by a single concatenated version. It will not work well.

**Comment by Cyan4973** [comment]
Latest update in `dev` modify a bit program behaviour for such use cases : 
- First, it detects large samples and warns that they get truncated to 128 KB
- Second, it correctly estimates sample size, including sample capping.

**Comment by bluezone2015** [comment]
very appreciate for your answer, thanks a lot.
