### ISSUE TITLE
Simple way to add folder with files and specify a range to split?

### ISSUE THREAD

**Issue by Weej1** [facebook/zstd#500]
Hi I'm not very technical so bear with me. 
I work at a small school and we've learned that your program is a good option for compressing files to and from USB drives. My question is how do we add folders and can we set a split range ? Like when a file is more than 4GB it will divide itself at that point. I ask because recently the children went on a trip and they'd like to show their parents the videos we compiled but the file is 5GB.

I saw an article that recommended we use tar program to split files and folder and THEN run zstd but I'm not sure how to explain this process to the kids or their parents since many of the parents aren't very tech savvy - I can make a batch file of course  but I was hoping there was a "one command" approach to doing this instead of using 2 or 3 ? 

I hope I made sense. Sorry if its a bit long.

**Comment by Cyan4973** [comment]
I'm afraid this issue is not `zstd` related.

The 4 GB limit mentioned is typically File System dependent. I suspect it means your USB drive uses FAT or FAT32 FS, which feature such limitation. But if it was ext4 or ntfs for example, there would be no such restriction.

So that would be my first advise, check the file system, change it if possible.

Everything else is going to be too complex.
Command line tools are not meant for "normal" users. So it's not reasonable to expect children with no or little programming experience to tar, split, compress, merge, etc.

Moreover, movies tend to be already compressed. In general, adding a generic lossless compression layer on top of it will bring very little or no compression benefit.
