### ISSUE TITLE
Empty source inputs have ambiguous frame headers when writing content size

### ISSUE THREAD

**Issue by indygreg** [facebook/zstd#506]
(This issue is derived from indygreg/python-zstandard/issues/11.)

Calling `ZSTD_compress_advanced()` with a `srcSize=0` and `ZSTD_frameParams.frameContentSize=1` leads to an ambiguous frame header.

From `ZSTD_writeFrameHeader()`:

```
    U32   const singleSegment = params.fParams.contentSizeFlag && (windowSize > (pledgedSrcSize-1));
    U32   const fcsCode = params.fParams.contentSizeFlag ?
                     (pledgedSrcSize>=256) + (pledgedSrcSize>=65536+256) + (pledgedSrcSize>=0xFFFFFFFFU) :   /* 0-3 */
                      0;
```

If `pledgedSrcSize==0`, `singleSegment` will be `0` if `contentSizeFlag=1` because `windowSize` and `pledgedSrcSize` are `U32` and the `>` comparison fails because `-1` is wrapping. **This is possibly a bug.**

Anyway, in the current behavior, compressing an empty input while told to write content size results in `Frame_Content_Size_flag=0` and `Single_Segment_flag=0`. This is effectively the same as not writing the content size and means that the simple decompress API can't be used and we must go to streaming mode because the output size is unknown. **This defeats the purpose of writing the content size.**

If `Single_Segment_flag=1` (as I /think/ it should be for the empty input because the decompressed output most certainly fits in a single window size because it is length 0), there is still an ambiguous case as to how to decompress this. This is because `ZSTD_getDecompressedSize()` returns `0`, which can mean *content size unknown* or a content size of `0`. If you call `ZSTD_getFrameParams()` as the docs for `ZSTD_getDecompressedSize()` suggest, you don't get anything useful, as `frameContentSize=0`. So you still have an ambiguous scenario: you don't know if the content size is unknown or if the content size is 0. This means you have to use streaming decompression, which again undermines the purpose of writing the content size.

My main question in this issue is how is the empty input supposed to be handled by the simple decompression API? How are we supposed to disambiguate between content size not being written and a `0` content size?

**Comment by Cyan4973** [comment]
This is a known weakness of current API.

Indeed, on the decoding side, there is no way currently to make a distinction between `decompressed size unknown` and `decompressed size is known and is zero` (empty frame).

There is an identical issue on the encoding side : a `pledgedSrcSize` of `0` is explicitly defined as `srcSize not known` in the interface documentation. As a consequence, there is no way currently to tell the encoder to write a content size of `0` into final frame header.

Note that it is an API issue, not a compression format issue : the specification makes it possible to encode a `0` content size into frame header. 

It has not proven an important issue so far, probably because it is a corner case with limited usefulness, and also because it's still possible to decode such empty frame using the streaming API, or using an a-priori bounded maximum size. 

Of course, it's not a static situation. It's indeed possible to change the API to better support this scenario. It will require an API change, potentially a breaking one.
We can use this thread to discuss it.

A few rules : API flagged "stable" should not be changed.
This includes `ZSTD_getDecompressedSize()`.
API flagged "experimental" can be changed.
This includes `ZSTD_getFrameParams()` or `ZSTD_compress_advanced()`.

It doesn't give a solution, just some guidelines to design one.

**Comment by indygreg** [comment]
For the record, I'm likely not going to be volunteering to fix this. I'm content to document the edge case in my Python bindings and have this issue on file tracking an eventual solution. (Although one of these days I should try my hand at writing some code for the actual zstd project.)

**Comment by Cyan4973** [comment]
That's a good policy.
In parallel, I'm adding that item in the "todo" list, so that we try to come back with a solution in a future version.

**Comment by Cyan4973** [comment]
There's an updated API by @iburinoc in `dev` branch that is expected to improve if not solve this situation.

On the decompression side, `ZSTD_getDecompressedSize()` is obsoleted in favor of `ZSTD_getFrameContentSize()`. It basically works the same, but the second one is able to distinguish between a `0` content size, an unknown content size, or an error.

(note : since `ZSTD_getDecompressedSize()` is part of "stable" API, deprecation is a slow process. It starts by the existence of a (better) alternative in "experimental" API, which will be promoted to master in a later release, when it's considered fulfilling its promises).

On the compression side, `ZSTD_compress()` and equivalent will now generate a zero-size frame of known size when provided with `srcSize == 0`. Same for `ZSTD_initCStream_advanced()` when provided with both a `pledgedSrcSize == 0` and `contentSizeFlag == 1` : `0` will now means `0`, instead of `unknown`.
Note so that other variants such as `ZSTD_resetCStream()`, which have no chance to be explicit about the meaning of `pledgedSrcSize==0` will keep the current behavior which means `unknown`, in order to avoid breaking current applications. The meaning of `pledgedSrcSize==0` should be clearly described for every prototype.

Should you have time to test the new interface and provide feedback, you are very welcomed !

**Comment by indygreg** [comment]
This sounds like a promising update and on first read it looks like this will solve the problems I have in python-zstandard.

As soon as the new API is part of a released zstd, I'll likely incorporate it (it isn't a problem it is "experimental" - python-zstandard ships and compiles against an explicit version of zstd, so API stability is not a problem).

**Comment by Cyan4973** [comment]
Starting `v1.1.4`, there is a new method, `ZSTD_getFrameContentSize()`,
which is in essence about the same as `ZSTD_getDecompressedSize()`,
with additional ability to distinguish between a `0-sized` frame, 
an "unknown size" frame, and an error.

This new method starts its life in the experimental section.
We make a habit to have new methods stage through experimental section first, 
they'll join stable section later on, after being successfully validated in a few real-life deployment scenarios, in case their design require further tuning.
