### ISSUE TITLE
Failing ZSTD_createDDict in 1.1.4

### ISSUE THREAD

**Issue by luben** [facebook/zstd#609]
Minimal test case provided in https://github.com/facebook/zstd/pull/608

**Comment by luben** [comment]
also the plain buffer dictionaries are affected,

**Comment by Cyan4973** [comment]
Thanks for notification @luben .

That's an important one.
I'm very surprised that such a bug evaded all tests so far.
I was expecting `ZSTD_createDDict()` to be well tested at each commit.

In `fuzzer`, it's part of unit tests, called here : 
https://github.com/facebook/zstd/blob/bfd62277bf2c0eaf3702beee43fede08b30e67e7/tests/fuzzer.c#L271
though, arguably, it is the `_byReference()` version.

In `zstreamtest`, it's also part of unit test, called here : 
https://github.com/facebook/zstd/blob/bfd62277bf2c0eaf3702beee43fede08b30e67e7/tests/zstreamtest.c#L403

Perhaps more importantly, it is indirectly called from multiple places in `zstreamtest`, especially within the fuzzer tests (which are run thousands of times per commit), through `ZSTD_initDStream_usingDict()` : 
https://github.com/facebook/zstd/blob/bfd62277bf2c0eaf3702beee43fede08b30e67e7/tests/zstreamtest.c#L715
which internally uses `ZSTD_createDDict()` : 
https://github.com/facebook/zstd/blob/20f9c70c75bb9c6e9ea961db8b56c57484c9ffd0/lib/decompress/zstd_decompress.c#L2236

Given that all these tests pass successfully, it's impressive that such a failure remained unnoticed.
We'll have to understand what's different in the failing case, in order to add it to the test suite.

**Comment by luben** [comment]
Closing as the issue is addressed is satisfying way
