### ISSUE TITLE
1.1.4 ZSTDMT uses only 1 core in --ultra mode

### ISSUE THREAD

**Issue by StephanBusch** [facebook/zstd#639]
1.1.4 ZSTDMT uses only 1 core in --ultra mode, but MT wors with -1 to -19.
I tried to define -T2, -T4 and T8

**Comment by Cyan4973** [comment]
Yes, this part can be a bit difficult.

Loading a chunk to process in parallel costs some time and some compression ratio.

To minimize this cost, the size of chunks is by default defined as `4 * windowSize`.
`windowSize` depends on compression level.
For `--ultra -22`, it's 128 MB.
It means that a processing chunk is 512 MB.
That's quite a lot. Any file below that threshold will only use 1 thread.

There is a way to get around this.
It's possible to manually decide what the chunk size is.
This is option `-B#`, with `#` being the size.
For example `-B200M` means "chunk size of 200 MB".

There is a minimum chunk size enforced though, 
which is `1 * overlapSize`. For most compression levels, `overlapSize == windowSize / 8`,
but for `--ultra -22` specifically, `overlapSize == windowSize`, because it gives best compression ratio.
So, for `--ultra -22` the minimum size of a chunk is 128 MB.

There are some even more complex options available, such as `overlapLog`  : 
https://github.com/facebook/zstd/blob/dev/programs/zstdcli.c#L271
which makes it possible to play with `overlapSize`.
But they are not yet documented.
That's because `zstdmt` is still in experimental mode, 
we still need some time (and feedbacks like yours !) to settle its behavior.

**Comment by Cyan4973** [comment]
Next version of `zstd` will have improved documentation regarding multithreading support.
Updated documentation has been uploaded into `zstdmt` feature branch.

**Comment by Cyan4973** [comment]
Next version of `zstd` will provide multi-threading by default.
All explanations detailed above remain valid.
Documentation has been updated to reflect the changes.
