### ISSUE TITLE
Request/question : -T parameter

### ISSUE THREAD

**Issue by sebbellob** [facebook/zstd#671]
It would be nice to change the (MT) -T parameter to lowercase ,because zstdmt cant be used as external compressor with multithreading in Freearc. In my experiences Freearc dont understant uppercase characters after the -m parameter ! (after -m you can chain compression algorithms ,like this : arc a -mdelta+zstd myarc.arc mydata.dat)

Ok ,in Arc.ini it works fine ,but i need to change frequently the number of threads and it is not a good way to do that....

ZSTD/MT:
1 thread : it eats ~750 MB RAM.
2 threads : ~4 GB RAM.
The RAM consumption is non-linear ,i cant predict the required RAM. Is it normal ?
How can i calculate the required memory ?

Thanks !

**Comment by Cyan4973** [comment]
Thanks for feedback @sebbellob 

> The RAM consumption is non-linear ,i cant predict the required RAM. Is it normal ?

RAM consumption is expected to be linear starting from 2 threads.

From 1 thread to 2 threads though, there is a larger difference, especially for high compression mode, because buffers are larger for parallel processing. They are *much* larger in `--ultra` mode. (I suspect you're using `-22` in your example, which is kind of an extreme).

> It would be nice to change the (MT) -T parameter to lowercase ,because zstdmt cant be used as external compressor with multithreading in Freearc

Interesting.
We selected `-T#` because that's the way it's defined in `xz` (see https://linux.die.net/man/1/xz).
`-t` is already taken, for tests.

Another possibility could be to also support `-p#`, because it's the way it's defined in `pigz` (https://linux.die.net/man/1/pigz). `-p#` stands for "# processes", which is kind of a misnommer : we effectively multi-thread, not multi-process. But that's probably a minor nuance for command line users.
Another problem is that we already support `-p` (without argument) for "pause at the end", so this is effectively overloading this command. Looks possible though, since `-p#` and `-p` can be distinguished.

**Comment by Cyan4973** [comment]
In latest `dev` branch update,
`zstd` cli receives support for long command `--threads=#`.
It works the same as `-T#`, but the command itself needs no uppercase character.
Hope it helps for your issue with `freearc`.

**Comment by Cyan4973** [comment]
`--threads=#` command will be part of soon-to-be-released zstd v1.2.0
