### ISSUE TITLE
Does Zstandard support password compress/decompress?

### ISSUE THREAD

**Issue by arden** [facebook/zstd#752]
Does Zstandard support password compress/decompress?

**Comment by terrelln** [comment]
What do you mean by that? Zstd does not do encryption.

**Comment by Cyan4973** [comment]
This functionality is generally found at archiver level,
like @mcmilk's excellent [7-zip Zstandard edition](https://github.com/mcmilk/7-Zip-zstd)

**Comment by guptaprince** [comment]
are there any plans for archiving support in near future?( i know about mcmilk's 7z-zstd)

**Comment by Cyan4973** [comment]
Compressors and Archivers are 2 different layers of responsibility.

Sure, archivers _typically_ use compressors (though not always, see `tar`), but they have a lot more metadata to handle, such as file names, regenerating directory trees, random access, keeping track of special permissions, dates and time, inter-OS compatibility, etc. and yes, possibly encryption.
All these topics are totally out of scope for a compressor.

7zip is an archiver, it proposes all these possibilities. And can use multiple compression algorithms.
zstd is a compression algorithm, like gzip, or xz. Its goal is to be used by archivers, not to become one.

The same is true on the other side : a compressor has _many_ different use cases (see https://facebook.github.io/zstd/#references for a glimpse), and an archiver is just one of them.

**Comment by izanbf1803** [comment]
@arden Why not just compress with zstd and use another protocol to encrypt the compressed data?

**Comment by sebres** [comment]
> Why not just compress with zstd and use another protocol to encrypt the compressed data?

Because a smart encryption algorithms could encrypt only literals blocks or blocks containing raw or uncompressed data only and avoid encryption of frames with bit-stream. This way the encryption will be much faster than an encryption of whole stream. Let alone the extra overhead to pipe, all the interim buffers, write/read operations etc.

It is surely possible subsequently on the compressed stream (e. g. before it gets written ultimately), but would expect to "understand" RFC 8878 so quasi to implement parsing of stream buffer similar to zstd performing during decompression.
But such parsing will cost additional time for the analysis but also as already said for the piping etc.

Anyway it will be many times faster than encryption of whole stream and thereby no less securely than a complete encryption.

> Because zstd was created to compress very fast, but encryption is slower and many times

1. it doesn't really matter if encryption is needed;
2. but also if we'll consider compression speed only, a symmetric encryption will be faster than zstd, for instance by ca. 200MB/s zstd compression throughput, 500MB/s encryption speed with aes-256;
3. precisely because the encryption can be made many times faster inside the compression/decompression facilities (or at least in the callbacks at some layer of zstd API), due to abovementioned reasons.
