### ISSUE TITLE
Non-redistributable source

### ISSUE THREAD

**Issue by jsonn** [facebook/zstd#774]
The current licensing doesn't allow the redistribution of the examples and therefore the normal release tarballs. That's broken from a distribution perspective.

**Comment by Cyan4973** [comment]
I don't think it's a big deal.
This is standard license for `examples`.
The intention is to make it clear that `examples` are just source of inspiration, 
they are not meant to be copy/pasted and expected to work into any environment.

**Comment by jsonn** [comment]
It is a big deal. To quote LICENSE-example: 'Facebook reserves all rights not expressly granted.' No rights, most importantly, the right to redistribute them, has been granted.

**Comment by Cyan4973** [comment]
`examples` are not meant to be redistributed. They are just here to help newcomers.

So when taking the tarball content in order to include it into another product, the content has be stripped of `\examples` directory.

Which seems consistent with what happens today : distributions strip the tarball, keeping only what's useful for them.

**Comment by jsonn** [comment]
(1) It is not done in all cases. There is at least one major open source product currently looking at resolving the mess without having to manually cut the repository into pieces.
(2) The official release tarballs are not redistributable as a result. Since they are typically mirrored at least in some limited ways by many projects, it's a huge PITA. Personally I consider it bad enough to classify zstd as "stay away, not worth the pain", but YMMV. If you don't want people to redistribute the examples, don't put them in the tarball in first place.

**Comment by bmwiedemann** [comment]
All .c files in the zstd-1.3.1/examples dir have an explicit
```
 * This source code is licensed under both the BSD-style license (found in the
 * LICENSE file in the root directory of this source tree) and the GPLv2 (found
 * in the COPYING file in the root directory of this source tree).
```

Which makes it redistributable. But then it was reverted a few days later in git :-(

IMHO, BSD or GPL licenses (which come with 'AS IS' and 'NO WARRANTIES' clauses) are better for these 'inspirational' examples, because then people could see and try them more.

**Comment by jsonn** [comment]
Yes, a very permissive license ala CC0 would actually be best for those files. It is also beyond the scope of this issue. This issue is about ensuring that the releases can actually be properly copied AS IS. I'm sorry, but I have to seriously consider to advise people from not using zstd if the maintainers can't even manage to create redistributable releases. That's one of the most basic project management tasks for an open source project I can think of.

**Comment by Cyan4973** [comment]
In bigger companies, changing license is not something that a developer can decide on its own.
It takes time to get decisions, and most of the effort is invisible to users.

**Comment by jsonn** [comment]
That doesn't explain the  closed ticket...

**Comment by Cyan4973** [comment]
license for `/examples` has been updated to be the same as repository, aka BSD + GPLv2.
https://github.com/facebook/zstd/pull/821

**Comment by jsonn** [comment]
Thanks.
