### ISSUE TITLE
Compatibility with brotli dictionary + transforms

### ISSUE THREAD

**Issue by jyrkialakuijala** [facebook/zstd#804]
Consider adding compatibility with brotli dictionary and transforms. The brotli dictionary can be found from most modern computers. For example, three copies of the dictionary exists in windows: https://twitter.com/ericlaw/status/889935096467279872 

In cronet they are already considering to consolidate the dictionaries, so that one instance can be shared between all uses. This will likely come later to other platforms, too.

You will get some savings even without introducing the transforms and more dense unique (length,distance) coding, and the code is ready in zstd for that kind of dictionaries. However, you get some more if you decide to go the full way, i.e., code the words as unique distance,length pairs and decode transform-codes out of distances that exceed the word count for that length.

In my experience you get about an 8 % savings using the brotli static dictionary, and 1.5 % savings from the transforms. The transforms are about 2-3 kB of additional code complexity whereas the brotli static dictionary is about 122 kB of complexity (around 55 kB compressed).

**Comment by Cyan4973** [comment]
That's an interesting suggestion @jyrkialakuijala .
If I understand you correctly, chromium/cronet is considering to make brotli's dictionary a static asset that other services could rely upon ?

**Comment by jyrkialakuijala** [comment]
There is such consolidation going on and it makes sense: brotli is used in a few contexts, and so is woff 2.0. Having the static dictionary mapped into memory only once makes a lot of sense.

**Comment by Cyan4973** [comment]
Yes, that's a good point.

As you already mentioned, `zstd` can accept any content as "raw dictionary", so it can also be applied to brotli's dictionary.
A major difference is that `zstd` has no concept of "fields" or "dictionary entries" : the dictionary is just prepended "as is", its content can be reached anywhere through standard `offset / length` fields.

It's expected to be less dense than a dedicated list of fields with entry points. The upside is flexibility : this approach is more "universal", since any content can be prepended this way.

Going the "full way" is an interesting suggestion, though it implies a major code rework, likely impacting the compression format too. It's an interesting topic, though it must really pay off to be worth its complexity cost.

**Comment by jyrkialakuijala** [comment]
Transforms are in https://github.com/google/brotli/blob/master/c/dec/transform.h

No one has said _beautiful_ when they saw it, but it is not a lot of code for ~1.5 %.

In brotli we have support for two different kinds of dictionaries, the linear dictionaries that can get any data -- and the dictionary entry kind of dictionaries. In the current repo version only linear dictionaries can be custom dictionaries, and the static dictionary is a dictionary entry kind of dictionary. We are making this more flexible in future versions (i.e., to support the dictionary entry kind custom dictionaries, too).
