### ISSUE TITLE
Building without threading primatives

### ISSUE THREAD

**Issue by mitchblank** [facebook/zstd#819]
I am updating an environment from zstd-1.2.0 to zstd-1.3.1.  This environment is only building the library itself (not the programs) and is *not* using `ZSTD_MULTITHREAD`.  It's also not using the build system that comes with zstd but instead is compiling the files itself.

Since we're not using any of the ZSTDMT interfaces, I haven't been including the `zstdmt_*.c` files (or `threading.c`/`pool.c`)  I am trying to avoid having and dependency from the zstd library to pthreads.

In 1.2.0 this all worked fine, but now this causes linking errors:

```
Undefined symbols for architecture x86_64:
  "_ZSTDMT_freeCCtx", referenced from:
      _ZSTD_freeCCtx in libzstd.a(zstd_compress.c.o)
  "_ZSTDMT_setMTCtxParameter", referenced from:
      _ZSTD_CCtx_setParameter in libzstd.a(zstd_compress.c.o)
  "_ZSTDMT_sizeof_CCtx", referenced from:
      _ZSTD_sizeof_CCtx in libzstd.a(zstd_compress.c.o)
```

It seems that the `ZSTDMT_*` symbols are now being called from the common code even if `ZSTD_MULTITHREAD` isn't defined.  It this intended?  It is a shame that the segregation of the multithreading code seems to have broken down a bit.

**Comment by mitchblank** [comment]
I got my environment building again with this change fwiw:

```
--- zstd-1.3.1/lib/compress/zstd_compress.c.ORIG	2017-08-28 14:21:41.000000000 +0200
+++ zstd-1.3.1/lib/compress/zstd_compress.c	2017-08-28 14:29:43.000000000 +0200
@@ -175,23 +175,35 @@
     cctx->workSpace = NULL;
     ZSTD_freeCDict(cctx->cdictLocal);
     cctx->cdictLocal = NULL;
+#ifdef ZSTD_MULTITHREAD
     ZSTDMT_freeCCtx(cctx->mtctx);
     cctx->mtctx = NULL;
+#endif
     ZSTD_free(cctx, cctx->customMem);
     return 0;   /* reserved as a potential error code in the future */
 }
 
+static size_t sizeof_mtctx(const ZSTD_CCtx* cctx)
+{
+#ifdef ZSTD_MULTITHREAD
+    return ZSTDMT_sizeof_CCtx(cctx->mtctx);
+#else
+    (void) cctx;
+    return 0;
+#endif
+}
+
 size_t ZSTD_sizeof_CCtx(const ZSTD_CCtx* cctx)
 {
     if (cctx==NULL) return 0;   /* support sizeof on NULL */
     DEBUGLOG(5, "sizeof(*cctx) : %u", (U32)sizeof(*cctx));
     DEBUGLOG(5, "workSpaceSize : %u", (U32)cctx->workSpaceSize);
     DEBUGLOG(5, "streaming buffers : %u", (U32)(cctx->outBuffSize + cctx->inBuffSize));
-    DEBUGLOG(5, "inner MTCTX : %u", (U32)ZSTDMT_sizeof_CCtx(cctx->mtctx));
+    DEBUGLOG(5, "inner MTCTX : %u", (U32)sizeof_mtctx(cctx));
     return sizeof(*cctx) + cctx->workSpaceSize
            + ZSTD_sizeof_CDict(cctx->cdictLocal)
            + cctx->outBuffSize + cctx->inBuffSize
-           + ZSTDMT_sizeof_CCtx(cctx->mtctx);
+           + sizeof_mtctx(cctx);
 }
 
 size_t ZSTD_sizeof_CStream(const ZSTD_CStream* zcs)
@@ -345,20 +357,24 @@
     case ZSTD_p_nbThreads:
         if (value==0) return 0;
         DEBUGLOG(5, " setting nbThreads : %u", value);
-#ifndef ZSTD_MULTITHREAD
-        if (value > 1) return ERROR(parameter_unsupported);
+        if (value > 1) {
+#ifdef ZSTD_MULTITHREAD
+            if (cctx->nbThreads != value) {
+                if (cctx->staticSize)  /* MT not compatible with static alloc */
+                    return ERROR(parameter_unsupported);
+                ZSTDMT_freeCCtx(cctx->mtctx);
+                cctx->nbThreads = 1;
+                cctx->mtctx = ZSTDMT_createCCtx_advanced(value, cctx->customMem);
+                if (cctx->mtctx == NULL) return ERROR(memory_allocation);
+            }
+            cctx->nbThreads = value;
+#else
+            return ERROR(parameter_unsupported);
 #endif
-        if ((value>1) && (cctx->nbThreads != value)) {
-            if (cctx->staticSize)  /* MT not compatible with static alloc */
-                return ERROR(parameter_unsupported);
-            ZSTDMT_freeCCtx(cctx->mtctx);
-            cctx->nbThreads = 1;
-            cctx->mtctx = ZSTDMT_createCCtx_advanced(value, cctx->customMem);
-            if (cctx->mtctx == NULL) return ERROR(memory_allocation);
         }
-        cctx->nbThreads = value;
         return 0;
 
+#ifdef ZSTD_MULTITHREAD
     case ZSTD_p_jobSize:
         if (cctx->nbThreads <= 1) return ERROR(parameter_unsupported);
         assert(cctx->mtctx != NULL);
@@ -369,6 +385,7 @@
         if (cctx->nbThreads <= 1) return ERROR(parameter_unsupported);
         assert(cctx->mtctx != NULL);
         return ZSTDMT_setMTCtxParameter(cctx->mtctx, ZSTDMT_p_overlapSectionLog, value);
+#endif
 
     default: return ERROR(parameter_unsupported);
     }
```

**Comment by Cyan4973** [comment]
Nice catch @mitchblank !
I believe we also need to design a test to make sure we don't bring such dependency when `ZSTD_MULTITHREAD` is not defined.

**Comment by Cyan4973** [comment]
An important point : 
As long as `ZSTD_MULTITHREAD` is not defined, the library does not carry any dependency on `pthread`. Reason is, functions in `pool.c` get simplified to some shell single-thread equivalent.
See [source code](https://github.com/facebook/zstd/blob/dev/lib/common/pool.c#L212) for details.

In your case, removing `zstdmt` dependency achieves the same objective, and also makes it possible to _not_ import `zstdmt_compress.c` in the source tree. Since `zstdmt_compress.c` is only used for a few functions, `ZSTDMT_sizeof_CCtx()` and `ZSTDMT_setMTCtxParameter()`, the binary size is impacted a little bit, but just a little, because the bulk of the code is actually never invoked, so dead code elimination should get rid of it.

I guess you are not importing the dictionary builder either, as there you would catch additional difficulties with some invocations of `POOL_*()` functions. But ultimately, removing `pool.c` is not important. In single-thread mode, it carries no dependency to `pthread`, and it compiles to almost nothing. On the other hand, it makes it possible to express the code in a uniform way, mt or not, without having to decorate it with some `#define` sections, which is more efficient for maintenance.

For information, the library in its default configuration (`make -C lib`) is also compiled in single-thread mode, without any dependency on `pthread`. 

It's possible to compile the multi-thread version (`make -C lib lib-mt`) but we kept it out from default for the time being, precisely to avoid the dependency on `pthread`.

**Comment by mitchblank** [comment]
OK, duly noted about pool.c.  I actually was compiling it originally but I noticed that it didn't seem to be necessary for me, so I removed it from my build.  You are correct that I'm not using the dictionary builder at this time.

I can verify the dde9705 commit fixes my compile problem.
