### ISSUE TITLE
[QUESTION] shifting error codes?

### ISSUE THREAD

**Issue by revintec** [facebook/zstd#856]
Hi, I'm using zstd-jni, which uses zstd under the hood according to them
I'm trying to use an adaptive buffer size during compression to save memory:
allocate a minimal buffer, and try to compress. if failed with dstSizeTooSmall, replace the buffer with a larger one and retry. as you can see it relies on error codes returned from the underlying library

in previous versions the dstSizeTooSmall is -12, which I hard-coded into my code
but today when I upgraded zstd-jni(which includes the updated version of zstd)
the error code got changed to -13, and breaked a lot of stuff

so my question is:
1) is there a better way to achieve what I want?
2) if not, how can I detect dstSizeTooSmall error code reliably?
3) is there any documentation or code that I can refer to for error codes?
4) are these error codes pinned down, will they change in the future?

for 2, I won't do getErrorName() string match, and cache error code from a 0-sized buffer is also ugly.
for 3, zstd_errors.h seems not mentioning dstSizeTooSmall, maybe this is for internal uses only?
for 4, the changelog mentioned error code pin down, is dstSizeTooSmall included?

thx in advance

**Comment by Cyan4973** [comment]
Hi @revintec 

The supported way to analyse error codes is to use `enum ZSTD_ErrorCode` type exposed in `zstd_errors.h`.
When using the enum list, the client code is no longer dependent on any specific value.

Code `ZSTD_error_dstSize_tooSmall` can be found here : https://github.com/facebook/zstd/blob/dev/lib/common/zstd_errors.h#L64

Understanding that some clients check specific error codes using their associated integer values directly, we have recently decided to pin down error values. That's why each error code is now explicitly associated with a value. This exercise required to change all error codes to reach their assigned values, in order to respect a newly created allocation map. 
We expect to no longer need to modify error code values in the future.

**Comment by revintec** [comment]
Hi, thx for the reply

as I mentioned in my post, I'm using Java(through zstd-jni) so I can't access the underlying enum, that's why I'm hard-coding the error code. I do see ZSTD_error_dstSize_tooSmall, but its value is 70(where in contrast the real value seems to be -12 or -13) so I just thought it's unrelated, sorry about the overlook

all my problems are solved, I'm closing the issue

**Comment by Cyan4973** [comment]
Yes, that's a good reason.

Note that error code as read directly from function result is actually `(2^systemBits - 70)`, which can easily look like `-70` if you read it as an `int` on a [one-complement](https://en.wikipedia.org/wiki/Ones%27_complement) CPU (basically, almost any cpu these days).

It becomes `+70` when invoking `ZSTD_getErrorCode()`, which is the supported method in C (technically, it generates the `enum` itself, but that's equivalent to its value).

**Comment by revintec** [comment]
thx for the extra information, it's good to know
I uses long(64bit) values internally, and just thought all non-negative values are a success(returns size)
and all negative values are error codes, which is then matched against known values
