### ISSUE TITLE
v1.3.1 streaming questions

### ISSUE THREAD

**Issue by jmbnyc** [facebook/zstd#865]
I am attempting to use zstd for streaming compression over a socket. I am currently using zlib inflate and deflate for this but zstd has obvious advantages. I appreciate the relatively clean API and it maps fairly well to my existing deflate/inflate compression abstraction. 

I have one usage question and one request:

Question:

When using zlib for streaming compressed data over a long lived socket connection, the following procedure is used:
1. call deflate_init
2. use deflate and flush periodically as new data needs to be sent on socket
3. call deflate_end and close the socket

The zstd Streaming API offers init, compress, flush and finish APIs. 

The question is do I ever need to call "finish" or can I just compress and flush before sending on socket. I understand that finish writes the frame epilogue but it is not clear if it is required in a streaming context.

Ask:
Would it be possible to expose a method that allows a user to check a stream of bytes to know if they can be inflated:

Something like the following:

       bool is_inflatable(const char* p_, size_t byteCount_)
      {
        if (byteCount_ >= 4)
        {
          const uint32_t magic = *reinterpret_cast<const uint32_t*>(p_);
          if (magic == zstd_magic_u32)
          {
            return true;
          }
        }
        return false;
      }

Why do I want this: I want the far end of a socket connection to self discover if the stream is compressed or not. I want to read the first few bytes and determinate if compressed and what type of compression, zstd or zlib.

Thanks,
/JMB

**Comment by Cyan4973** [comment]
> do I ever need to call "finish" or can I just compress and flush before sending on socket. 

In general, it's cleaner to call `ZSTD_endStream()` when the stream is completely finished.
In your use case though, you might be able to get away without it.

Should you ever plan to store the stream, typically for log, and later on, want to invoke `ZSTD_decompress()` on a complete stream to regenerate its content, this operation will fail without the epilogue.

In your application, this might be a meaningless limitation. If you only have short-lived data, that get decompressed immediately, `flush()` after `flush()`, and forgot afterwards, you probably never need to call `ZSTD_endStream()`, because the "end of stream" becomes something implicit in your application.

> Would it be possible to expose a method that allows a user to check a stream of bytes to know if they can be inflated:

partially.
The function `ZSTD_isFrame()` is created for this usage : 
https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L644

Limitation is, this function is currently part of the experimental API section, and it will only detect the beginning of a frame.

If you plan on freely interleaving some data of different type right in the middle of a frame, you will need your own flag system to determine what is what.

**Comment by jmbnyc** [comment]
Yann,
Thanks for the quick response. I think you answered my question. I understand the requirement for the epilogue in the context of storing the stream. However, my use case is pure streaming of data across a socket so the "end" is when the socket closes. 

I did see the ZSTD_isFrame in the experimental API. My Ask was an open request that something similar to available in the current API. 

<<<
If you plan on freely interleaving some data of different type right in the middle of a frame, you will need your own flag system to determine what is what.
<<<

I do not plan to do any such thing, I am literally compressing the data and sending. The far end of the socket is reading data and then processing that data. The uncompressed data has its own framing which will guide the processing of the data, e.g. the compressed data represents a stream of messages.

I think we can mark this as closed.
Thanks again.

**Comment by Cyan4973** [comment]
Hi @jmbnyc ,
we are considering moving `ZSTD_isFrame()` into stable API in a future release.

However, the quality bar to meet "stable" API is much higher than "experimental" one. As a consequence, we have a few questions on several little details to settle. The intention is to make the API usage clear, with no or little side effects.
We would appreciate feedbacks on these questions.

`ZSTD_isFrame()` currently answer with a simple `0`/`1` return value to a deceptively simple question : is `src` input a frame ?

Well, that makes it necessary to unambiguously define what is a frame in this context.
Actually, the real question to which `ZSTD_isFrame()` answers : is the input decodable ?
`ZSTD_isFrame()` will answer `1` (yes) to any frame it can decode, be it a "zstd" frame, a "skippable" frame, or one in many supported "legacy" frame (which scope vary depending on compilation parameter `ZSTD_LEGACY_SUPPORT`).
So it's already quite more complex than the initial name make it sound.

We have several ways to answer to this situation : 
- Do nothing. Name is good enough, answer is good enough.
- Change the name, so that it more properly describes the scope. Typically `ZSTD_isDecodableFrame()`. Keep current behaviour.
- Restrict the scope, so that it answers the more specific question "is it a __zstd__ frame" ? Name would be changed to `ZSTD_isZstdFrame()`. This variant would answer with a `0` for skippable and legacy frames (i.e. non zstd ones).
- Expand the scope : instead of answering with only `0`/`1`, provide the exact frame type through an `enum` list. Function name would typically become `ZSTD_frameType()`. 
The `enum` list could keep the value `0` for `ZSTD_ft_unknown`, making it possible to use `ZSTD_frameType()` within a test the same way as `ZSTD_isFrame()` is used today. Then it would use positive values to distinguish "zstd" frame from "skippable" frames, from "legacy" frames.
   + A slightly more complex follow-up question is "how to distinguish between the 7 legacy formats". With the following possible answers : 
      * It's not necessary to distinguish them, a single enum is enough
      * Use one enum value per legacy format 

The more complete scope is obviously the last one.
But it needs to remain easy to understand and use.
It looks to me that these properties seem in good enough shape in this proposal, but a user's comment would help a lot determining that.

**Comment by jmbnyc** [comment]
Yann,
Thank you for the well formed response. Let me describe what I would want as a user. I want the ability to receive bytes over a socket connection and self discover if the bytes are inflatable with zstd or zlib or some other compression format. Thus, I want an API that takes a pointer to the byte stream and returns true or false (1 or 0)  if the stream can be decoded with zstd decompression. I don't care much about the type of frame. If the API returns true then my assumption is that I can decode with zstd and will call the decompress function to execute the decompress.
HTH,
/JMB
