### ISSUE TITLE
Why ZSTD and LZ4 framing formats are only partially compatible

### ISSUE THREAD

**Issue by scherepanov** [facebook/zstd#907]
Hi,
I wonder why you did not make LZ4 and ZSTD framing compatible.
That would be nice just to append lz4 file to zstd and have it decompressed by same utility.
If you asking why it needed...
I am dealing with real-time compression, with huge spikes. In time of low volume, ZSTD is a way to go. During spikes, you have to use LZ4. That is adaptive compression.
Having incompatible framing formats makes it by far harder than it should be.
In perfect word, should be single framing format that includes both LZ4 and ZSTD. I should be able to say "I am in a hurry" and compressor will switch to LZ4. Or say "low time" and compressor switch to ZSTD. Based on some predefined policy.
And, in perfect word you would have frame type "foreign compression" with frame length and compression type fields. I should be able to say "it is really low volume" and compress frame as LZMA in foreign compression frame type.
Well, our world is not perfect.
Thanks for reading!

**Comment by Cyan4973** [comment]
The `zstd` command line utility can do what you're asking for : 
provide it with a stream of frames, which can be either `zstd`, `lz4`, `zlib`, `xz`, `lzma` or `skippable` ones, and it will decompress them in sequence.

Decoding `lz4` frames requires `lz4` support, which is default policy since `v1.3.2`.

`libzstd` itself only supports Zstandard frames.
It felt like a good policy to keep each library in charge of its own format.
Hopefully, [`programs/fileio.c`](https://github.com/facebook/zstd/blob/dev/programs/fileio.c#L1446) can give you some clues on how it was done for `zstd` cli, if it can be useful in your program.

**Comment by scherepanov** [comment]
Thanks, will lookon example

**Comment by scherepanov** [comment]
Yes, zstd utility do decode mix of formats - lz4, zstd, lz4/zstd skip frames, lzma.
Very useful feature.
It is not done on library level, but still pretty good.
Thanks you!
