### ISSUE TITLE
ZStd hangs on files on random

### ISSUE THREAD

**Issue by markusriedl** [facebook/zstd#909]
Hi,

More of a question:
We (the company I work at) use zstd to compress a large amount of files (not in a batch fashion rather whenever files are ready to compressed). 
Usually this works fine, but randomly zstd does hang and never finishes compression. 
The state of the process then always remains as 'T'.

It does not seem to be related to input data, since the we retry the compression and then it works just fine. 

Are you possibly aware of any circumstances that would cause zstd to behave this way.
zstd version: 1.1.1

Best regards

**Comment by Cyan4973** [comment]
It's difficult to tell.
As you can guess, we use `zstd` within Facebook a pretty large number of times every day, and have not observe this behaviour so far.

I guess there are a number of points to clarify in order to understand the situation better : 
- Are you using the CLI or the API ?
- On which OS is the thread running ?
- Are you using multi-threading ?

Another potential clue : 
> T==  stopped, either by a job control signal or because it is being traced

Could there be a 3rd party process involved into this ?

**Comment by markusriedl** [comment]
Thank you for replying.

We currently use the CLI, as we start zstd out of process from a java process. 
It runs on a linux (ubuntu).
There is only one thread involved in (de)compressing a file.

**Comment by Cyan4973** [comment]
I just noticed you're running v1.1.1.
Does that sound possible for you to update to v1.3.2 (latest stable release) ?

**Comment by markusriedl** [comment]
Not out of the question, but do you suppose that something in v1.1.1 does cause this or why do you suggest it?

**Comment by Cyan4973** [comment]
I have no idea.
It's just that all metrics and tests we can gather at fleet scale use more recent versions, so they would not help to debug `1.1.1`.
