### ISSUE TITLE
-lrt is needed with glibc < 2.17 (rhel6 for example)

### ISSUE THREAD

**Issue by pixelb** [facebook/zstd#911]
clock_gettime() needs -lrt on el6
gnulib does the check like:

```
  LIB_CLOCK_GETTIME=
  AC_SUBST([LIB_CLOCK_GETTIME])
  gl_saved_libs=$LIBS
    AC_SEARCH_LIBS([clock_gettime], [rt posix4],
                   [test "$ac_cv_search_clock_gettime" = "none required" ||
                    LIB_CLOCK_GETTIME=$ac_cv_search_clock_gettime])
    AC_CHECK_FUNCS([clock_gettime clock_settime])
  LIBS=$gl_saved_libs

```

**Comment by Cyan4973** [comment]
Thanks for valuable feedback @pixelb .

`clock_gettime()` is not a strong necessity for `zstd`.
It's been selected for its improved accuracy, but is only useful for benchmark module, and a few optional status displays. We also have a backup implementation, using is the more standard `<time.h>`'s `clock_t clock()`.

I have no idea what's behind the `AC_*` family of macros, and I suspect we'd better not try to reproduce it. A simple fix is to add a macro condition [here](https://github.com/facebook/zstd/blob/dev/programs/util.h#L169), so that the backup implementation using `clock()` is generated instead. Though, at this stage, I'm unsure which macro we should check to ensure glibc version >= 2.17. [`PLATFORM_POSIX_VERSION`](https://github.com/facebook/zstd/blob/dev/programs/platform.h#L67) was supposed to encapsulate relevant condition, but it's either incomplete or improperly setup.

**Comment by pixelb** [comment]
Well generally POSIX doesn't specify which library contains what.
-lrt is required on solaris for example, and there are all sorts of other combos.

As a hack you could look for a proxy for determining clock_gettime is in the default c library.
I see that time.h includes features.h, so I would do:
```
#if defined __UCLIBC__ || ((__GLIBC__ == 2 && __GLIBC_MINOR__ >= 17) || __GLIBC__ > 2)
/* clock_gettime is available in the default c library.  */
#endif
```

**Comment by Cyan4973** [comment]
Currently working on a CentOS 6.2 VM, where the problem can be reproduced.

Unfortunately, the [documented method to check `_POSIX_TIMERS > 0`](https://linux.die.net/man/3/clock_gettime) doesn't seem to work : the test pass, but the linker nonetheless fails to find `clock_gettime()` afterwards.

**Comment by Cyan4973** [comment]
Your suggested macro test works well : 
`#if defined __UCLIBC__ || ((__GLIBC__ == 2 && __GLIBC_MINOR__ >= 17) || __GLIBC__ > 2)`

Downside is, some platform may not satisfy above condition (glibc / uclibc) yet support `clock_gettime()` properly. In which case, it will default on standard C's `clock()` instead, which means it will still compile properly, just suffer reduced benchmark accuracy.

If such a use case matter, I guess we can still enrich the detection macro later on ...
