### ISSUE TITLE
Need clarification on the benchmarking

### ISSUE THREAD

**Issue by scottchiefbaker** [facebook/zstd#930]
I apologize for a silly question, but can someone explain what the output of the benchmark stuff is:

```
 8#test.bin          :1872691200 -> 872584382 (2.146),  22.3 MB/s ,1166.8 MB/s
```

I looked in the man page, and documentation and couldn't figure out what each field was. My best guess is:

compression level#filename     input size -> compress_size (compression ratio), compression speed, decompression speed? Assuming that last one is decompression speed is the entire input compressed and then decompressed to measure that speed or how does that work?

**Comment by Cyan4973** [comment]
Yes, you are correct in your interpretation of the fields.
Indeed, it would probably be better to document it in the `man` page.

For both compression and decompression speed, the entire input is compressed / decompressed in-memory to measure speed. A compression / decompression run lasts at least 1 sec, so when files are small, they are compressed / decompressed several times per run, in order to improve measurement accuracy.  Your test file is ~1.8GB though, which is pretty large, so it most likely needs only one decompression per run.

**Comment by scottchiefbaker** [comment]
@Cyan4973 I've been looking for an excuse to submit a PR. Would you be willing to take a PR to update the man page with that information.

**Comment by Cyan4973** [comment]
👍  sure !

**Comment by scottchiefbaker** [comment]
Should I be sending a PR for `programs/zstd.1` or for `programs/zstd.1.md`? I'm guessing the markdown one is generated from the raw man page?

**Comment by Cyan4973** [comment]
It's the other way round :)
We create `zstd.1` from `zstd.1.md`, which is much easier to edit
