### ISSUE TITLE
ZSTD_compressStream always returns 1?

### ISSUE THREAD

**Issue by vulture** [facebook/zstd#942]
Just going by the example program streaming_compression.c, ZSTD_compressStream is called as follows:
`    toRead = ZSTD_compressStream(cstream, &output , &input);`
and then the next file read reads toRead number of bytes:
`    while( (read = fread_orDie(buffIn, toRead, fin)) ) {`
However, at some point between the last time I pulled zstd (probably almost a year at this point) and today, it seems like ZSTD_compressStream basically always returns 1. Which means we're reading 1 byte at a time. My compression speed dropped to a crawl as a result, since I was modelling after examples/streaming_compression.c. On a fresh compile on latest repo, streaming_compression.c seems to itself have this same problem. Or is there something I'm doing wrong here???

**Comment by Cyan4973** [comment]
Hi @vulture,
You are right ! 
I just looked into it, and indeed, this API returns `1`, while it should, according to its own documentation, return "a size hint, preferred nb of bytes to use as input for next function call".

To be fixed.

I guess we did not notice this because none of our performance tests use the result from this interface, and the other tests only care about format compliance. There's definitely something to do on the test side to detect such situation in the future.

**Comment by Cyan4973** [comment]
There is a feature branch, [fix942](https://github.com/facebook/zstd/tree/fix942), which is expected to fix this bug.

It's actually a pretty serious bug, where usage of `ZSTD_initCStream()` confuses the streaming state into believing that input will be empty (instead of "unknown"). As a consequence, the streaming interface creates a fake 1-byte buffer. As a consequence, data cannot be compressed ! Data is still, technically, a "valid frame", but it's actually expanded, due to additional headers...

The fix restores performance and interface behaviour as it should. 
It also adds a test to check that specific scenario (data expanded after usage of `ZSTD_initCStream()`).

**Comment by vulture** [comment]
Tested your 1 line fix using ZSTD_CONTENTSIZE_UNKNOWN instead of 0 for ZSTD_initCStream_srcSize and that fixed the issue for me in my app as well. Thanks a lot!!
