### ISSUE TITLE
ZDICT_trainFromBuffer_legacy() fails in HUF_writeCTable() in 1.3.2+

### ISSUE THREAD

**Issue by indygreg** [facebook/zstd#977]
After upgrading from 1.3.1 to 1.3.2 (or 1.3.3), a previously working call to `ZDICT_trainFromBuffer_legacy()` starts failing in `HUF_writeCTable()`. It is failing on the `if (maxSymbolValue > (256-128)) return ERROR(GENERIC);   /* should not happen : likely means source cannot be compressed */` line. `maxSymbolValue` during failure is `256`.

The `python-zstandard` code that triggers the failure is:

```
samples = []
for i in range(128):
    samples.append(b'foo' * 64)
    samples.append(b'bar' * 64)
    samples.append(b'foobar' * 64)

d = zstd.train_dictionary(8192, samples)
```

Translated to C, it is roughly:

```
ZDICT_legacy_params_t zparams;
memset(&zparams, 0, sizeof(zparams));

void* sampleBuffer = malloc(samplesSize);
void* sampleSizes = malloc(samplesLen * sizeof(size_t));
/* build data and sizes buffers */

void* dict = malloc(capacity);
size_t zresult = ZDICT_trainFromBuffer_legacy(dict, capacity,
    sampleBuffer, sampleSizes, (unsigned int)samplesLen,
    zparams);
```

Since the failing line has a "should not happen" comment, this smells like a bug and not an intended failure due to "bad" input.

I could produce a more easily reproducible test case if it would help.

**Comment by Cyan4973** [comment]
I suspect it's a relative of #304 .

We know we have a weakness in the dictionary format : 
it's not possible to create a conformant dictionary header when the literals (aka "rest of compression) is not compressible.

In "real world" scenario, it should never happens.
All use cases we have found so far are synthetic cases, manually created, which tend to be too regular.
Typically, it happens when all samples are just noise.
The main rule is that all characters should be present with exactly the same frequency in the literals list.

This sample set is different. It's clearly compressible. It's even trivial to compress.
What I _suspect_ is that the result of dictionary compression leaves _no literal_.
Why it did not happen with `v1.3.1` and does now with `v1.3.2` is unclear. Maybe dictionary compression with `v1.3.1` would leave some literals. Just one literal instead of zero would be enough to avoid such corner case.
If no literal is ever produces, statistics module just produce the minimum frequency of `1` for all characters, with the consequence that it's not compressible.

We have not spent much time into fixing this issue yet, since it's always associated with pathological synthetic dataset. That being said, it's not uncommon for someone playing with the dictionary builder API to inadvertently produce such pathological data set during early tests.

A tentative solution could be to produce a "fake" compression table for literals, with mostly flat statistics (but not completely) when such case happen. It would have barely any impact on compression ratio (and none in your example), but would be compatible with dictionary header format, hence would avoid resulting in an error.

**Comment by Cyan4973** [comment]
A fix is proposed in feature branch `fix304`.
I haven't tested exactly the scenario presented above, but the new test case added in `fuzzer` is a close relative, so I expect the fix to solve @indygreg's scenario too.

**Comment by Cyan4973** [comment]
fix merged into `dev` branch
