### ISSUE TITLE
Any somewhat reliable way to determine if file is compressed with zstd?

### ISSUE THREAD

**Issue by stmlange** [facebook/zstd#989]
Hi first of all,
thanks for this great compression and this project :-)

To some extend this is not an issue rather a question if there is a somewhat reliable way to determine if file is compressed with zstd. Assuming a case where one need an implementation to support the old legacy version (reading plain text files) and the new cool version where files are now compressed with zstd to save disk space.
There are multiple ways to solve this one by simply trying to extract the file and if it is not compressed this steps already fails and one might go for a backup method. However I was wondering if there is also a reliable magic header that indicates that the file is compressed with zstd (supported by different versions of zstd?).
I'm currently using the java implementation of zstd and I was thinking of something similar to checking if a InputStream is compressed (https://stackoverflow.com/questions/4818468/how-to-check-if-inputstream-is-gzipped).

I noticed that all files I created with zstd have the magic header of 0x184D2A50. Based on the docs this would indicate a skippable frame ID - 4 Bytes, Little endian format (any value from 0x184D2A50 to 0x184D2A5F). Is this always the case for the first frame and could this magic number be used similar to ``java.util.zip.GZIPInputStream.GZIP_MAGIC``?

I'm reporting this here since I feel this is a more general question about the format and not the implementation side. Could not find any related in the docs nor anything on a popular search engine.

Would appreciate any input.

**Comment by Cyan4973** [comment]
There are several possibilities to answer this question : 

- Read the [specification](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#zstandard-frames), which states that a zstd frame starts with 4 Bytes value `0xFD2FB528` in little-endian format.

It seems you already checked that, and the frame produced by your java library starts instead by a [skippable frame](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#skippable-frames). This is allowed by the format, though definitely not "standard". It allows the implementation to encapsulate any kind of "custom metadata", for example, the size of frame to follow. Such data however is implementation dependent, so it's not possible to rely on that.
Reading a skippable frame magic number is not a proof that it's followed by a zstd frame, but it's a pretty good hint. You could "bet" on this outcome, it would probably work in many circumstances.

Another possibility is to use the advanced API. Here, you'll find : 
- [`ZSTD_isFrame()`](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L655), which mostly tells if input data is a frame. In your case, it would answer "yes" (`1`), because it starts by a skippable frame magic number. So it's not significantly more precise than first solution.
- A more complete and complex solution is [ZSTD_getFrameHeader()](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L862), which will tell a lot more about the frame, including its type, and its content size. For a skippable frame, knowing the size allows to skip it, and start again the test on next frame.

Unfortunately, "advanced API" are not considered stable, so if you are using a binder, chances are, these functions are not exposed in your language of choice.

**Comment by stmlange** [comment]
Alright, thanks for the additional input and hinters.
I'll close this since the rest is to decide on my side to use or not to use this (plus the question if its available in the language of choice) :-)
